*
* Generated by py/gen_compiled_acts.py - do not edit by hand
* ActBlitTable: (sprite & 7)*2 + (X&1) -> abs addresses
* Sprites $10-$17, bank #16. Act3BlitTable: index*2 + (X&1)
* for stork $30/$18/$2C, sack $07, junior $0F. Y = SHR offset,
* DBR = $01, returns via RTS
*

ActBlitGo
* X = index*2 into ActBlitTable; JMP so blit RTS returns to caller.
	jmp	(ActBlitTable,x)

ActBlitTable
	da	CA0_E	; clapper open, left spr=$10 even
	da	CA0_O	; clapper open, left spr=$10 odd
	da	CA1_E	; clapper open, right spr=$11 even
	da	CA1_O	; clapper open, right spr=$11 odd
	da	CA2_E	; board, left spr=$12 even
	da	CA2_O	; board, left spr=$12 odd
	da	CA3_E	; board, right spr=$13 even
	da	CA3_O	; board, right spr=$13 odd
	da	CA4_E	; clapper mid, left spr=$14 even
	da	CA4_O	; clapper mid, left spr=$14 odd
	da	CA5_E	; clapper mid, right spr=$15 even
	da	CA5_O	; clapper mid, right spr=$15 odd
	da	CA6_E	; clapper shut, left spr=$16 even
	da	CA6_O	; clapper shut, left spr=$16 odd
	da	CA7_E	; clapper shut, right spr=$17 even
	da	CA7_O	; clapper shut, right spr=$17 odd

Act3BlitGo
* X = index*2 into Act3BlitTable; JMP so blit RTS returns to caller.
	jmp	(Act3BlitTable,x)

Act3BlitTable
	da	C30_E	; stork head spr=$30 even
	da	C30_O	; stork head spr=$30 odd
	da	C31_E	; stork spr=$18 even
	da	C31_O	; stork spr=$18 odd
	da	C32_E	; stork flap spr=$2C even
	da	C32_O	; stork flap spr=$2C odd
	da	C33_E	; sack spr=$07 even
	da	C33_O	; sack spr=$07 odd
	da	C34_E	; junior spr=$0F even
	da	C34_O	; junior spr=$0F odd

CA0_E
	php
	rep	#$20
	lda	$2325,y
	and	#$0FF0
	ora	#$1001
	sta	$2325,y
	lda	$23C4,y
	and	#$0FF0
	ora	#$1001
	sta	$23C4,y
	lda	$2465,y
	and	#$0FF0
	ora	#$1001
	sta	$2465,y
	lda	$2502,y
	and	#$00F0
	ora	#$1101
	sta	$2502,y
	lda	$2504,y
	and	#$0F00
	ora	#$1011
	sta	$2504,y
	lda	$25A1,y
	and	#$0FF0
	ora	#$1001
	sta	$25A1,y
	lda	$2642,y
	and	#$0FF0
	ora	#$1001
	sta	$2642,y
	lda	$26E1,y
	and	#$0F00
	ora	#$1011
	sta	$26E1,y
	sep	#$20
	lda	$2286,y
	and	#$0F
	ora	#$10
	sta	$2286,y
	lda	#$11
	sta	$2463,y
	lda	#$11
	sta	$25A4,y
	lda	$2641,y
	and	#$0F
	ora	#$10
	sta	$2641,y
	lda	$26E0,y
	and	#$F0
	ora	#$01
	sta	$26E0,y
	plp
	rts

CA0_O
	php
	rep	#$20
	lda	$2463,y
	and	#$0FF0
	ora	#$1001
	sta	$2463,y
	lda	#$1111
	sta	$2504,y
	lda	$25A4,y
	and	#$0FF0
	ora	#$1001
	sta	$25A4,y
	lda	#$1111
	sta	$26E1,y
	sep	#$20
	lda	$2286,y
	and	#$F0
	ora	#$01
	sta	$2286,y
	lda	#$11
	sta	$2326,y
	lda	#$11
	sta	$23C5,y
	lda	#$11
	sta	$2466,y
	lda	#$11
	sta	$2503,y
	lda	#$11
	sta	$25A2,y
	lda	$2641,y
	and	#$F0
	ora	#$01
	sta	$2641,y
	lda	#$11
	sta	$2643,y
	plp
	rts

CA1_E
	php
	rep	#$20
	lda	$2004,y
	and	#$0FF0
	ora	#$1001
	sta	$2004,y
	lda	$2142,y
	and	#$00F0
	ora	#$1101
	sta	$2142,y
	lda	$2144,y
	and	#$0F00
	ora	#$1011
	sta	$2144,y
	lda	$21E1,y
	and	#$0FF0
	ora	#$1001
	sta	$21E1,y
	lda	$2282,y
	and	#$0FF0
	ora	#$1001
	sta	$2282,y
	lda	$2321,y
	and	#$0F00
	ora	#$1011
	sta	$2321,y
	sep	#$20
	lda	#$11
	sta	$20A3,y
	lda	#$11
	sta	$21E4,y
	lda	$2280,y
	and	#$F0
	ora	#$01
	sta	$2280,y
	lda	$2320,y
	and	#$F0
	ora	#$01
	sta	$2320,y
	lda	#$11
	sta	$23C1,y
	plp
	rts

CA1_O
	php
	rep	#$20
	lda	$20A3,y
	and	#$0FF0
	ora	#$1001
	sta	$20A3,y
	lda	#$1111
	sta	$2144,y
	lda	$21E4,y
	and	#$0FF0
	ora	#$1001
	sta	$21E4,y
	lda	#$1111
	sta	$2321,y
	lda	$23C1,y
	and	#$0FF0
	ora	#$1001
	sta	$23C1,y
	sep	#$20
	lda	#$11
	sta	$2005,y
	lda	#$11
	sta	$2143,y
	lda	#$11
	sta	$21E2,y
	lda	$2281,y
	and	#$0F
	ora	#$10
	sta	$2281,y
	lda	#$11
	sta	$2283,y
	plp
	rts

CA2_E
	php
	rep	#$20
	lda	#$1111
	sta	$2001,y
	lda	#$1111
	sta	$2003,y
	lda	#$1111
	sta	$2005,y
	lda	$20A1,y
	and	#$F0F0
	ora	#$0101
	sta	$20A1,y
	lda	$20A4,y
	and	#$F00F
	ora	#$0110
	sta	$20A4,y
	lda	$2141,y
	and	#$00F0
	ora	#$1101
	sta	$2141,y
	lda	$2143,y
	and	#$0FF0
	ora	#$1001
	sta	$2143,y
	lda	$2145,y
	and	#$F000
	ora	#$0111
	sta	$2145,y
	lda	$21E1,y
	and	#$00F0
	ora	#$1101
	sta	$21E1,y
	lda	#$1111
	sta	$21E3,y
	lda	#$1111
	sta	$21E5,y
	lda	$23C1,y
	and	#$F0F0
	ora	#$0101
	sta	$23C1,y
	lda	$23C3,y
	and	#$F0F0
	ora	#$0101
	sta	$23C3,y
	lda	$2461,y
	and	#$F0F0
	ora	#$0101
	sta	$2461,y
	lda	$2463,y
	and	#$F000
	ora	#$0111
	sta	$2463,y
	lda	$2501,y
	and	#$F0F0
	ora	#$0101
	sta	$2501,y
	lda	$2503,y
	and	#$F0F0
	ora	#$0101
	sta	$2503,y
	lda	$25A2,y
	and	#$F0F0
	ora	#$0101
	sta	$25A2,y
	lda	$26E1,y
	and	#$00F0
	ora	#$1101
	sta	$26E1,y
	lda	#$1111
	sta	$26E3,y
	lda	$26E5,y
	and	#$0F00
	ora	#$1011
	sta	$26E5,y
	sep	#$20
	lda	$2000,y
	and	#$F0
	ora	#$01
	sta	$2000,y
	lda	$2281,y
	and	#$F0
	ora	#$01
	sta	$2281,y
	lda	$2321,y
	and	#$F0
	ora	#$01
	sta	$2321,y
	lda	$2323,y
	and	#$0F
	ora	#$10
	sta	$2323,y
	lda	#$11
	sta	$2325,y
	lda	$25A1,y
	and	#$F0
	ora	#$01
	sta	$25A1,y
	lda	#$11
	sta	$25A5,y
	lda	$2641,y
	and	#$F0
	ora	#$01
	sta	$2641,y
	plp
	rts

CA2_O
	php
	rep	#$20
	lda	#$1111
	sta	$2001,y
	lda	#$1111
	sta	$2003,y
	lda	#$1111
	sta	$2005,y
	lda	$20A3,y
	and	#$F00F
	ora	#$0110
	sta	$20A3,y
	lda	$2143,y
	and	#$000F
	ora	#$1110
	sta	$2143,y
	lda	$2145,y
	and	#$0FF0
	ora	#$1001
	sta	$2145,y
	lda	#$1111
	sta	$21E3,y
	lda	#$1111
	sta	$21E5,y
	lda	$2322,y
	and	#$F00F
	ora	#$0110
	sta	$2322,y
	lda	$2325,y
	and	#$0FF0
	ora	#$1001
	sta	$2325,y
	lda	$23C2,y
	and	#$0F0F
	ora	#$1010
	sta	$23C2,y
	lda	$23C4,y
	and	#$0F0F
	ora	#$1010
	sta	$23C4,y
	lda	$2462,y
	and	#$000F
	ora	#$1110
	sta	$2462,y
	lda	$2464,y
	and	#$0F0F
	ora	#$1010
	sta	$2464,y
	lda	$2502,y
	and	#$0F0F
	ora	#$1010
	sta	$2502,y
	lda	$2504,y
	and	#$0F0F
	ora	#$1010
	sta	$2504,y
	lda	$25A3,y
	and	#$0F0F
	ora	#$1010
	sta	$25A3,y
	lda	$25A5,y
	and	#$0FF0
	ora	#$1001
	sta	$25A5,y
	lda	#$1111
	sta	$26E3,y
	lda	#$1111
	sta	$26E5,y
	sep	#$20
	lda	$20A2,y
	and	#$0F
	ora	#$10
	sta	$20A2,y
	lda	$20A6,y
	and	#$0F
	ora	#$10
	sta	$20A6,y
	lda	#$11
	sta	$2142,y
	lda	#$11
	sta	$21E2,y
	lda	$2282,y
	and	#$0F
	ora	#$10
	sta	$2282,y
	lda	$25A2,y
	and	#$0F
	ora	#$10
	sta	$25A2,y
	lda	$2642,y
	and	#$0F
	ora	#$10
	sta	$2642,y
	lda	#$11
	sta	$26E2,y
	plp
	rts

CA3_E
	php
	rep	#$20
	lda	#$1111
	sta	$2001,y
	lda	#$1111
	sta	$2003,y
	lda	$2005,y
	and	#$0F00
	ora	#$1011
	sta	$2005,y
	lda	$20A2,y
	and	#$F00F
	ora	#$0110
	sta	$20A2,y
	lda	$20A5,y
	and	#$0F0F
	ora	#$1010
	sta	$20A5,y
	lda	$2141,y
	and	#$0FF0
	ora	#$1001
	sta	$2141,y
	lda	$2143,y
	and	#$F000
	ora	#$0111
	sta	$2143,y
	lda	$2145,y
	and	#$0F0F
	ora	#$1010
	sta	$2145,y
	lda	#$1111
	sta	$21E1,y
	lda	#$1111
	sta	$21E3,y
	lda	$21E5,y
	and	#$0F00
	ora	#$1011
	sta	$21E5,y
	lda	$2320,y
	and	#$00F0
	ora	#$1101
	sta	$2320,y
	lda	#$1111
	sta	$26E1,y
	lda	#$1111
	sta	$26E3,y
	lda	$26E5,y
	and	#$0F00
	ora	#$1011
	sta	$26E5,y
	sep	#$20
	lda	$2000,y
	and	#$F0
	ora	#$01
	sta	$2000,y
	lda	$20A0,y
	and	#$F0
	ora	#$01
	sta	$20A0,y
	lda	$2140,y
	and	#$F0
	ora	#$01
	sta	$2140,y
	lda	$21E0,y
	and	#$F0
	ora	#$01
	sta	$21E0,y
	lda	$2286,y
	and	#$0F
	ora	#$10
	sta	$2286,y
	lda	$2326,y
	and	#$0F
	ora	#$10
	sta	$2326,y
	lda	$23C1,y
	and	#$0F
	ora	#$10
	sta	$23C1,y
	lda	$23C6,y
	and	#$0F
	ora	#$10
	sta	$23C6,y
	lda	$2461,y
	and	#$0F
	ora	#$10
	sta	$2461,y
	lda	$2466,y
	and	#$0F
	ora	#$10
	sta	$2466,y
	lda	$2501,y
	and	#$0F
	ora	#$10
	sta	$2501,y
	lda	$2506,y
	and	#$0F
	ora	#$10
	sta	$2506,y
	lda	$25A1,y
	and	#$0F
	ora	#$10
	sta	$25A1,y
	lda	$25A6,y
	and	#$0F
	ora	#$10
	sta	$25A6,y
	lda	$2646,y
	and	#$0F
	ora	#$10
	sta	$2646,y
	lda	$26E0,y
	and	#$F0
	ora	#$01
	sta	$26E0,y
	plp
	rts

CA3_O
	php
	rep	#$20
	lda	#$1111
	sta	$2001,y
	lda	#$1111
	sta	$2003,y
	lda	#$1111
	sta	$2005,y
	lda	$20A1,y
	and	#$F00F
	ora	#$0110
	sta	$20A1,y
	lda	$20A5,y
	and	#$F0F0
	ora	#$0101
	sta	$20A5,y
	lda	$2141,y
	and	#$000F
	ora	#$1110
	sta	$2141,y
	lda	$2143,y
	and	#$0FF0
	ora	#$1001
	sta	$2143,y
	lda	$2145,y
	and	#$F000
	ora	#$0111
	sta	$2145,y
	lda	#$1111
	sta	$21E1,y
	lda	#$1111
	sta	$21E3,y
	lda	#$1111
	sta	$21E5,y
	lda	$2321,y
	and	#$0F00
	ora	#$1011
	sta	$2321,y
	lda	#$1111
	sta	$26E1,y
	lda	#$1111
	sta	$26E3,y
	lda	#$1111
	sta	$26E5,y
	sep	#$20
	lda	$20A4,y
	and	#$0F
	ora	#$10
	sta	$20A4,y
	lda	$2286,y
	and	#$F0
	ora	#$01
	sta	$2286,y
	lda	$2326,y
	and	#$F0
	ora	#$01
	sta	$2326,y
	lda	$23C1,y
	and	#$F0
	ora	#$01
	sta	$23C1,y
	lda	$23C6,y
	and	#$F0
	ora	#$01
	sta	$23C6,y
	lda	$2461,y
	and	#$F0
	ora	#$01
	sta	$2461,y
	lda	$2466,y
	and	#$F0
	ora	#$01
	sta	$2466,y
	lda	$2501,y
	and	#$F0
	ora	#$01
	sta	$2501,y
	lda	$2506,y
	and	#$F0
	ora	#$01
	sta	$2506,y
	lda	$25A1,y
	and	#$F0
	ora	#$01
	sta	$25A1,y
	lda	$25A6,y
	and	#$F0
	ora	#$01
	sta	$25A6,y
	lda	$2646,y
	and	#$F0
	ora	#$01
	sta	$2646,y
	plp
	rts

CA4_E
	php
	rep	#$20
	lda	$23C5,y
	and	#$0F00
	ora	#$1011
	sta	$23C5,y
	lda	$2462,y
	and	#$00F0
	ora	#$1101
	sta	$2462,y
	lda	$2501,y
	and	#$00F0
	ora	#$1101
	sta	$2501,y
	lda	#$1111
	sta	$2503,y
	lda	$2505,y
	and	#$0F00
	ora	#$1011
	sta	$2505,y
	lda	$25A0,y
	and	#$00F0
	ora	#$1101
	sta	$25A0,y
	lda	$25A4,y
	and	#$00F0
	ora	#$1101
	sta	$25A4,y
	lda	$2640,y
	and	#$0FF0
	ora	#$1001
	sta	$2640,y
	lda	$2642,y
	and	#$00F0
	ora	#$1101
	sta	$2642,y
	lda	$26E1,y
	and	#$0F00
	ora	#$1011
	sta	$26E1,y
	sep	#$20
	lda	$2326,y
	and	#$0F
	ora	#$10
	sta	$2326,y
	lda	$26E0,y
	and	#$F0
	ora	#$01
	sta	$26E0,y
	plp
	rts

CA4_O
	php
	rep	#$20
	lda	$23C5,y
	and	#$00F0
	ora	#$1101
	sta	$23C5,y
	lda	$2463,y
	and	#$0F00
	ora	#$1011
	sta	$2463,y
	lda	#$1111
	sta	$2503,y
	lda	#$1111
	sta	$2505,y
	lda	$25A1,y
	and	#$0F00
	ora	#$1011
	sta	$25A1,y
	lda	$25A5,y
	and	#$0F00
	ora	#$1011
	sta	$25A5,y
	lda	$2643,y
	and	#$0F00
	ora	#$1011
	sta	$2643,y
	lda	#$1111
	sta	$26E1,y
	sep	#$20
	lda	$2326,y
	and	#$F0
	ora	#$01
	sta	$2326,y
	lda	#$11
	sta	$2502,y
	lda	#$11
	sta	$2641,y
	plp
	rts

CA5_E
	php
	rep	#$20
	lda	$2144,y
	and	#$0FF0
	ora	#$1001
	sta	$2144,y
	lda	$21E4,y
	and	#$0F0F
	ora	#$1010
	sta	$21E4,y
	lda	$2281,y
	and	#$0F00
	ora	#$1011
	sta	$2281,y
	lda	$2320,y
	and	#$00F0
	ora	#$1101
	sta	$2320,y
	lda	#$1111
	sta	$2322,y
	lda	$2324,y
	and	#$0F00
	ora	#$1011
	sta	$2324,y
	lda	$23C3,y
	and	#$0F00
	ora	#$1011
	sta	$23C3,y
	lda	$2461,y
	and	#$0F00
	ora	#$1011
	sta	$2461,y
	sep	#$20
	lda	$21E3,y
	and	#$F0
	ora	#$01
	sta	$21E3,y
	lda	$2285,y
	and	#$0F
	ora	#$10
	sta	$2285,y
	lda	$2500,y
	and	#$F0
	ora	#$01
	sta	$2500,y
	plp
	rts

CA5_O
	php
	rep	#$20
	lda	$21E4,y
	and	#$F000
	ora	#$0111
	sta	$21E4,y
	lda	$2281,y
	and	#$00F0
	ora	#$1101
	sta	$2281,y
	lda	#$1111
	sta	$2322,y
	lda	#$1111
	sta	$2324,y
	lda	$23C3,y
	and	#$00F0
	ora	#$1101
	sta	$23C3,y
	lda	$2461,y
	and	#$00F0
	ora	#$1101
	sta	$2461,y
	sep	#$20
	lda	#$11
	sta	$2145,y
	lda	$2285,y
	and	#$F0
	ora	#$01
	sta	$2285,y
	lda	#$11
	sta	$2321,y
	lda	$2501,y
	and	#$0F
	ora	#$10
	sta	$2501,y
	plp
	rts

CA6_E
	php
	rep	#$20
	lda	#$1111
	sta	$25A1,y
	lda	#$1111
	sta	$25A3,y
	lda	$25A5,y
	and	#$0F00
	ora	#$1011
	sta	$25A5,y
	lda	$2640,y
	and	#$0FF0
	ora	#$1001
	sta	$2640,y
	lda	$2642,y
	and	#$F00F
	ora	#$0110
	sta	$2642,y
	lda	$26E1,y
	and	#$F000
	ora	#$0111
	sta	$26E1,y
	lda	$26E4,y
	and	#$F00F
	ora	#$0110
	sta	$26E4,y
	sep	#$20
	lda	$25A0,y
	and	#$F0
	ora	#$01
	sta	$25A0,y
	lda	$2645,y
	and	#$0F
	ora	#$10
	sta	$2645,y
	lda	$26E0,y
	and	#$F0
	ora	#$01
	sta	$26E0,y
	plp
	rts

CA6_O
	php
	rep	#$20
	lda	#$1111
	sta	$25A1,y
	lda	#$1111
	sta	$25A3,y
	lda	#$1111
	sta	$25A5,y
	lda	$2641,y
	and	#$F000
	ora	#$0111
	sta	$2641,y
	lda	$2644,y
	and	#$F00F
	ora	#$0110
	sta	$2644,y
	lda	$26E1,y
	and	#$0F00
	ora	#$1011
	sta	$26E1,y
	lda	$26E3,y
	and	#$F00F
	ora	#$0110
	sta	$26E3,y
	sep	#$20
	lda	$26E6,y
	and	#$0F
	ora	#$10
	sta	$26E6,y
	plp
	rts

CA7_E
	php
	rep	#$20
	lda	#$1111
	sta	$25A1,y
	lda	#$1111
	sta	$25A3,y
	lda	$25A5,y
	and	#$0F00
	ora	#$1011
	sta	$25A5,y
	lda	$2642,y
	and	#$F00F
	ora	#$0110
	sta	$2642,y
	lda	$2645,y
	and	#$0F0F
	ora	#$1010
	sta	$2645,y
	lda	$26E1,y
	and	#$F00F
	ora	#$0110
	sta	$26E1,y
	lda	$26E5,y
	and	#$0FF0
	ora	#$1001
	sta	$26E5,y
	sep	#$20
	lda	$25A0,y
	and	#$F0
	ora	#$01
	sta	$25A0,y
	lda	$2640,y
	and	#$F0
	ora	#$01
	sta	$2640,y
	lda	$26E4,y
	and	#$0F
	ora	#$10
	sta	$26E4,y
	plp
	rts

CA7_O
	php
	rep	#$20
	lda	#$1111
	sta	$25A1,y
	lda	#$1111
	sta	$25A3,y
	lda	#$1111
	sta	$25A5,y
	lda	$2641,y
	and	#$F00F
	ora	#$0110
	sta	$2641,y
	lda	$2645,y
	and	#$F0F0
	ora	#$0101
	sta	$2645,y
	lda	$26E3,y
	and	#$F00F
	ora	#$0110
	sta	$26E3,y
	sep	#$20
	lda	$2644,y
	and	#$0F
	ora	#$10
	sta	$2644,y
	lda	$26E1,y
	and	#$F0
	ora	#$01
	sta	$26E1,y
	lda	#$11
	sta	$26E6,y
	plp
	rts

C30_E
	php
	rep	#$20
	lda	$21E4,y
	and	#$0FF0
	ora	#$1001
	sta	$21E4,y
	lda	$2280,y
	and	#$00F0
	ora	#$DD0D
	sta	$2280,y
	lda	#$D1DD
	sta	$2282,y
	lda	#$1111
	sta	$2284,y
	lda	$2323,y
	and	#$00F0
	ora	#$1101
	sta	$2323,y
	lda	$2325,y
	and	#$0F00
	ora	#$1011
	sta	$2325,y
	lda	#$1111
	sta	$23C4,y
	sep	#$20
	lda	$23C6,y
	and	#$0F
	ora	#$10
	sta	$23C6,y
	plp
	rts

C30_O
	php
	rep	#$20
	lda	#$DDDD
	sta	$2281,y
	lda	#$11DD
	sta	$2283,y
	lda	$2285,y
	and	#$0F00
	ora	#$1011
	sta	$2285,y
	lda	#$1111
	sta	$2325,y
	lda	#$1111
	sta	$23C5,y
	sep	#$20
	lda	#$11
	sta	$21E5,y
	lda	#$11
	sta	$2324,y
	lda	$23C4,y
	and	#$F0
	ora	#$01
	sta	$23C4,y
	plp
	rts

C31_E
	php
	rep	#$20
	lda	$2002,y
	and	#$0FF0
	ora	#$1001
	sta	$2002,y
	lda	$20A2,y
	and	#$00F0
	ora	#$1101
	sta	$20A2,y
	lda	#$1111
	sta	$2142,y
	lda	$21E1,y
	and	#$00F0
	ora	#$1101
	sta	$21E1,y
	lda	$21E3,y
	and	#$0F00
	ora	#$1011
	sta	$21E3,y
	lda	#$1111
	sta	$2281,y
	lda	$2283,y
	and	#$0F00
	ora	#$1011
	sta	$2283,y
	lda	#$1111
	sta	$2321,y
	lda	#$1111
	sta	$2323,y
	lda	$2325,y
	and	#$0F00
	ora	#$1011
	sta	$2325,y
	lda	$23C0,y
	and	#$00F0
	ora	#$1101
	sta	$23C0,y
	lda	#$1111
	sta	$23C2,y
	lda	#$1111
	sta	$23C4,y
	lda	#$1111
	sta	$2461,y
	lda	#$1111
	sta	$2463,y
	sep	#$20
	lda	$2144,y
	and	#$0F
	ora	#$10
	sta	$2144,y
	lda	$2320,y
	and	#$F0
	ora	#$01
	sta	$2320,y
	plp
	rts

C31_O
	php
	rep	#$20
	lda	$20A3,y
	and	#$0F00
	ora	#$1011
	sta	$20A3,y
	lda	#$1111
	sta	$2143,y
	lda	#$1111
	sta	$21E3,y
	lda	$2281,y
	and	#$00F0
	ora	#$1101
	sta	$2281,y
	lda	#$1111
	sta	$2283,y
	lda	#$1111
	sta	$2321,y
	lda	#$1111
	sta	$2323,y
	lda	#$1111
	sta	$2325,y
	lda	#$1111
	sta	$23C1,y
	lda	#$1111
	sta	$23C3,y
	lda	$23C5,y
	and	#$0F00
	ora	#$1011
	sta	$23C5,y
	lda	#$1111
	sta	$2462,y
	lda	$2464,y
	and	#$0F00
	ora	#$1011
	sta	$2464,y
	sep	#$20
	lda	#$11
	sta	$2003,y
	lda	$2142,y
	and	#$F0
	ora	#$01
	sta	$2142,y
	lda	#$11
	sta	$21E2,y
	lda	$2461,y
	and	#$F0
	ora	#$01
	sta	$2461,y
	plp
	rts

C32_E
	php
	rep	#$20
	lda	#$1111
	sta	$2281,y
	lda	#$1111
	sta	$2283,y
	lda	$2320,y
	and	#$00F0
	ora	#$1101
	sta	$2320,y
	lda	#$1111
	sta	$2322,y
	lda	#$1111
	sta	$2324,y
	lda	#$1111
	sta	$23C1,y
	lda	#$1111
	sta	$23C3,y
	lda	$23C5,y
	and	#$0F00
	ora	#$1011
	sta	$23C5,y
	lda	#$1111
	sta	$2461,y
	lda	$2463,y
	and	#$0F00
	ora	#$1011
	sta	$2463,y
	lda	$2501,y
	and	#$00F0
	ora	#$1101
	sta	$2501,y
	lda	$2503,y
	and	#$0F00
	ora	#$1011
	sta	$2503,y
	lda	#$1111
	sta	$25A2,y
	lda	$2642,y
	and	#$00F0
	ora	#$1101
	sta	$2642,y
	lda	$26E2,y
	and	#$0FF0
	ora	#$1001
	sta	$26E2,y
	sep	#$20
	lda	$23C0,y
	and	#$F0
	ora	#$01
	sta	$23C0,y
	lda	$25A4,y
	and	#$0F
	ora	#$10
	sta	$25A4,y
	plp
	rts

C32_O
	php
	rep	#$20
	lda	#$1111
	sta	$2282,y
	lda	$2284,y
	and	#$0F00
	ora	#$1011
	sta	$2284,y
	lda	#$1111
	sta	$2321,y
	lda	#$1111
	sta	$2323,y
	lda	$2325,y
	and	#$0F00
	ora	#$1011
	sta	$2325,y
	lda	#$1111
	sta	$23C1,y
	lda	#$1111
	sta	$23C3,y
	lda	#$1111
	sta	$23C5,y
	lda	$2461,y
	and	#$00F0
	ora	#$1101
	sta	$2461,y
	lda	#$1111
	sta	$2463,y
	lda	#$1111
	sta	$2503,y
	lda	#$1111
	sta	$25A3,y
	lda	$2643,y
	and	#$0F00
	ora	#$1011
	sta	$2643,y
	sep	#$20
	lda	$2281,y
	and	#$F0
	ora	#$01
	sta	$2281,y
	lda	#$11
	sta	$2502,y
	lda	$25A2,y
	and	#$F0
	ora	#$01
	sta	$25A2,y
	lda	#$11
	sta	$26E3,y
	plp
	rts

C33_E
	php
	rep	#$20
	lda	$2461,y
	and	#$0F00
	ora	#$A0AA
	sta	$2461,y
	lda	#$AAAA
	sta	$2501,y
	lda	#$AAAA
	sta	$25A1,y
	lda	$2641,y
	and	#$0F00
	ora	#$A0AA
	sta	$2641,y
	sep	#$20
	lda	$2321,y
	and	#$F0
	ora	#$01
	sta	$2321,y
	lda	$23C1,y
	and	#$F0
	ora	#$01
	sta	$23C1,y
	lda	$2500,y
	and	#$F0
	ora	#$0A
	sta	$2500,y
	lda	$25A0,y
	and	#$F0
	ora	#$0A
	sta	$25A0,y
	plp
	rts

C33_O
	php
	rep	#$20
	lda	$2461,y
	and	#$00F0
	ora	#$AA0A
	sta	$2461,y
	lda	#$AAAA
	sta	$2501,y
	lda	#$AAAA
	sta	$25A1,y
	lda	$2641,y
	and	#$00F0
	ora	#$AA0A
	sta	$2641,y
	sep	#$20
	lda	$2322,y
	and	#$0F
	ora	#$10
	sta	$2322,y
	lda	$23C2,y
	and	#$0F
	ora	#$10
	sta	$23C2,y
	lda	$2503,y
	and	#$0F
	ora	#$A0
	sta	$2503,y
	lda	$25A3,y
	and	#$0F
	ora	#$A0
	sta	$25A3,y
	plp
	rts

C34_E
	php
	rep	#$20
	lda	$23C3,y
	and	#$0F00
	ora	#$D0DD
	sta	$23C3,y
	lda	#$DDDD
	sta	$2463,y
	lda	$2503,y
	and	#$00F0
	ora	#$DD0D
	sta	$2503,y
	lda	#$DDDD
	sta	$25A3,y
	lda	$2643,y
	and	#$0F00
	ora	#$D0DD
	sta	$2643,y
	sep	#$20
	lda	$2462,y
	and	#$F0
	ora	#$0D
	sta	$2462,y
	lda	$25A2,y
	and	#$F0
	ora	#$0D
	sta	$25A2,y
	plp
	rts

C34_O
	php
	rep	#$20
	lda	$23C3,y
	and	#$00F0
	ora	#$DD0D
	sta	$23C3,y
	lda	#$DDDD
	sta	$2463,y
	lda	$2504,y
	and	#$0F00
	ora	#$D0DD
	sta	$2504,y
	lda	#$DDDD
	sta	$25A3,y
	lda	$2643,y
	and	#$00F0
	ora	#$DD0D
	sta	$2643,y
	sep	#$20
	lda	$2465,y
	and	#$0F
	ora	#$D0
	sta	$2465,y
	lda	$25A5,y
	and	#$0F
	ora	#$D0
	sta	$25A5,y
	plp
	rts

	mx	%00

