*
* Generated by py/gen_compiled_points.py - do not edit by hand
* PointsBlitTable: (ACT_SPR&3)*2 + (X&1) -> abs addresses
* Sprites $28-$2B; opaque ink forced to SHR pen 1 (white).
*

PointsBlitGo
* X = index*2 into PointsBlitTable; JMP so blit RTS returns to caller.
	jmp	(PointsBlitTable,x)

PointsBlitTable
	da	CP0_E	; Pts200 spr=$28 white even
	da	CP0_O	; Pts200 spr=$28 white odd
	da	CP1_E	; Pts400 spr=$29 white even
	da	CP1_O	; Pts400 spr=$29 white odd
	da	CP2_E	; Pts800 spr=$2A white even
	da	CP2_O	; Pts800 spr=$2A white odd
	da	CP3_E	; Pts1600 spr=$2B white even
	da	CP3_O	; Pts1600 spr=$2B white odd

CP0_E
	php
	rep	#$20
	lda	$2460,y
	and	#$0FF0
	ora	#$1001
	sta	$2460,y
	sep	#$20
	lda	#$11
	sta	$21E1,y
	lda	#$11
	sta	$21E3,y
	lda	$21E5,y
	and	#$0F
	ora	#$10
	sta	$21E5,y
	lda	$2280,y
	and	#$F0
	ora	#$01
	sta	$2280,y
	lda	$2282,y
	and	#$0F
	ora	#$10
	sta	$2282,y
	lda	$2284,y
	and	#$F0
	ora	#$01
	sta	$2284,y
	lda	$2321,y
	and	#$F0
	ora	#$01
	sta	$2321,y
	lda	$2324,y
	and	#$F0
	ora	#$01
	sta	$2324,y
	lda	$23C4,y
	and	#$F0
	ora	#$01
	sta	$23C4,y
	plp
	rts

CP0_O
	php
	rep	#$20
	lda	$21E2,y
	and	#$F00F
	ora	#$0110
	sta	$21E2,y
	lda	$21E4,y
	and	#$F00F
	ora	#$0110
	sta	$21E4,y
	lda	$2281,y
	and	#$F00F
	ora	#$0110
	sta	$2281,y
	sep	#$20
	lda	$21E1,y
	and	#$F0
	ora	#$01
	sta	$21E1,y
	lda	$2285,y
	and	#$0F
	ora	#$10
	sta	$2285,y
	lda	$2322,y
	and	#$0F
	ora	#$10
	sta	$2322,y
	lda	$2325,y
	and	#$0F
	ora	#$10
	sta	$2325,y
	lda	$23C5,y
	and	#$0F
	ora	#$10
	sta	$23C5,y
	lda	#$11
	sta	$2461,y
	plp
	rts

CP1_E
	php
	rep	#$20
	lda	$2320,y
	and	#$F0F0
	ora	#$0101
	sta	$2320,y
	lda	$23C1,y
	and	#$0F00
	ora	#$1011
	sta	$23C1,y
	sep	#$20
	lda	$21E1,y
	and	#$F0
	ora	#$01
	sta	$21E1,y
	lda	#$11
	sta	$21E3,y
	lda	$21E5,y
	and	#$0F
	ora	#$10
	sta	$21E5,y
	lda	$2281,y
	and	#$F0
	ora	#$01
	sta	$2281,y
	lda	$2284,y
	and	#$F0
	ora	#$01
	sta	$2284,y
	lda	$2324,y
	and	#$F0
	ora	#$01
	sta	$2324,y
	lda	$23C0,y
	and	#$F0
	ora	#$01
	sta	$23C0,y
	lda	$23C4,y
	and	#$F0
	ora	#$01
	sta	$23C4,y
	lda	$2461,y
	and	#$F0
	ora	#$01
	sta	$2461,y
	plp
	rts

CP1_O
	php
	rep	#$20
	lda	$21E2,y
	and	#$F00F
	ora	#$0110
	sta	$21E2,y
	lda	$21E4,y
	and	#$F00F
	ora	#$0110
	sta	$21E4,y
	lda	$2321,y
	and	#$0F0F
	ora	#$1010
	sta	$2321,y
	lda	#$1111
	sta	$23C1,y
	sep	#$20
	lda	$2282,y
	and	#$0F
	ora	#$10
	sta	$2282,y
	lda	$2285,y
	and	#$0F
	ora	#$10
	sta	$2285,y
	lda	$2325,y
	and	#$0F
	ora	#$10
	sta	$2325,y
	lda	$23C5,y
	and	#$0F
	ora	#$10
	sta	$23C5,y
	lda	$2462,y
	and	#$0F
	ora	#$10
	sta	$2462,y
	plp
	rts

CP2_E
	php
	rep	#$20
	sep	#$20
	lda	#$11
	sta	$21E1,y
	lda	#$11
	sta	$21E3,y
	lda	$21E5,y
	and	#$0F
	ora	#$10
	sta	$21E5,y
	lda	$2280,y
	and	#$F0
	ora	#$01
	sta	$2280,y
	lda	$2282,y
	and	#$0F
	ora	#$10
	sta	$2282,y
	lda	$2284,y
	and	#$F0
	ora	#$01
	sta	$2284,y
	lda	#$11
	sta	$2321,y
	lda	$2324,y
	and	#$F0
	ora	#$01
	sta	$2324,y
	lda	$23C0,y
	and	#$F0
	ora	#$01
	sta	$23C0,y
	lda	$23C2,y
	and	#$0F
	ora	#$10
	sta	$23C2,y
	lda	$23C4,y
	and	#$F0
	ora	#$01
	sta	$23C4,y
	plp
	rts

CP2_O
	php
	rep	#$20
	lda	$21E2,y
	and	#$F00F
	ora	#$0110
	sta	$21E2,y
	lda	$21E4,y
	and	#$F00F
	ora	#$0110
	sta	$21E4,y
	lda	$2281,y
	and	#$F00F
	ora	#$0110
	sta	$2281,y
	lda	$2321,y
	and	#$0FF0
	ora	#$1001
	sta	$2321,y
	lda	$23C1,y
	and	#$F00F
	ora	#$0110
	sta	$23C1,y
	sep	#$20
	lda	$21E1,y
	and	#$F0
	ora	#$01
	sta	$21E1,y
	lda	$2285,y
	and	#$0F
	ora	#$10
	sta	$2285,y
	lda	$2325,y
	and	#$0F
	ora	#$10
	sta	$2325,y
	lda	$23C5,y
	and	#$0F
	ora	#$10
	sta	$23C5,y
	plp
	rts

CP3_E
	php
	rep	#$20
	lda	$21E0,y
	and	#$F0F0
	ora	#$0101
	sta	$21E0,y
	lda	$21E2,y
	and	#$F00F
	ora	#$0110
	sta	$21E2,y
	lda	$2285,y
	and	#$0F0F
	ora	#$1010
	sta	$2285,y
	lda	$2320,y
	and	#$F0F0
	ora	#$0101
	sta	$2320,y
	lda	$2322,y
	and	#$0F0F
	ora	#$1010
	sta	$2322,y
	lda	$2325,y
	and	#$0F0F
	ora	#$1010
	sta	$2325,y
	lda	$23C5,y
	and	#$0F0F
	ora	#$1010
	sta	$23C5,y
	sep	#$20
	lda	$21E5,y
	and	#$F0
	ora	#$01
	sta	$21E5,y
	lda	$2280,y
	and	#$F0
	ora	#$01
	sta	$2280,y
	lda	$2283,y
	and	#$0F
	ora	#$10
	sta	$2283,y
	lda	$23C0,y
	and	#$F0
	ora	#$01
	sta	$23C0,y
	lda	$23C3,y
	and	#$0F
	ora	#$10
	sta	$23C3,y
	lda	$2460,y
	and	#$F0
	ora	#$01
	sta	$2460,y
	plp
	rts

CP3_O
	php
	rep	#$20
	lda	$21E1,y
	and	#$000F
	ora	#$1110
	sta	$21E1,y
	lda	$2285,y
	and	#$F0F0
	ora	#$0101
	sta	$2285,y
	lda	$2322,y
	and	#$F000
	ora	#$0111
	sta	$2322,y
	lda	$2325,y
	and	#$F0F0
	ora	#$0101
	sta	$2325,y
	lda	$23C5,y
	and	#$F0F0
	ora	#$0101
	sta	$23C5,y
	sep	#$20
	lda	$21E4,y
	and	#$0F
	ora	#$10
	sta	$21E4,y
	lda	$21E6,y
	and	#$0F
	ora	#$10
	sta	$21E6,y
	lda	$2281,y
	and	#$0F
	ora	#$10
	sta	$2281,y
	lda	$2283,y
	and	#$F0
	ora	#$01
	sta	$2283,y
	lda	$2321,y
	and	#$0F
	ora	#$10
	sta	$2321,y
	lda	$23C1,y
	and	#$0F
	ora	#$10
	sta	$23C1,y
	lda	$23C3,y
	and	#$F0
	ora	#$01
	sta	$23C3,y
	lda	$2461,y
	and	#$0F
	ora	#$10
	sta	$2461,y
	plp
	rts

	mx	%00

