*
* Generated by py/gen_compiled_points.py - do not edit by hand
* Ghost $28-$2B: (ACT_SPR&3)*2 + (X&1) -> slots 0-3
* Fruit $08-$0F: (4+(ACT_SPR&7))*2 + (X&1) -> slots 4-11
* Opaque ink forced to SHR pen 1 (white).
*

PointsBlitGo
* X = index*2 into PointsBlitTable; JMP so blit RTS returns to caller.
	jmp	(PointsBlitTable,x)

PointsBlitTable
	da	CP0_E	; Pts200 spr=$28 white even
	da	CP0_O	; Pts200 spr=$28 white odd
	da	CP1_E	; Pts400 spr=$29 white even
	da	CP1_O	; Pts400 spr=$29 white odd
	da	CP2_E	; Pts800 spr=$2A white even
	da	CP2_O	; Pts800 spr=$2A white odd
	da	CP3_E	; Pts1600 spr=$2B white even
	da	CP3_O	; Pts1600 spr=$2B white odd
	da	CP4_E	; Pts100 spr=$08 white even
	da	CP4_O	; Pts100 spr=$08 white odd
	da	CP5_E	; Pts200f spr=$09 white even
	da	CP5_O	; Pts200f spr=$09 white odd
	da	CP6_E	; Pts500 spr=$0A white even
	da	CP6_O	; Pts500 spr=$0A white odd
	da	CP7_E	; Pts700 spr=$0B white even
	da	CP7_O	; Pts700 spr=$0B white odd
	da	CP8_E	; Pts1000 spr=$0C white even
	da	CP8_O	; Pts1000 spr=$0C white odd
	da	CP9_E	; Pts2000 spr=$0D white even
	da	CP9_O	; Pts2000 spr=$0D white odd
	da	CP10_E	; Pts5000 spr=$0E white even
	da	CP10_O	; Pts5000 spr=$0E white odd
	da	CP11_E	; Pts5000J spr=$0F white even
	da	CP11_O	; Pts5000J spr=$0F white odd

CP0_E
	php
	rep	#$20
	lda	$2283,y
	and	#$0F0F
	ora	#$1010
	sta	$2283,y
	lda	$2285,y
	and	#$0F0F
	ora	#$1010
	sta	$2285,y
	lda	$2323,y
	and	#$0F0F
	ora	#$1010
	sta	$2323,y
	lda	$2325,y
	and	#$0F0F
	ora	#$1010
	sta	$2325,y
	lda	$23C3,y
	and	#$0F0F
	ora	#$1010
	sta	$23C3,y
	lda	$23C5,y
	and	#$0F0F
	ora	#$1010
	sta	$23C5,y
	lda	$2460,y
	and	#$00F0
	ora	#$1101
	sta	$2460,y
	lda	$2462,y
	and	#$F00F
	ora	#$0110
	sta	$2462,y
	sep	#$20
	lda	#$11
	sta	$21E1,y
	lda	$21E3,y
	and	#$F0
	ora	#$01
	sta	$21E3,y
	lda	$21E5,y
	and	#$F0
	ora	#$01
	sta	$21E5,y
	lda	$2280,y
	and	#$F0
	ora	#$01
	sta	$2280,y
	lda	$2282,y
	and	#$0F
	ora	#$10
	sta	$2282,y
	lda	$2321,y
	and	#$F0
	ora	#$01
	sta	$2321,y
	lda	$23C1,y
	and	#$0F
	ora	#$10
	sta	$23C1,y
	lda	$2465,y
	and	#$F0
	ora	#$01
	sta	$2465,y
	plp
	rts

CP0_O
	php
	rep	#$20
	lda	$21E1,y
	and	#$0FF0
	ora	#$1001
	sta	$21E1,y
	lda	$2281,y
	and	#$F00F
	ora	#$0110
	sta	$2281,y
	lda	$2283,y
	and	#$F0F0
	ora	#$0101
	sta	$2283,y
	lda	$2285,y
	and	#$F0F0
	ora	#$0101
	sta	$2285,y
	lda	$2323,y
	and	#$F0F0
	ora	#$0101
	sta	$2323,y
	lda	$2325,y
	and	#$F0F0
	ora	#$0101
	sta	$2325,y
	lda	$23C3,y
	and	#$F0F0
	ora	#$0101
	sta	$23C3,y
	lda	$23C5,y
	and	#$F0F0
	ora	#$0101
	sta	$23C5,y
	lda	#$1111
	sta	$2461,y
	sep	#$20
	lda	$21E4,y
	and	#$0F
	ora	#$10
	sta	$21E4,y
	lda	$21E6,y
	and	#$0F
	ora	#$10
	sta	$21E6,y
	lda	$2322,y
	and	#$0F
	ora	#$10
	sta	$2322,y
	lda	$23C1,y
	and	#$F0
	ora	#$01
	sta	$23C1,y
	lda	$2464,y
	and	#$0F
	ora	#$10
	sta	$2464,y
	lda	$2466,y
	and	#$0F
	ora	#$10
	sta	$2466,y
	plp
	rts

CP1_E
	php
	rep	#$20
	lda	$21E2,y
	and	#$F00F
	ora	#$0110
	sta	$21E2,y
	lda	$2283,y
	and	#$0F0F
	ora	#$1010
	sta	$2283,y
	lda	$2285,y
	and	#$0F0F
	ora	#$1010
	sta	$2285,y
	lda	$2321,y
	and	#$0F00
	ora	#$1011
	sta	$2321,y
	lda	$2323,y
	and	#$0F0F
	ora	#$1010
	sta	$2323,y
	lda	$2325,y
	and	#$0F0F
	ora	#$1010
	sta	$2325,y
	lda	$23C3,y
	and	#$0F0F
	ora	#$1010
	sta	$23C3,y
	lda	$23C5,y
	and	#$0F0F
	ora	#$1010
	sta	$23C5,y
	lda	$2462,y
	and	#$F00F
	ora	#$0110
	sta	$2462,y
	sep	#$20
	lda	$21E0,y
	and	#$F0
	ora	#$01
	sta	$21E0,y
	lda	$21E5,y
	and	#$F0
	ora	#$01
	sta	$21E5,y
	lda	$2280,y
	and	#$F0
	ora	#$01
	sta	$2280,y
	lda	$2282,y
	and	#$0F
	ora	#$10
	sta	$2282,y
	lda	$2320,y
	and	#$F0
	ora	#$01
	sta	$2320,y
	lda	$23C2,y
	and	#$0F
	ora	#$10
	sta	$23C2,y
	lda	$2465,y
	and	#$F0
	ora	#$01
	sta	$2465,y
	plp
	rts

CP1_O
	php
	rep	#$20
	lda	$21E1,y
	and	#$F00F
	ora	#$0110
	sta	$21E1,y
	lda	$2281,y
	and	#$F00F
	ora	#$0110
	sta	$2281,y
	lda	$2283,y
	and	#$F0F0
	ora	#$0101
	sta	$2283,y
	lda	$2285,y
	and	#$F0F0
	ora	#$0101
	sta	$2285,y
	lda	#$1111
	sta	$2321,y
	lda	$2323,y
	and	#$F0F0
	ora	#$0101
	sta	$2323,y
	lda	$2325,y
	and	#$F0F0
	ora	#$0101
	sta	$2325,y
	lda	$23C3,y
	and	#$F0F0
	ora	#$0101
	sta	$23C3,y
	lda	$23C5,y
	and	#$F0F0
	ora	#$0101
	sta	$23C5,y
	sep	#$20
	lda	$21E4,y
	and	#$0F
	ora	#$10
	sta	$21E4,y
	lda	$21E6,y
	and	#$0F
	ora	#$10
	sta	$21E6,y
	lda	$23C2,y
	and	#$F0
	ora	#$01
	sta	$23C2,y
	lda	$2462,y
	and	#$F0
	ora	#$01
	sta	$2462,y
	lda	$2464,y
	and	#$0F
	ora	#$10
	sta	$2464,y
	lda	$2466,y
	and	#$0F
	ora	#$10
	sta	$2466,y
	plp
	rts

CP2_E
	php
	rep	#$20
	lda	$2283,y
	and	#$0F0F
	ora	#$1010
	sta	$2283,y
	lda	$2285,y
	and	#$0F0F
	ora	#$1010
	sta	$2285,y
	lda	$2323,y
	and	#$0F0F
	ora	#$1010
	sta	$2323,y
	lda	$2325,y
	and	#$0F0F
	ora	#$1010
	sta	$2325,y
	lda	$23C3,y
	and	#$0F0F
	ora	#$1010
	sta	$23C3,y
	lda	$23C5,y
	and	#$0F0F
	ora	#$1010
	sta	$23C5,y
	sep	#$20
	lda	#$11
	sta	$21E1,y
	lda	$21E3,y
	and	#$F0
	ora	#$01
	sta	$21E3,y
	lda	$21E5,y
	and	#$F0
	ora	#$01
	sta	$21E5,y
	lda	$2280,y
	and	#$F0
	ora	#$01
	sta	$2280,y
	lda	$2282,y
	and	#$0F
	ora	#$10
	sta	$2282,y
	lda	#$11
	sta	$2321,y
	lda	$23C0,y
	and	#$F0
	ora	#$01
	sta	$23C0,y
	lda	$23C2,y
	and	#$0F
	ora	#$10
	sta	$23C2,y
	lda	#$11
	sta	$2461,y
	lda	$2463,y
	and	#$F0
	ora	#$01
	sta	$2463,y
	lda	$2465,y
	and	#$F0
	ora	#$01
	sta	$2465,y
	plp
	rts

CP2_O
	php
	rep	#$20
	lda	$21E1,y
	and	#$0FF0
	ora	#$1001
	sta	$21E1,y
	lda	$2281,y
	and	#$F00F
	ora	#$0110
	sta	$2281,y
	lda	$2283,y
	and	#$F0F0
	ora	#$0101
	sta	$2283,y
	lda	$2285,y
	and	#$F0F0
	ora	#$0101
	sta	$2285,y
	lda	$2321,y
	and	#$0FF0
	ora	#$1001
	sta	$2321,y
	lda	$2323,y
	and	#$F0F0
	ora	#$0101
	sta	$2323,y
	lda	$2325,y
	and	#$F0F0
	ora	#$0101
	sta	$2325,y
	lda	$23C1,y
	and	#$F00F
	ora	#$0110
	sta	$23C1,y
	lda	$23C3,y
	and	#$F0F0
	ora	#$0101
	sta	$23C3,y
	lda	$23C5,y
	and	#$F0F0
	ora	#$0101
	sta	$23C5,y
	lda	$2461,y
	and	#$0FF0
	ora	#$1001
	sta	$2461,y
	sep	#$20
	lda	$21E4,y
	and	#$0F
	ora	#$10
	sta	$21E4,y
	lda	$21E6,y
	and	#$0F
	ora	#$10
	sta	$21E6,y
	lda	$2464,y
	and	#$0F
	ora	#$10
	sta	$2464,y
	lda	$2466,y
	and	#$0F
	ora	#$10
	sta	$2466,y
	plp
	rts

CP3_E
	php
	rep	#$20
	lda	$21E2,y
	and	#$0F00
	ora	#$1011
	sta	$21E2,y
	lda	$21E4,y
	and	#$F0F0
	ora	#$0101
	sta	$21E4,y
	lda	$2280,y
	and	#$F0F0
	ora	#$0101
	sta	$2280,y
	lda	$2285,y
	and	#$0F0F
	ora	#$1010
	sta	$2285,y
	lda	$2320,y
	and	#$F0F0
	ora	#$0101
	sta	$2320,y
	lda	$2323,y
	and	#$0F0F
	ora	#$1010
	sta	$2323,y
	lda	$2325,y
	and	#$0F0F
	ora	#$1010
	sta	$2325,y
	lda	$23C0,y
	and	#$F0F0
	ora	#$0101
	sta	$23C0,y
	lda	$23C3,y
	and	#$0F0F
	ora	#$1010
	sta	$23C3,y
	lda	$23C5,y
	and	#$0F0F
	ora	#$1010
	sta	$23C5,y
	lda	$2464,y
	and	#$F0F0
	ora	#$0101
	sta	$2464,y
	sep	#$20
	lda	$21E0,y
	and	#$F0
	ora	#$01
	sta	$21E0,y
	lda	$2284,y
	and	#$0F
	ora	#$10
	sta	$2284,y
	lda	#$11
	sta	$2322,y
	lda	$2460,y
	and	#$F0
	ora	#$01
	sta	$2460,y
	lda	#$11
	sta	$2462,y
	plp
	rts

CP3_O
	php
	rep	#$20
	lda	$21E1,y
	and	#$F00F
	ora	#$0110
	sta	$21E1,y
	lda	$21E5,y
	and	#$0F0F
	ora	#$1010
	sta	$21E5,y
	lda	$2281,y
	and	#$0F0F
	ora	#$1010
	sta	$2281,y
	lda	$2285,y
	and	#$F0F0
	ora	#$0101
	sta	$2285,y
	lda	$2321,y
	and	#$000F
	ora	#$1110
	sta	$2321,y
	lda	$2323,y
	and	#$F000
	ora	#$0111
	sta	$2323,y
	lda	$2325,y
	and	#$F0F0
	ora	#$0101
	sta	$2325,y
	lda	$23C1,y
	and	#$0F0F
	ora	#$1010
	sta	$23C1,y
	lda	$23C3,y
	and	#$F0F0
	ora	#$0101
	sta	$23C3,y
	lda	$23C5,y
	and	#$F0F0
	ora	#$0101
	sta	$23C5,y
	lda	$2462,y
	and	#$0FF0
	ora	#$1001
	sta	$2462,y
	lda	$2465,y
	and	#$0F0F
	ora	#$1010
	sta	$2465,y
	sep	#$20
	lda	#$11
	sta	$21E3,y
	lda	$2284,y
	and	#$F0
	ora	#$01
	sta	$2284,y
	lda	$2461,y
	and	#$0F
	ora	#$10
	sta	$2461,y
	plp
	rts

CP4_E
	php
	rep	#$20
	lda	$2283,y
	and	#$0F00
	ora	#$1011
	sta	$2283,y
	lda	$2323,y
	and	#$0F0F
	ora	#$1010
	sta	$2323,y
	lda	$23C4,y
	and	#$0F00
	ora	#$1011
	sta	$23C4,y
	lda	$2464,y
	and	#$0F0F
	ora	#$1010
	sta	$2464,y
	lda	$2504,y
	and	#$0F0F
	ora	#$1010
	sta	$2504,y
	lda	$25A4,y
	and	#$0F00
	ora	#$1011
	sta	$25A4,y
	sep	#$20
	lda	$2142,y
	and	#$0F
	ora	#$10
	sta	$2142,y
	lda	$21E2,y
	and	#$0F
	ora	#$10
	sta	$21E2,y
	lda	$2282,y
	and	#$0F
	ora	#$10
	sta	$2282,y
	lda	$2322,y
	and	#$0F
	ora	#$10
	sta	$2322,y
	lda	$23C3,y
	and	#$0F
	ora	#$10
	sta	$23C3,y
	lda	#$11
	sta	$2463,y
	plp
	rts

CP4_O
	php
	rep	#$20
	lda	$2282,y
	and	#$F0F0
	ora	#$0101
	sta	$2282,y
	lda	$2323,y
	and	#$F0F0
	ora	#$0101
	sta	$2323,y
	lda	$23C3,y
	and	#$F0F0
	ora	#$0101
	sta	$23C3,y
	lda	$2464,y
	and	#$F000
	ora	#$0111
	sta	$2464,y
	lda	$2504,y
	and	#$F0F0
	ora	#$0101
	sta	$2504,y
	lda	$25A4,y
	and	#$00F0
	ora	#$1101
	sta	$25A4,y
	sep	#$20
	lda	$2142,y
	and	#$F0
	ora	#$01
	sta	$2142,y
	lda	$21E2,y
	and	#$F0
	ora	#$01
	sta	$21E2,y
	lda	#$11
	sta	$2284,y
	lda	$2322,y
	and	#$F0
	ora	#$01
	sta	$2322,y
	lda	#$11
	sta	$23C5,y
	lda	$2463,y
	and	#$F0
	ora	#$01
	sta	$2463,y
	plp
	rts

CP5_E
	php
	rep	#$20
	lda	$2141,y
	and	#$0FF0
	ora	#$1001
	sta	$2141,y
	lda	$2283,y
	and	#$0F00
	ora	#$1011
	sta	$2283,y
	lda	$2321,y
	and	#$0FF0
	ora	#$1001
	sta	$2321,y
	lda	$2323,y
	and	#$0F0F
	ora	#$1010
	sta	$2323,y
	lda	$23C4,y
	and	#$0F00
	ora	#$1011
	sta	$23C4,y
	lda	$2464,y
	and	#$0F0F
	ora	#$1010
	sta	$2464,y
	lda	$2504,y
	and	#$0F0F
	ora	#$1010
	sta	$2504,y
	lda	$25A4,y
	and	#$0F00
	ora	#$1011
	sta	$25A4,y
	sep	#$20
	lda	$21E2,y
	and	#$0F
	ora	#$10
	sta	$21E2,y
	lda	$2281,y
	and	#$F0
	ora	#$01
	sta	$2281,y
	lda	$23C3,y
	and	#$0F
	ora	#$10
	sta	$23C3,y
	lda	#$11
	sta	$2463,y
	plp
	rts

CP5_O
	php
	rep	#$20
	lda	$2282,y
	and	#$F00F
	ora	#$0110
	sta	$2282,y
	lda	$2323,y
	and	#$F0F0
	ora	#$0101
	sta	$2323,y
	lda	$23C3,y
	and	#$F0F0
	ora	#$0101
	sta	$23C3,y
	lda	$2464,y
	and	#$F000
	ora	#$0111
	sta	$2464,y
	lda	$2504,y
	and	#$F0F0
	ora	#$0101
	sta	$2504,y
	lda	$25A4,y
	and	#$00F0
	ora	#$1101
	sta	$25A4,y
	sep	#$20
	lda	#$11
	sta	$2142,y
	lda	$21E2,y
	and	#$F0
	ora	#$01
	sta	$21E2,y
	lda	#$11
	sta	$2284,y
	lda	#$11
	sta	$2322,y
	lda	#$11
	sta	$23C5,y
	lda	$2463,y
	and	#$F0
	ora	#$01
	sta	$2463,y
	plp
	rts

CP6_E
	php
	rep	#$20
	lda	$2141,y
	and	#$0FF0
	ora	#$1001
	sta	$2141,y
	lda	$2283,y
	and	#$0F00
	ora	#$1011
	sta	$2283,y
	lda	$2321,y
	and	#$0FF0
	ora	#$1001
	sta	$2321,y
	lda	$2323,y
	and	#$0F0F
	ora	#$1010
	sta	$2323,y
	lda	$23C4,y
	and	#$0F00
	ora	#$1011
	sta	$23C4,y
	lda	$2464,y
	and	#$0F0F
	ora	#$1010
	sta	$2464,y
	lda	$2504,y
	and	#$0F0F
	ora	#$1010
	sta	$2504,y
	lda	$25A4,y
	and	#$0F00
	ora	#$1011
	sta	$25A4,y
	sep	#$20
	lda	$21E1,y
	and	#$F0
	ora	#$01
	sta	$21E1,y
	lda	$2282,y
	and	#$0F
	ora	#$10
	sta	$2282,y
	lda	$23C3,y
	and	#$0F
	ora	#$10
	sta	$23C3,y
	lda	#$11
	sta	$2463,y
	plp
	rts

CP6_O
	php
	rep	#$20
	lda	$2282,y
	and	#$F0F0
	ora	#$0101
	sta	$2282,y
	lda	$2323,y
	and	#$F0F0
	ora	#$0101
	sta	$2323,y
	lda	$23C3,y
	and	#$F0F0
	ora	#$0101
	sta	$23C3,y
	lda	$2464,y
	and	#$F000
	ora	#$0111
	sta	$2464,y
	lda	$2504,y
	and	#$F0F0
	ora	#$0101
	sta	$2504,y
	lda	$25A4,y
	and	#$00F0
	ora	#$1101
	sta	$25A4,y
	sep	#$20
	lda	#$11
	sta	$2142,y
	lda	$21E2,y
	and	#$0F
	ora	#$10
	sta	$21E2,y
	lda	#$11
	sta	$2284,y
	lda	#$11
	sta	$2322,y
	lda	#$11
	sta	$23C5,y
	lda	$2463,y
	and	#$F0
	ora	#$01
	sta	$2463,y
	plp
	rts

CP7_E
	php
	rep	#$20
	lda	$2141,y
	and	#$0F00
	ora	#$1011
	sta	$2141,y
	lda	$2283,y
	and	#$0F00
	ora	#$1011
	sta	$2283,y
	lda	$2323,y
	and	#$0F0F
	ora	#$1010
	sta	$2323,y
	lda	$23C4,y
	and	#$0F00
	ora	#$1011
	sta	$23C4,y
	lda	$2464,y
	and	#$0F0F
	ora	#$1010
	sta	$2464,y
	lda	$2504,y
	and	#$0F0F
	ora	#$1010
	sta	$2504,y
	lda	$25A4,y
	and	#$0F00
	ora	#$1011
	sta	$25A4,y
	sep	#$20
	lda	$21E2,y
	and	#$0F
	ora	#$10
	sta	$21E2,y
	lda	$2282,y
	and	#$0F
	ora	#$10
	sta	$2282,y
	lda	$2322,y
	and	#$0F
	ora	#$10
	sta	$2322,y
	lda	$23C3,y
	and	#$0F
	ora	#$10
	sta	$23C3,y
	lda	#$11
	sta	$2463,y
	plp
	rts

CP7_O
	php
	rep	#$20
	lda	$2141,y
	and	#$00F0
	ora	#$1101
	sta	$2141,y
	lda	$2282,y
	and	#$F0F0
	ora	#$0101
	sta	$2282,y
	lda	$2323,y
	and	#$F0F0
	ora	#$0101
	sta	$2323,y
	lda	$23C3,y
	and	#$F0F0
	ora	#$0101
	sta	$23C3,y
	lda	$2464,y
	and	#$F000
	ora	#$0111
	sta	$2464,y
	lda	$2504,y
	and	#$F0F0
	ora	#$0101
	sta	$2504,y
	lda	$25A4,y
	and	#$00F0
	ora	#$1101
	sta	$25A4,y
	sep	#$20
	lda	$21E2,y
	and	#$F0
	ora	#$01
	sta	$21E2,y
	lda	#$11
	sta	$2284,y
	lda	$2322,y
	and	#$F0
	ora	#$01
	sta	$2322,y
	lda	#$11
	sta	$23C5,y
	lda	$2463,y
	and	#$F0
	ora	#$01
	sta	$2463,y
	plp
	rts

CP8_E
	php
	rep	#$20
	lda	$21E2,y
	and	#$0F00
	ora	#$1011
	sta	$21E2,y
	lda	$2282,y
	and	#$0F0F
	ora	#$1010
	sta	$2282,y
	lda	#$1111
	sta	$2323,y
	lda	#$1111
	sta	$23C2,y
	lda	$2463,y
	and	#$F0F0
	ora	#$0101
	sta	$2463,y
	lda	$2465,y
	and	#$0F00
	ora	#$1011
	sta	$2465,y
	lda	$2503,y
	and	#$00F0
	ora	#$1101
	sta	$2503,y
	lda	$2505,y
	and	#$0F0F
	ora	#$1010
	sta	$2505,y
	lda	$25A5,y
	and	#$0F0F
	ora	#$1010
	sta	$25A5,y
	lda	$2645,y
	and	#$0F00
	ora	#$1011
	sta	$2645,y
	sep	#$20
	lda	$20A1,y
	and	#$0F
	ora	#$10
	sta	$20A1,y
	lda	$2141,y
	and	#$0F
	ora	#$10
	sta	$2141,y
	lda	$21E1,y
	and	#$0F
	ora	#$10
	sta	$21E1,y
	lda	$2281,y
	and	#$0F
	ora	#$10
	sta	$2281,y
	lda	$2322,y
	and	#$0F
	ora	#$10
	sta	$2322,y
	lda	$23C4,y
	and	#$F0
	ora	#$01
	sta	$23C4,y
	plp
	rts

CP8_O
	php
	rep	#$20
	lda	$21E1,y
	and	#$F0F0
	ora	#$0101
	sta	$21E1,y
	lda	$2282,y
	and	#$F0F0
	ora	#$0101
	sta	$2282,y
	lda	$2322,y
	and	#$F0F0
	ora	#$0101
	sta	$2322,y
	lda	$2324,y
	and	#$0F00
	ora	#$1011
	sta	$2324,y
	lda	$23C2,y
	and	#$00F0
	ora	#$1101
	sta	$23C2,y
	lda	$23C4,y
	and	#$0F0F
	ora	#$1010
	sta	$23C4,y
	lda	#$1111
	sta	$2465,y
	lda	#$1111
	sta	$2504,y
	lda	$25A5,y
	and	#$F0F0
	ora	#$0101
	sta	$25A5,y
	lda	$2645,y
	and	#$00F0
	ora	#$1101
	sta	$2645,y
	sep	#$20
	lda	$20A1,y
	and	#$F0
	ora	#$01
	sta	$20A1,y
	lda	$2141,y
	and	#$F0
	ora	#$01
	sta	$2141,y
	lda	#$11
	sta	$21E3,y
	lda	$2281,y
	and	#$F0
	ora	#$01
	sta	$2281,y
	lda	$2464,y
	and	#$0F
	ora	#$10
	sta	$2464,y
	lda	$2506,y
	and	#$F0
	ora	#$01
	sta	$2506,y
	plp
	rts

CP9_E
	php
	rep	#$20
	lda	$20A0,y
	and	#$0FF0
	ora	#$1001
	sta	$20A0,y
	lda	$21E2,y
	and	#$0F00
	ora	#$1011
	sta	$21E2,y
	lda	$2280,y
	and	#$0FF0
	ora	#$1001
	sta	$2280,y
	lda	$2282,y
	and	#$0F0F
	ora	#$1010
	sta	$2282,y
	lda	#$1111
	sta	$2323,y
	lda	#$1111
	sta	$23C2,y
	lda	$2463,y
	and	#$F0F0
	ora	#$0101
	sta	$2463,y
	lda	$2465,y
	and	#$0F00
	ora	#$1011
	sta	$2465,y
	lda	$2503,y
	and	#$00F0
	ora	#$1101
	sta	$2503,y
	lda	$2505,y
	and	#$0F0F
	ora	#$1010
	sta	$2505,y
	lda	$25A5,y
	and	#$0F0F
	ora	#$1010
	sta	$25A5,y
	lda	$2645,y
	and	#$0F00
	ora	#$1011
	sta	$2645,y
	sep	#$20
	lda	$2141,y
	and	#$0F
	ora	#$10
	sta	$2141,y
	lda	$21E0,y
	and	#$F0
	ora	#$01
	sta	$21E0,y
	lda	$2322,y
	and	#$0F
	ora	#$10
	sta	$2322,y
	lda	$23C4,y
	and	#$F0
	ora	#$01
	sta	$23C4,y
	plp
	rts

CP9_O
	php
	rep	#$20
	lda	$21E1,y
	and	#$F00F
	ora	#$0110
	sta	$21E1,y
	lda	$2282,y
	and	#$F0F0
	ora	#$0101
	sta	$2282,y
	lda	$2322,y
	and	#$F0F0
	ora	#$0101
	sta	$2322,y
	lda	$2324,y
	and	#$0F00
	ora	#$1011
	sta	$2324,y
	lda	$23C2,y
	and	#$00F0
	ora	#$1101
	sta	$23C2,y
	lda	$23C4,y
	and	#$0F0F
	ora	#$1010
	sta	$23C4,y
	lda	#$1111
	sta	$2465,y
	lda	#$1111
	sta	$2504,y
	lda	$25A5,y
	and	#$F0F0
	ora	#$0101
	sta	$25A5,y
	lda	$2645,y
	and	#$00F0
	ora	#$1101
	sta	$2645,y
	sep	#$20
	lda	#$11
	sta	$20A1,y
	lda	$2141,y
	and	#$F0
	ora	#$01
	sta	$2141,y
	lda	#$11
	sta	$21E3,y
	lda	#$11
	sta	$2281,y
	lda	$2464,y
	and	#$0F
	ora	#$10
	sta	$2464,y
	lda	$2506,y
	and	#$F0
	ora	#$01
	sta	$2506,y
	plp
	rts

CP10_E
	php
	rep	#$20
	lda	$21E1,y
	and	#$F0F0
	ora	#$0101
	sta	$21E1,y
	lda	$2282,y
	and	#$F0F0
	ora	#$0101
	sta	$2282,y
	lda	$2322,y
	and	#$F0F0
	ora	#$0101
	sta	$2322,y
	lda	$23C3,y
	and	#$F000
	ora	#$0111
	sta	$23C3,y
	lda	$2463,y
	and	#$F0F0
	ora	#$0101
	sta	$2463,y
	lda	$2504,y
	and	#$F000
	ora	#$0111
	sta	$2504,y
	lda	$25A4,y
	and	#$F0F0
	ora	#$0101
	sta	$25A4,y
	lda	$2644,y
	and	#$00F0
	ora	#$1101
	sta	$2644,y
	sep	#$20
	lda	#$11
	sta	$20A1,y
	lda	$2141,y
	and	#$0F
	ora	#$10
	sta	$2141,y
	lda	#$11
	sta	$21E3,y
	lda	#$11
	sta	$2281,y
	lda	#$11
	sta	$2324,y
	lda	$23C2,y
	and	#$F0
	ora	#$01
	sta	$23C2,y
	lda	#$11
	sta	$2465,y
	lda	$2503,y
	and	#$F0
	ora	#$01
	sta	$2503,y
	plp
	rts

CP10_O
	php
	rep	#$20
	lda	$20A1,y
	and	#$0FF0
	ora	#$1001
	sta	$20A1,y
	lda	$21E3,y
	and	#$0F00
	ora	#$1011
	sta	$21E3,y
	lda	$2281,y
	and	#$0FF0
	ora	#$1001
	sta	$2281,y
	lda	$2283,y
	and	#$0F0F
	ora	#$1010
	sta	$2283,y
	lda	$2324,y
	and	#$0F00
	ora	#$1011
	sta	$2324,y
	lda	$23C4,y
	and	#$0F0F
	ora	#$1010
	sta	$23C4,y
	lda	$2465,y
	and	#$0F00
	ora	#$1011
	sta	$2465,y
	lda	$2505,y
	and	#$0F0F
	ora	#$1010
	sta	$2505,y
	lda	$25A5,y
	and	#$0F0F
	ora	#$1010
	sta	$25A5,y
	lda	$2645,y
	and	#$0F00
	ora	#$1011
	sta	$2645,y
	sep	#$20
	lda	$2141,y
	and	#$F0
	ora	#$01
	sta	$2141,y
	lda	$21E2,y
	and	#$0F
	ora	#$10
	sta	$21E2,y
	lda	$2323,y
	and	#$0F
	ora	#$10
	sta	$2323,y
	lda	#$11
	sta	$23C3,y
	lda	$2464,y
	and	#$0F
	ora	#$10
	sta	$2464,y
	lda	#$11
	sta	$2504,y
	plp
	rts

CP11_E
	php
	rep	#$20
	lda	$23C3,y
	and	#$0F00
	ora	#$1011
	sta	$23C3,y
	lda	#$1111
	sta	$2463,y
	lda	$2503,y
	and	#$00F0
	ora	#$1101
	sta	$2503,y
	lda	#$1111
	sta	$25A3,y
	lda	$2643,y
	and	#$0F00
	ora	#$1011
	sta	$2643,y
	sep	#$20
	lda	$2462,y
	and	#$F0
	ora	#$01
	sta	$2462,y
	lda	$25A2,y
	and	#$F0
	ora	#$01
	sta	$25A2,y
	plp
	rts

CP11_O
	php
	rep	#$20
	lda	$23C3,y
	and	#$00F0
	ora	#$1101
	sta	$23C3,y
	lda	#$1111
	sta	$2463,y
	lda	$2504,y
	and	#$0F00
	ora	#$1011
	sta	$2504,y
	lda	#$1111
	sta	$25A3,y
	lda	$2643,y
	and	#$00F0
	ora	#$1101
	sta	$2643,y
	sep	#$20
	lda	$2465,y
	and	#$0F
	ora	#$10
	sta	$2465,y
	lda	$25A5,y
	and	#$0F
	ora	#$10
	sta	$25A5,y
	plp
	rts

	mx	%00

