*
* Generated by py/gen_compiled_fruits.py - do not edit by hand
* FruitBlitTable: (ACT_SPR&7)*2 + (X&1) -> abs addresses
* Each blit: Y = SHR offset, DBR = $01, returns via RTS
*

FruitBlitGo
* X = index*2 into FruitBlitTable; JMP so blit RTS returns to caller.
	jmp	(FruitBlitTable,x)

FruitBlitTable
	da	CF0_E	; Cherry spr=$00 bank=#14 even
	da	CF0_O	; Cherry spr=$00 bank=#14 odd
	da	CF1_E	; Strawberry spr=$01 bank=#0F even
	da	CF1_O	; Strawberry spr=$01 bank=#0F odd
	da	CF2_E	; Orange spr=$02 bank=#15 even
	da	CF2_O	; Orange spr=$02 bank=#15 odd
	da	CF3_E	; Pretzel spr=$03 bank=#07 even
	da	CF3_O	; Pretzel spr=$03 bank=#07 odd
	da	CF4_E	; Apple spr=$04 bank=#14 even
	da	CF4_O	; Apple spr=$04 bank=#14 odd
	da	CF5_E	; Pear spr=$05 bank=#15 even
	da	CF5_O	; Pear spr=$05 bank=#15 odd
	da	CF6_E	; Banana spr=$06 bank=#16 even
	da	CF6_O	; Banana spr=$06 bank=#16 odd
	da	CF7_E	; Junior spr=$07 bank=#09 even
	da	CF7_O	; Junior spr=$07 bank=#09 odd

CF0_E
	php
	rep	#$20
	lda	$2144,y
	and	#$0FF0
	ora	#$6006
	sta	$2144,y
	lda	$21E3,y
	and	#$F0F0
	ora	#$0606
	sta	$21E3,y
	lda	$2322,y
	and	#$0F00
	ora	#$3033
	sta	$2322,y
	lda	$23C1,y
	and	#$00F0
	ora	#$3303
	sta	$23C1,y
	lda	$23C3,y
	and	#$00F0
	ora	#$3303
	sta	$23C3,y
	lda	$2461,y
	and	#$0FF0
	ora	#$3003
	sta	$2461,y
	lda	#$3333
	sta	$2463,y
	lda	$2501,y
	and	#$0FF0
	ora	#$3003
	sta	$2501,y
	lda	#$3331
	sta	$2503,y
	lda	#$3333
	sta	$25A3,y
	sep	#$20
	lda	$2321,y
	and	#$F0
	ora	#$03
	sta	$2321,y
	lda	$2465,y
	and	#$0F
	ora	#$30
	sta	$2465,y
	lda	$2505,y
	and	#$0F
	ora	#$30
	sta	$2505,y
	lda	$25A5,y
	and	#$0F
	ora	#$30
	sta	$25A5,y
	plp
	rts

CF0_O
	php
	rep	#$20
	lda	$21E4,y
	and	#$0F0F
	ora	#$6060
	sta	$21E4,y
	lda	#$3333
	sta	$2322,y
	lda	$23C2,y
	and	#$0F00
	ora	#$3033
	sta	$23C2,y
	lda	$23C4,y
	and	#$0F00
	ora	#$3033
	sta	$23C4,y
	lda	$2462,y
	and	#$F000
	ora	#$0333
	sta	$2462,y
	lda	#$3333
	sta	$2464,y
	lda	$2502,y
	and	#$F000
	ora	#$0333
	sta	$2502,y
	lda	#$3313
	sta	$2504,y
	lda	#$3333
	sta	$25A4,y
	sep	#$20
	lda	#$66
	sta	$2145,y
	lda	$25A3,y
	and	#$F0
	ora	#$03
	sta	$25A3,y
	plp
	rts

CF1_E
	php
	rep	#$20
	lda	#$1444
	sta	$2142,y
	lda	$21E1,y
	and	#$00F0
	ora	#$3403
	sta	$21E1,y
	lda	#$3344
	sta	$21E3,y
	lda	#$3333
	sta	$2282,y
	lda	$2284,y
	and	#$0F00
	ora	#$3033
	sta	$2284,y
	lda	#$1333
	sta	$2322,y
	lda	$2324,y
	and	#$0F00
	ora	#$3033
	sta	$2324,y
	lda	#$3333
	sta	$23C2,y
	lda	$23C4,y
	and	#$0F00
	ora	#$3033
	sta	$23C4,y
	lda	$2461,y
	and	#$00F0
	ora	#$3303
	sta	$2461,y
	lda	#$3333
	sta	$2463,y
	lda	#$3333
	sta	$2502,y
	lda	$25A2,y
	and	#$00F0
	ora	#$3303
	sta	$25A2,y
	sep	#$20
	lda	$2144,y
	and	#$0F
	ora	#$40
	sta	$2144,y
	lda	$2281,y
	and	#$F0
	ora	#$03
	sta	$2281,y
	lda	$2321,y
	and	#$F0
	ora	#$03
	sta	$2321,y
	lda	$23C1,y
	and	#$F0
	ora	#$03
	sta	$23C1,y
	plp
	rts

CF1_O
	php
	rep	#$20
	lda	#$4441
	sta	$2143,y
	lda	#$4433
	sta	$21E2,y
	lda	$21E4,y
	and	#$0F00
	ora	#$3043
	sta	$21E4,y
	lda	#$3333
	sta	$2282,y
	lda	#$3333
	sta	$2284,y
	lda	#$3133
	sta	$2322,y
	lda	#$3333
	sta	$2324,y
	lda	#$3333
	sta	$23C2,y
	lda	#$3333
	sta	$23C4,y
	lda	#$3333
	sta	$2462,y
	lda	$2464,y
	and	#$0F00
	ora	#$3033
	sta	$2464,y
	lda	$2503,y
	and	#$0F00
	ora	#$3033
	sta	$2503,y
	lda	$25A3,y
	and	#$0F00
	ora	#$3033
	sta	$25A3,y
	sep	#$20
	lda	$2142,y
	and	#$F0
	ora	#$04
	sta	$2142,y
	lda	$2502,y
	and	#$F0
	ora	#$03
	sta	$2502,y
	plp
	rts

CF2_E
	php
	rep	#$20
	lda	#$4464
	sta	$2143,y
	lda	$21E3,y
	and	#$000F
	ora	#$4460
	sta	$21E3,y
	lda	#$BB6B
	sta	$2283,y
	lda	#$BBBB
	sta	$2322,y
	lda	$2324,y
	and	#$0F00
	ora	#$B0BB
	sta	$2324,y
	lda	#$BBBB
	sta	$23C2,y
	lda	$23C4,y
	and	#$0F00
	ora	#$B0BB
	sta	$23C4,y
	lda	#$BBBB
	sta	$2462,y
	lda	$2464,y
	and	#$0F00
	ora	#$B0BB
	sta	$2464,y
	lda	#$BBBB
	sta	$2502,y
	lda	$2504,y
	and	#$0F00
	ora	#$B0BB
	sta	$2504,y
	lda	#$BBBB
	sta	$25A2,y
	lda	$25A4,y
	and	#$0F00
	ora	#$B0BB
	sta	$25A4,y
	sep	#$20
	lda	$2145,y
	and	#$0F
	ora	#$40
	sta	$2145,y
	lda	#$BB
	sta	$2282,y
	lda	$2321,y
	and	#$F0
	ora	#$0B
	sta	$2321,y
	lda	$23C1,y
	and	#$F0
	ora	#$0B
	sta	$23C1,y
	lda	$2461,y
	and	#$F0
	ora	#$0B
	sta	$2461,y
	lda	$2501,y
	and	#$F0
	ora	#$0B
	sta	$2501,y
	lda	$25A1,y
	and	#$F0
	ora	#$0B
	sta	$25A1,y
	plp
	rts

CF2_O
	php
	rep	#$20
	lda	#$4444
	sta	$2144,y
	lda	$21E4,y
	and	#$0FF0
	ora	#$4004
	sta	$21E4,y
	lda	$2282,y
	and	#$00F0
	ora	#$B60B
	sta	$2282,y
	lda	$2284,y
	and	#$0F00
	ora	#$B0BB
	sta	$2284,y
	lda	#$BBBB
	sta	$2322,y
	lda	#$BBBB
	sta	$2324,y
	lda	#$BBBB
	sta	$23C2,y
	lda	#$BBBB
	sta	$23C4,y
	lda	#$BBBB
	sta	$2462,y
	lda	#$BBBB
	sta	$2464,y
	lda	#$BBBB
	sta	$2502,y
	lda	#$BBBB
	sta	$2504,y
	lda	#$BBBB
	sta	$25A2,y
	lda	#$BBBB
	sta	$25A4,y
	sep	#$20
	lda	$2143,y
	and	#$F0
	ora	#$06
	sta	$2143,y
	lda	$21E3,y
	and	#$F0
	ora	#$06
	sta	$21E3,y
	plp
	rts

CF3_E
	php
	rep	#$20
	lda	$2142,y
	and	#$0F00
	ora	#$B0BB
	sta	$2142,y
	lda	$2144,y
	and	#$0F00
	ora	#$B0BB
	sta	$2144,y
	lda	$21E4,y
	and	#$000F
	ora	#$1BB0
	sta	$21E4,y
	lda	$23C4,y
	and	#$F00F
	ora	#$0BB0
	sta	$23C4,y
	lda	$2461,y
	and	#$F0F0
	ora	#$0B0B
	sta	$2461,y
	lda	$2463,y
	and	#$0F0F
	ora	#$B0B0
	sta	$2463,y
	lda	$25A2,y
	and	#$000F
	ora	#$BBB0
	sta	$25A2,y
	lda	$25A4,y
	and	#$0FF0
	ora	#$B00B
	sta	$25A4,y
	lda	$2641,y
	and	#$0FF0
	ora	#$100B
	sta	$2641,y
	sep	#$20
	lda	$2141,y
	and	#$F0
	ora	#$0B
	sta	$2141,y
	lda	#$BB
	sta	$21E1,y
	lda	$2281,y
	and	#$0F
	ora	#$B0
	sta	$2281,y
	lda	$2283,y
	and	#$F0
	ora	#$0B
	sta	$2283,y
	lda	$2285,y
	and	#$F0
	ora	#$0B
	sta	$2285,y
	lda	$2321,y
	and	#$0F
	ora	#$B0
	sta	$2321,y
	lda	#$BB
	sta	$2323,y
	lda	$2325,y
	and	#$F0
	ora	#$0B
	sta	$2325,y
	lda	#$B1
	sta	$23C1,y
	lda	$23C3,y
	and	#$0F
	ora	#$B0
	sta	$23C3,y
	lda	#$BB
	sta	$2465,y
	lda	$2502,y
	and	#$F0
	ora	#$0B
	sta	$2502,y
	lda	$2504,y
	and	#$F0
	ora	#$0B
	sta	$2504,y
	lda	$2645,y
	and	#$0F
	ora	#$B0
	sta	$2645,y
	plp
	rts

CF3_O
	php
	rep	#$20
	lda	#$BBBB
	sta	$2142,y
	lda	$2144,y
	and	#$00F0
	ora	#$BB0B
	sta	$2144,y
	lda	$21E1,y
	and	#$0FF0
	ora	#$B00B
	sta	$21E1,y
	lda	$21E5,y
	and	#$0FF0
	ora	#$B001
	sta	$21E5,y
	lda	$2323,y
	and	#$0FF0
	ora	#$B00B
	sta	$2323,y
	lda	$23C1,y
	and	#$0FF0
	ora	#$100B
	sta	$23C1,y
	lda	$23C3,y
	and	#$F0F0
	ora	#$0B0B
	sta	$23C3,y
	lda	$2463,y
	and	#$F000
	ora	#$0BBB
	sta	$2463,y
	lda	$2465,y
	and	#$0FF0
	ora	#$B00B
	sta	$2465,y
	lda	$25A2,y
	and	#$F0F0
	ora	#$0B0B
	sta	$25A2,y
	lda	$25A4,y
	and	#$000F
	ora	#$BBB0
	sta	$25A4,y
	sep	#$20
	lda	$21E4,y
	and	#$F0
	ora	#$0B
	sta	$21E4,y
	lda	$2281,y
	and	#$F0
	ora	#$0B
	sta	$2281,y
	lda	$2284,y
	and	#$0F
	ora	#$B0
	sta	$2284,y
	lda	$2286,y
	and	#$0F
	ora	#$B0
	sta	$2286,y
	lda	$2321,y
	and	#$F0
	ora	#$0B
	sta	$2321,y
	lda	$2326,y
	and	#$0F
	ora	#$B0
	sta	$2326,y
	lda	$23C6,y
	and	#$0F
	ora	#$B0
	sta	$23C6,y
	lda	$2462,y
	and	#$0F
	ora	#$B0
	sta	$2462,y
	lda	$2503,y
	and	#$0F
	ora	#$B0
	sta	$2503,y
	lda	$2505,y
	and	#$0F
	ora	#$B0
	sta	$2505,y
	lda	#$B1
	sta	$2642,y
	lda	$2645,y
	and	#$F0
	ora	#$0B
	sta	$2645,y
	plp
	rts

CF4_E
	php
	rep	#$20
	lda	$2141,y
	and	#$0FF0
	ora	#$3003
	sta	$2141,y
	lda	$2143,y
	and	#$000F
	ora	#$3360
	sta	$2143,y
	lda	#$6333
	sta	$21E2,y
	lda	$21E4,y
	and	#$0F00
	ora	#$3033
	sta	$21E4,y
	lda	#$3333
	sta	$2282,y
	lda	$2284,y
	and	#$0F00
	ora	#$3033
	sta	$2284,y
	lda	#$3333
	sta	$2322,y
	lda	$2324,y
	and	#$0F00
	ora	#$3033
	sta	$2324,y
	lda	#$3333
	sta	$23C2,y
	lda	$23C4,y
	and	#$0F00
	ora	#$3031
	sta	$23C4,y
	lda	#$3333
	sta	$2462,y
	lda	$2464,y
	and	#$0F00
	ora	#$3033
	sta	$2464,y
	lda	#$3333
	sta	$2502,y
	lda	$2504,y
	and	#$0F00
	ora	#$3033
	sta	$2504,y
	lda	#$3333
	sta	$25A3,y
	sep	#$20
	lda	$21E1,y
	and	#$F0
	ora	#$03
	sta	$21E1,y
	lda	$2281,y
	and	#$F0
	ora	#$03
	sta	$2281,y
	lda	$2321,y
	and	#$F0
	ora	#$03
	sta	$2321,y
	lda	$23C1,y
	and	#$F0
	ora	#$03
	sta	$23C1,y
	lda	$2461,y
	and	#$F0
	ora	#$03
	sta	$2461,y
	lda	$2501,y
	and	#$F0
	ora	#$03
	sta	$2501,y
	lda	#$33
	sta	$25A2,y
	plp
	rts

CF4_O
	php
	rep	#$20
	lda	$2142,y
	and	#$F000
	ora	#$0633
	sta	$2142,y
	lda	$2144,y
	and	#$0FF0
	ora	#$3003
	sta	$2144,y
	lda	#$3633
	sta	$21E2,y
	lda	#$3333
	sta	$21E4,y
	lda	#$3333
	sta	$2282,y
	lda	#$3333
	sta	$2284,y
	lda	#$3333
	sta	$2322,y
	lda	#$3333
	sta	$2324,y
	lda	#$3333
	sta	$23C2,y
	lda	#$1333
	sta	$23C4,y
	lda	#$3333
	sta	$2462,y
	lda	#$3333
	sta	$2464,y
	lda	#$3333
	sta	$2502,y
	lda	#$3333
	sta	$2504,y
	lda	$25A2,y
	and	#$00F0
	ora	#$3303
	sta	$25A2,y
	lda	$25A4,y
	and	#$0F00
	ora	#$3033
	sta	$25A4,y
	sep	#$20
	plp
	rts

CF5_E
	php
	rep	#$20
	lda	$21E3,y
	and	#$0F00
	ora	#$4044
	sta	$21E3,y
	lda	$2283,y
	and	#$0F00
	ora	#$4044
	sta	$2283,y
	lda	$2323,y
	and	#$0F00
	ora	#$4044
	sta	$2323,y
	lda	#$4444
	sta	$23C3,y
	lda	#$4444
	sta	$2463,y
	lda	#$444B
	sta	$2502,y
	lda	$2504,y
	and	#$0F00
	ora	#$4044
	sta	$2504,y
	lda	#$B444
	sta	$25A2,y
	lda	$25A4,y
	and	#$0F00
	ora	#$4044
	sta	$25A4,y
	lda	#$4444
	sta	$2643,y
	sep	#$20
	lda	$20A4,y
	and	#$0F
	ora	#$60
	sta	$20A4,y
	lda	#$44
	sta	$2143,y
	lda	$23C2,y
	and	#$F0
	ora	#$04
	sta	$23C2,y
	lda	#$44
	sta	$2462,y
	lda	$2642,y
	and	#$F0
	ora	#$04
	sta	$2642,y
	plp
	rts

CF5_O
	php
	rep	#$20
	lda	$2143,y
	and	#$0FF0
	ora	#$4004
	sta	$2143,y
	lda	$21E3,y
	and	#$00F0
	ora	#$4404
	sta	$21E3,y
	lda	$2283,y
	and	#$00F0
	ora	#$4404
	sta	$2283,y
	lda	$2323,y
	and	#$00F0
	ora	#$4404
	sta	$2323,y
	lda	#$4444
	sta	$23C3,y
	lda	$2462,y
	and	#$00F0
	ora	#$4404
	sta	$2462,y
	lda	$2464,y
	and	#$0F00
	ora	#$4044
	sta	$2464,y
	lda	$2502,y
	and	#$00F0
	ora	#$B404
	sta	$2502,y
	lda	#$4444
	sta	$2504,y
	lda	$25A2,y
	and	#$00F0
	ora	#$4B04
	sta	$25A2,y
	lda	#$4444
	sta	$25A4,y
	lda	#$4444
	sta	$2643,y
	sep	#$20
	lda	$20A4,y
	and	#$F0
	ora	#$06
	sta	$20A4,y
	lda	$23C5,y
	and	#$0F
	ora	#$40
	sta	$23C5,y
	lda	$2645,y
	and	#$0F
	ora	#$40
	sta	$2645,y
	plp
	rts

CF6_E
	php
	rep	#$20
	lda	$21E4,y
	and	#$0FF0
	ora	#$D00D
	sta	$21E4,y
	lda	$2284,y
	and	#$0FF0
	ora	#$D00D
	sta	$2284,y
	lda	$2324,y
	and	#$0FF0
	ora	#$D00D
	sta	$2324,y
	lda	$23C4,y
	and	#$0F00
	ora	#$D0DD
	sta	$23C4,y
	lda	$2463,y
	and	#$00F0
	ora	#$DD0D
	sta	$2463,y
	lda	#$D1DD
	sta	$2502,y
	lda	#$1DDD
	sta	$25A2,y
	sep	#$20
	lda	$2145,y
	and	#$0F
	ora	#$D0
	sta	$2145,y
	lda	$2323,y
	and	#$F0
	ora	#$0D
	sta	$2323,y
	lda	$23C3,y
	and	#$0F
	ora	#$D0
	sta	$23C3,y
	lda	$2504,y
	and	#$0F
	ora	#$D0
	sta	$2504,y
	lda	$25A1,y
	and	#$F0
	ora	#$0D
	sta	$25A1,y
	plp
	rts

CF6_O
	php
	rep	#$20
	lda	$2324,y
	and	#$000F
	ora	#$DDD0
	sta	$2324,y
	lda	$23C3,y
	and	#$F0F0
	ora	#$0D0D
	sta	$23C3,y
	lda	$2464,y
	and	#$0F00
	ora	#$D0DD
	sta	$2464,y
	lda	#$1DDD
	sta	$2503,y
	lda	#$D1DD
	sta	$25A2,y
	sep	#$20
	lda	$2145,y
	and	#$F0
	ora	#$0D
	sta	$2145,y
	lda	#$DD
	sta	$21E5,y
	lda	#$DD
	sta	$2285,y
	lda	#$DD
	sta	$23C5,y
	lda	$2502,y
	and	#$F0
	ora	#$0D
	sta	$2502,y
	lda	$25A4,y
	and	#$0F
	ora	#$D0
	sta	$25A4,y
	plp
	rts

CF7_E
	php
	rep	#$20
	lda	$2461,y
	and	#$0F00
	ora	#$3033
	sta	$2461,y
	lda	#$3333
	sta	$2501,y
	lda	#$3333
	sta	$25A1,y
	lda	#$3333
	sta	$2641,y
	sep	#$20
	lda	$2321,y
	and	#$F0
	ora	#$0D
	sta	$2321,y
	lda	$23C1,y
	and	#$F0
	ora	#$0D
	sta	$23C1,y
	lda	$2500,y
	and	#$F0
	ora	#$03
	sta	$2500,y
	lda	$25A0,y
	and	#$F0
	ora	#$03
	sta	$25A0,y
	lda	$2640,y
	and	#$F0
	ora	#$03
	sta	$2640,y
	plp
	rts

CF7_O
	php
	rep	#$20
	lda	$2461,y
	and	#$00F0
	ora	#$3303
	sta	$2461,y
	lda	#$3333
	sta	$2501,y
	lda	#$3333
	sta	$25A1,y
	lda	#$3333
	sta	$2641,y
	sep	#$20
	lda	$2322,y
	and	#$0F
	ora	#$D0
	sta	$2322,y
	lda	$23C2,y
	and	#$0F
	ora	#$D0
	sta	$23C2,y
	lda	$2503,y
	and	#$0F
	ora	#$30
	sta	$2503,y
	lda	$25A3,y
	and	#$0F
	ora	#$30
	sta	$25A3,y
	lda	$2643,y
	and	#$0F
	ora	#$30
	sta	$2643,y
	plp
	rts

	mx	%00

