*
* Generated by py/gen_palette.py — §2 target; maze #1D in 0–3
* Do not edit by hand; regenerate with: python3 py/gen_palette.py
*

PalTable
	dw	$0000,$0DDF,$0FBA,$0F00
	dw	$00F0,$0F00,$0D95,$0FBF
	dw	$04BA,$00FF,$04BF,$0FB5
	dw	$0000,$0FF0,$0DDF,$022F

