*
* Generated by py/gen_palette.py — maze #1D in 0–3, 12 and 14
* Do not edit by hand; regenerate with: python3 py/gen_palette.py
* MazeBankRGB: per arcade bank, outline (pen 12) and fill (pen 14) words
*

PalTable
	dw	$0000,$0DDF,$0FBA,$0F00
	dw	$00F0,$0000,$0D95,$0FBF
	dw	$0000,$00FF,$04BF,$0FB5
	dw	$0F00,$0FF0,$0FBA,$022F

MazeBankRGB
	dw	$0000,$0000	; #00
	dw	$0F00,$022F	; #01
	dw	$0000,$0000	; #02
	dw	$0FBF,$022F	; #03
	dw	$0000,$0000	; #04
	dw	$00FF,$022F	; #05
	dw	$0000,$0000	; #06
	dw	$0FB5,$022F	; #07
	dw	$0000,$0000	; #08
	dw	$0FF0,$0F00	; #09
	dw	$0000,$0000	; #0A
	dw	$0000,$0000	; #0B
	dw	$0000,$0000	; #0C
	dw	$0000,$0000	; #0D
	dw	$0FBA,$0000	; #0E
	dw	$0DDF,$00F0	; #0F
	dw	$022F,$0000	; #10
	dw	$0FBA,$022F	; #11
	dw	$0F00,$0DDF	; #12
	dw	$0000,$0000	; #13
	dw	$0DDF,$0D95	; #14
	dw	$0D95,$00F0	; #15
	dw	$0DDF,$04BF	; #16
	dw	$0DDF,$00F0	; #17
	dw	$0FF0,$0FBF	; #18
	dw	$0000,$022F	; #19
	dw	$022F,$0000	; #1A
	dw	$022F,$0000	; #1B
	dw	$0000,$0000	; #1C
	dw	$0F00,$0FBA	; #1D
	dw	$0FBA,$022F	; #1E
	dw	$0DDF,$0000	; #1F

