#!/usr/bin/env python3
"""Emit compiled 65816 masked blits for the act clapper and the act 3 stork.

The intermission slate is four sprites: the board ($12 left, $13 right)
and the clapper bar above it ($10/$14/$16 left, $11/$15/$17 right, open
to shut). Act 3 adds the stork (head $30, body $18, flap $2C), the sack
it drops ($07) and the junior who climbs out ($0F).

Every one of those scripts paints with color bank #16: pen 1 yellow,
pen 2 light blue, pen 3 white. The clapper uses only the white pen.
Index:

  clapper: (code & 7)*2 + (X & 1)  → ActBlitTable
  act 3:   index*2 + (X & 1)        → Act3BlitTable

Act3BlitTable order matches :a3tab in iigs/lower_host.s. Index 0 is the
stork head, drawn again on top of the body (they share a Y).

Usage:
  python3 py/gen_compiled_acts.py
  python3 py/gen_compiled_acts.py --gfx build/gfx -o iigs/compiled_acts.s
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from blit_emit import BlitStats, check_equivalence, emit_blit  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_GFX = ROOT / "build" / "gfx"
DEFAULT_PALETTE_ROM = ROOT / "mspacman" / "82s126.4a"
DEFAULT_OUT = ROOT / "iigs" / "compiled_acts.s"

BANK = 0x16

# code & 7 is the table index, so the order is $10, $11, $12, ...
ACTS = (
    (0x10, "clapper open, left"),
    (0x11, "clapper open, right"),
    (0x12, "board, left"),
    (0x13, "board, right"),
    (0x14, "clapper mid, left"),
    (0x15, "clapper mid, right"),
    (0x16, "clapper shut, left"),
    (0x17, "clapper shut, right"),
)

# Index order is the scan table in lower_host.s (:a3tab). 0 is the head.
ACT3 = (
    (0x30, "stork head"),
    (0x18, "stork"),
    (0x2C, "stork flap"),
    (0x07, "sack"),
    (0x0F, "junior"),
)


def _load(name: str):
    path = ROOT / "py" / name
    spec = importlib.util.spec_from_file_location(name.replace(".py", ""), path)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--gfx", type=Path, default=DEFAULT_GFX)
    ap.add_argument("--palette-rom", type=Path, default=DEFAULT_PALETTE_ROM)
    ap.add_argument("-o", "--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args()

    sheet_path = args.gfx / "sprites14x12.bin"
    if not sheet_path.is_file():
        raise SystemExit(f"missing {sheet_path} (run make gfx)")

    gfx = _load("gen_shr_gfx.py")
    pal = _load("gen_palette.py")
    rom_pens = pal.load_palette_pens(args.palette_rom, BANK)
    shr_map = tuple(pal.STABLE_ROM_TO_SHR[p & 15] for p in rom_pens)
    sheet = sheet_path.read_bytes()

    lines: list[str] = [
        "*",
        "* Generated by py/gen_compiled_acts.py - do not edit by hand",
        "* ActBlitTable: (sprite & 7)*2 + (X&1) -> abs addresses",
        "* Sprites $10-$17, bank #16. Act3BlitTable: index*2 + (X&1)",
        "* for stork $30/$18/$2C, sack $07, junior $0F. Y = SHR offset,",
        "* DBR = $01, returns via RTS",
        "*",
        "",
    ]

    labels: list[str] = []
    body: list[str] = []
    stats = BlitStats()

    def emit_family(go: str, table: str, sprites: tuple, prefix: str) -> None:
        lines.extend([
            go,
            f"* X = index*2 into {table}; JMP so blit RTS returns to caller.",
            f"\tjmp\t({table},x)",
            "",
            table,
        ])
        for i, (code, name) in enumerate(sprites):
            for parity, tag in enumerate(("E", "O")):
                lab = f"{prefix}{i}_{tag}"
                labels.append(lab)
                lines.append(
                    f"\tda\t{lab}\t; {name} spr=${code:02X} "
                    f"{'odd' if parity else 'even'}"
                )
        lines.append("")
        for i, (code, name) in enumerate(sprites):
            even = [[shr_map[p & 3] for p in row] for row in gfx.unpack_sprite_arcade(sheet, code)]
            odd = gfx.shift_odd_cell(even)
            cells = []
            for img in (even, odd):
                spr = gfx.pack_4bpp_rows(img)
                msk = bytes(gfx.pack_4bpp_rows(gfx.mask_from_pens(img)))
                check_equivalence(bytes(spr), msk)
                cells.append((spr, msk))
            for tag, (spr, msk) in zip(("E", "O"), cells):
                lab = f"{prefix}{i}_{tag}"
                body.extend(emit_blit(lab, bytes(spr), msk, stats, word16=True))
                print(f"  {lab}: {name} map={shr_map}")

    emit_family("ActBlitGo", "ActBlitTable", ACTS, "CA")
    emit_family("Act3BlitGo", "Act3BlitTable", ACT3, "C3")

    lines.extend(body)
    lines.append("\tmx\t%00")
    lines.append("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"wrote {args.out} ({len(labels)} blits, {stats})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
