#!/usr/bin/env python3
"""Emit compiled 65816 masked blits for normal ghost walk frames.

Reads build/gfx sprites14x12{,.odd}{,.mask}.bin, remaps body pen 6 → each of
Blinky/Pinky/Inky/Clyde (5/7/9/11), and writes Merlin32 routines plus a jump
table indexed by:

  index = color_slot*16 + (ACT_SPR & 7)*2 + (X & 1)
  color_slot = (ACT_COLOR - 5) / 2   ; 5,7,9,11 → 0..3

Transparent mask bytes are omitted; adjacent opaque bytes are coalesced into
16-bit ops by py/blit_emit.py.

Usage:
  python3 py/gen_compiled_ghosts.py
  python3 py/gen_compiled_ghosts.py --gfx build/gfx -o iigs/compiled_ghosts.s
  python3 py/gen_compiled_ghosts.py --no-word16    # 8-bit only, for A/B
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from blit_emit import BlitStats, check_equivalence, emit_blit  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_GFX = ROOT / "build" / "gfx"
DEFAULT_OUT = ROOT / "iigs" / "compiled_ghosts.s"

SPR_BYTES = 84
BODY_PEN = 6
# color_slot 0..3
COLORS = (5, 7, 9, 11)  # Blinky, Pinky, Inky, Clyde
COLOR_NAMES = ("Blinky", "Pinky", "Inky", "Clyde")
GHOST_BASE = 0x20
NFRAMES = 8  # $20..$27


def remap_body_byte(b: int, body: int) -> int:
    hi = (b >> 4) & 0xF
    lo = b & 0xF
    if hi == BODY_PEN:
        hi = body
    if lo == BODY_PEN:
        lo = body
    return ((hi & 0xF) << 4) | (lo & 0xF)


def load_sheet(path: Path) -> bytes:
    data = path.read_bytes()
    need = 64 * SPR_BYTES
    if len(data) < need:
        raise SystemExit(f"{path}: expected ≥{need} bytes, got {len(data)}")
    return data


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--gfx", type=Path, default=DEFAULT_GFX)
    ap.add_argument("-o", "--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument(
        "--no-word16",
        dest="word16",
        action="store_false",
        help="emit 8-bit ops only (pre-optimization output, for A/B)",
    )
    args = ap.parse_args()

    spr_e = load_sheet(args.gfx / "sprites14x12.bin")
    msk_e = load_sheet(args.gfx / "sprites14x12.mask.bin")
    spr_o = load_sheet(args.gfx / "sprites14x12.odd.bin")
    msk_o = load_sheet(args.gfx / "sprites14x12.odd.mask.bin")

    lines: list[str] = [
        "*",
        "* Generated by py/gen_compiled_ghosts.py - do not edit by hand",
        "* GhostBlitTable: color_slot*16 + (ACT_SPR&7)*2 + (X&1) -> abs addresses",
        "* Each blit: Y = SHR offset, DBR = $01, returns via RTS",
        "*",
        "",
        "GhostBlitGo",
        "* X = index*2 into GhostBlitTable; JMP so blit RTS returns to caller.",
        "\tjmp\t(GhostBlitTable,x)",
        "",
        "GhostBlitTable",
    ]

    labels: list[str] = []
    for ci, (pen, cname) in enumerate(zip(COLORS, COLOR_NAMES)):
        for frame in range(NFRAMES):
            for parity, tag in enumerate(("E", "O")):
                lab = f"CG{ci}_{frame}{tag}"
                labels.append(lab)
                # comment for humans
                spr_code = GHOST_BASE + frame
                lines.append(
                    f"\tda\t{lab}\t; {cname} pen={pen} spr=${spr_code:02X} {'odd' if parity else 'even'}"
                )

    lines.append("")
    stats = BlitStats()
    body_lines: list[str] = []

    for ci, pen in enumerate(COLORS):
        for frame in range(NFRAMES):
            spr_code = GHOST_BASE + frame
            base = spr_code * SPR_BYTES
            for parity, (spr_sheet, msk_sheet, tag) in enumerate(
                (
                    (spr_e, msk_e, "E"),
                    (spr_o, msk_o, "O"),
                )
            ):
                lab = f"CG{ci}_{frame}{tag}"
                raw = spr_sheet[base : base + SPR_BYTES]
                msk = msk_sheet[base : base + SPR_BYTES]
                colored = bytes(remap_body_byte(b, pen) for b in raw)
                if args.word16:
                    check_equivalence(colored, msk)
                body_lines.extend(
                    emit_blit(lab, colored, msk, stats, word16=args.word16)
                )

    lines.extend(body_lines)
    # Restore assemble-time MX after sep #$20 routines
    lines.append("\tmx\t%00")
    lines.append("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n", encoding="ascii")
    n = len(labels)
    print(f"wrote {args.out} ({n} blits, {stats})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
