#!/usr/bin/env python3
"""Build IIgs SHR palette words from Pac-Man color/palette PROMs.

Writes:
  build/gfx/palette.bin     — 16×16-bit SHR colors (32 bytes, little-endian)
  iigs/palette_data.s       — Merlin32 `dw` tables PalTable and MazeBankRGB

Target pen map (docs/ColorMap.md §3):
  0 black, 1 pale, 2 peach, 3 red, 4 green, 6 brown, 7 pink, 9 cyan,
  10 light blue, 11 orange, 12 maze outline, 13 yellow, 14 maze fill,
  15 deep blue; 5 and 8 free (black).

Slots 0–3 track maze palette #1D, so its tiles draw with no remapping.
Maze walls draw their outline (bank pen 3) on pen 12 and their fill (bank
pen 2) on pen 14. Those two are the only pens written at run time:
SetMazePens loads them from MazeBankRGB for each level's maze bank, and
for bank #1F during the level-end flash.

Usage:
  python3 py/gen_palette.py
  python3 py/gen_palette.py --maze-pal 0x1D --out build/gfx
"""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_COLOR = ROOT / "mspacman-orig" / "82s123.7f"
DEFAULT_PALETTE = ROOT / "mspacman-orig" / "82s126.4a"
DEFAULT_OUT = ROOT / "build" / "gfx"
DEFAULT_ASM = ROOT / "iigs" / "palette_data.s"
MAZE_PAL = 0x1D
NUM_BANKS = 32
MAZE_OUTLINE_PEN = 12  # maze wall bank pen 3
MAZE_FILL_PEN = 14     # maze wall bank pen 2

# Color-ROM index per SHR pen; None = free pen (black).
# Pens 0–3, 12 and 14 overwritten from the maze bank when building.
TARGET_COLOR_ROM = (
    0,     # 0 black
    15,    # 1 pale
    14,    # 2 peach
    1,     # 3 red (Blinky)
    12,    # 4 green
    None,  # 5 free
    2,     # 6 brown
    3,     # 7 pink (Pinky)
    None,  # 8 free
    5,     # 9 cyan (Inky)
    6,     # 10 light blue
    7,     # 11 orange (Sue)
    1,     # 12 maze outline
    9,     # 13 yellow
    14,    # 14 maze fill
    11,    # 15 deep blue
)


# Color-ROM index -> SHR pen (docs/ColorMap.md §4). Teal (13) has no pen
# and takes light blue 10; only the undrawn HUD pear bank #17 uses it.
STABLE_ROM_TO_SHR = {
    0: 0, 1: 3, 2: 6, 3: 7, 4: 0, 5: 9, 6: 10, 7: 11,
    8: 0, 9: 13, 10: 0, 11: 15, 12: 4, 13: 10, 14: 2, 15: 1,
}


def load_prom_colors(color_rom: Path) -> list[tuple[int, int, int]]:
    data = color_rom.read_bytes()
    colors: list[tuple[int, int, int]] = []
    for i in range(16):
        b = data[i] if i < len(data) else 0
        r = ((b >> 0) & 1) * 0x21 + ((b >> 1) & 1) * 0x47 + ((b >> 2) & 1) * 0x97
        g = ((b >> 3) & 1) * 0x21 + ((b >> 4) & 1) * 0x47 + ((b >> 5) & 1) * 0x97
        bl = ((b >> 6) & 1) * 0x51 + ((b >> 7) & 1) * 0xAE
        colors.append((r, g, bl))
    return colors


def load_palette_pens(palette_rom: Path, palette_index: int) -> list[int]:
    data = palette_rom.read_bytes()
    base = (palette_index & 63) * 4
    return [data[base + i] & 0x0F for i in range(4)]


def rgb_to_shr(r: int, g: int, b: int) -> int:
    """IIgs SHR $0RGB word: bits 0–3 blue, 4–7 green, 8–11 red.

    Stored little-endian as bytes [GB, 0R] (see Apple SHR / CiderPress notes).
    """
    return ((r >> 4) << 8) | ((g >> 4) << 4) | (b >> 4)


def build_shr_palette(
    colors: list[tuple[int, int, int]],
    maze_pens: list[int],
) -> list[int]:
    """Target pens; slots 0–3 = maze bank (level-1 walls/dots), and its
    outline and fill in the maze wall pens."""
    words = [0 if ci is None else rgb_to_shr(*colors[ci & 15]) for ci in TARGET_COLOR_ROM]
    for i, ci in enumerate(maze_pens):
        words[i] = rgb_to_shr(*colors[ci & 15])
    words[MAZE_OUTLINE_PEN] = words[3]
    words[MAZE_FILL_PEN] = words[2]
    return words


def maze_bank_rgb(colors: list[tuple[int, int, int]], palette_rom: Path) -> list[tuple[int, int]]:
    """Per bank: (outline, fill) SHR words, its pens 3 and 2."""
    out = []
    for b in range(NUM_BANKS):
        pens = load_palette_pens(palette_rom, b)
        out.append((rgb_to_shr(*colors[pens[3]]), rgb_to_shr(*colors[pens[2]])))
    return out


def write_palette_bin(path: Path, words: list[int]) -> None:
    blob = bytearray()
    for w in words:
        blob.append(w & 0xFF)
        blob.append((w >> 8) & 0xFF)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(blob)


def write_palette_asm(
    path: Path, words: list[int], maze_pal: int, mazes: list[tuple[int, int]]
) -> None:
    lines = [
        "*",
        f"* Generated by py/gen_palette.py — maze #{maze_pal:02X} in 0–3, 12 and 14",
        "* Do not edit by hand; regenerate with: python3 py/gen_palette.py",
        "* MazeBankRGB: per arcade bank, outline (pen 12) and fill (pen 14) words",
        "*",
        "",
        "PalTable",
    ]
    for row in range(4):
        chunk = words[row * 4 : row * 4 + 4]
        lines.append("\tdw\t" + ",".join(f"${w:04X}" for w in chunk))
    lines.append("")
    lines.append("MazeBankRGB")
    for b, (outline, fill) in enumerate(mazes):
        lines.append(f"\tdw\t${outline:04X},${fill:04X}\t; #{b:02X}")
    lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--color-rom", type=Path, default=DEFAULT_COLOR)
    ap.add_argument("--palette-rom", type=Path, default=DEFAULT_PALETTE)
    ap.add_argument("--maze-pal", type=lambda s: int(s, 0), default=MAZE_PAL)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--asm", type=Path, default=DEFAULT_ASM)
    args = ap.parse_args()

    colors = load_prom_colors(args.color_rom)
    pens = load_palette_pens(args.palette_rom, args.maze_pal)
    words = build_shr_palette(colors, pens)

    bin_path = args.out / "palette.bin"
    write_palette_bin(bin_path, words)
    write_palette_asm(args.asm, words, args.maze_pal, maze_bank_rgb(colors, args.palette_rom))

    print(f"wrote {bin_path} (32 bytes)")
    print(f"wrote {args.asm}")
    print(f"maze pal #{args.maze_pal:02X} pens {pens} → RGB {[colors[p] for p in pens]}")
    print(f"SHR words: {[f'${w:04X}' for w in words]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
