#!/usr/bin/env python3
"""Build IIgs SHR palette words from Pac-Man color/palette PROMs.

Writes:
  build/gfx/palette.bin     — 16×16-bit SHR colors (32 bytes, little-endian)
  iigs/palette_data.s       — Merlin32 `dw` table for PalTable

SHR slots 0–3 are maze palette #1D (level-1 walls/dots). Slots 4–15 hold the
remaining color-ROM RGB values so sprite work can pick fixed pens later.

Usage:
  python3 py/gen_palette.py
  python3 py/gen_palette.py --maze-pal 0x1D --out build/gfx
"""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_COLOR = ROOT / "mspacman-orig" / "82s123.7f"
DEFAULT_PALETTE = ROOT / "mspacman-orig" / "82s126.4a"
DEFAULT_OUT = ROOT / "build" / "gfx"
DEFAULT_ASM = ROOT / "iigs" / "palette_data.s"
MAZE_PAL = 0x1D


def load_prom_colors(color_rom: Path) -> list[tuple[int, int, int]]:
    data = color_rom.read_bytes()
    colors: list[tuple[int, int, int]] = []
    for i in range(16):
        b = data[i] if i < len(data) else 0
        r = ((b >> 0) & 1) * 0x21 + ((b >> 1) & 1) * 0x47 + ((b >> 2) & 1) * 0x97
        g = ((b >> 3) & 1) * 0x21 + ((b >> 4) & 1) * 0x47 + ((b >> 5) & 1) * 0x97
        bl = ((b >> 6) & 1) * 0x51 + ((b >> 7) & 1) * 0xAE
        colors.append((r, g, bl))
    return colors


def load_palette_pens(palette_rom: Path, palette_index: int) -> list[int]:
    data = palette_rom.read_bytes()
    base = (palette_index & 63) * 4
    return [data[base + i] & 0x0F for i in range(4)]


def rgb_to_shr(r: int, g: int, b: int) -> int:
    """IIgs SHR $0RGB word: bits 0–3 blue, 4–7 green, 8–11 red.

    Stored little-endian as bytes [GB, 0R] (see Apple SHR / CiderPress notes).
    """
    return ((r >> 4) << 8) | ((g >> 4) << 4) | (b >> 4)


def build_shr_palette(
    colors: list[tuple[int, int, int]],
    maze_pens: list[int],
) -> list[int]:
    """Slots 0–3 = maze pens; 4–15 = color ROM 0–11 (skip duplicates later if needed)."""
    words = [0] * 16
    for i, ci in enumerate(maze_pens):
        words[i] = rgb_to_shr(*colors[ci & 15])
    # Fill remaining with raw color-ROM order for experimentation
    for i in range(16):
        slot = 4 + (i % 12)
        if slot < 16 and words[slot] == 0 and slot >= 4:
            pass
    for i in range(12):
        words[4 + i] = rgb_to_shr(*colors[i])
    return words


def write_palette_bin(path: Path, words: list[int]) -> None:
    blob = bytearray()
    for w in words:
        blob.append(w & 0xFF)
        blob.append((w >> 8) & 0xFF)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(blob)


def write_palette_asm(path: Path, words: list[int], maze_pal: int) -> None:
    lines = [
        "*",
        f"* Generated by py/gen_palette.py — maze palette #{maze_pal:02X} in slots 0–3",
        "* Do not edit by hand; regenerate with: python3 py/gen_palette.py",
        "*",
        "",
        "PalTable",
    ]
    for row in range(4):
        chunk = words[row * 4 : row * 4 + 4]
        lines.append("\tdw\t" + ",".join(f"${w:04X}" for w in chunk))
    lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--color-rom", type=Path, default=DEFAULT_COLOR)
    ap.add_argument("--palette-rom", type=Path, default=DEFAULT_PALETTE)
    ap.add_argument("--maze-pal", type=lambda s: int(s, 0), default=MAZE_PAL)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--asm", type=Path, default=DEFAULT_ASM)
    args = ap.parse_args()

    colors = load_prom_colors(args.color_rom)
    pens = load_palette_pens(args.palette_rom, args.maze_pal)
    words = build_shr_palette(colors, pens)

    bin_path = args.out / "palette.bin"
    write_palette_bin(bin_path, words)
    write_palette_asm(args.asm, words, args.maze_pal)

    print(f"wrote {bin_path} (32 bytes)")
    print(f"wrote {args.asm}")
    print(f"maze pal #{args.maze_pal:02X} pens {pens} → RGB {[colors[p] for p in pens]}")
    print(f"SHR words 0–3: {[f'${w:04X}' for w in words[:4]]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
