#!/usr/bin/env python3
"""Emit compiled 65816 masked blits for the ghosts.

Reads build/gfx sprites14x12{,.odd}{,.mask}.bin and writes Merlin32 routines
plus a jump table indexed by:

  index = ACT_COLOR*16 + (ACT_SPR & 7)*2 + (X & 1)

ACT_COLOR is the ghost's blit slot (equates.s COL_*):

  0-3  Blinky, Pinky, Inky, Sue: walk frames $20-$27, the body marker
       (nibble 6, arcade pen 3) in the pen of the ghost's bank #01/#03/#05/#07
  4    frightened: sprites $1C/$1D in bank #11 (deep blue, peach face)
  5    flashing: sprites $1C/$1D in bank #12 (pale, red face)
  6    eyes: walk frames with the body dropped

The frightened slots have two frames; ACT_SPR bit 0 picks one. Every pen
comes from the stable color-ROM map in gen_palette.py, so nothing writes the
palette at run time.

Transparent mask bytes are omitted; adjacent opaque bytes are coalesced into
16-bit ops by py/blit_emit.py.

Usage:
  python3 py/gen_compiled_ghosts.py
  python3 py/gen_compiled_ghosts.py --gfx build/gfx --palette-rom mspacman/82s126.4a -o iigs/compiled_ghosts.s
  python3 py/gen_compiled_ghosts.py --no-word16    # 8-bit only, for A/B
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from blit_emit import BlitStats, check_equivalence, emit_blit  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_GFX = ROOT / "build" / "gfx"
DEFAULT_PALETTE_ROM = ROOT / "mspacman" / "82s126.4a"
DEFAULT_OUT = ROOT / "iigs" / "compiled_ghosts.s"

SPR_BYTES = 84
NFRAMES = 8
# Sheet nibble -> arcade 2bpp pen (gen_shr_gfx _SPRITE_PEN_MAP, inverted)
SHEET_TO_ARCADE = {0: 0, 1: 1, 15: 2, 6: 3}

# (name, arcade bank or None for eyes, first sprite code, frames)
SLOTS = (
    ("Blinky", 0x01, 0x20, 8),
    ("Pinky", 0x03, 0x20, 8),
    ("Inky", 0x05, 0x20, 8),
    ("Sue", 0x07, 0x20, 8),
    ("Fright", 0x11, 0x1C, 2),
    ("Flash", 0x12, 0x1C, 2),
    ("Eyes", None, 0x20, 8),
)


def _load_pal():
    path = ROOT / "py" / "gen_palette.py"
    spec = importlib.util.spec_from_file_location("gen_palette", path)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod


def nibble_map(pal, palette_rom: Path, bank: int | None) -> dict[int, int]:
    """Sheet nibble -> SHR pen for one slot."""
    if bank is None:
        return {0: 0, 1: 1, 15: 15, 6: 0}
    pens = pal.load_palette_pens(palette_rom, bank)
    return {n: pal.STABLE_ROM_TO_SHR[pens[p]] for n, p in SHEET_TO_ARCADE.items()}


def remap(raw: bytes, nib: dict[int, int]) -> bytes:
    return bytes((nib[b >> 4] << 4) | nib[b & 0xF] for b in raw)


def mask_from_colored(colored: bytes) -> bytes:
    """Opaque where nibble != 0 (eyes slot drops body from the mask too)."""
    out = bytearray(len(colored))
    for i, b in enumerate(colored):
        m = 0
        if b & 0xF0:
            m |= 0xF0
        if b & 0x0F:
            m |= 0x0F
        out[i] = m
    return bytes(out)


def load_sheet(path: Path) -> bytes:
    data = path.read_bytes()
    need = 64 * SPR_BYTES
    if len(data) < need:
        raise SystemExit(f"{path}: expected ≥{need} bytes, got {len(data)}")
    return data


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--gfx", type=Path, default=DEFAULT_GFX)
    ap.add_argument("--palette-rom", type=Path, default=DEFAULT_PALETTE_ROM)
    ap.add_argument("-o", "--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument(
        "--no-word16",
        dest="word16",
        action="store_false",
        help="emit 8-bit ops only (pre-optimization output, for A/B)",
    )
    args = ap.parse_args()

    pal = _load_pal()
    spr_e = load_sheet(args.gfx / "sprites14x12.bin")
    msk_e = load_sheet(args.gfx / "sprites14x12.mask.bin")
    spr_o = load_sheet(args.gfx / "sprites14x12.odd.bin")
    msk_o = load_sheet(args.gfx / "sprites14x12.odd.mask.bin")

    lines: list[str] = [
        "*",
        "* Generated by py/gen_compiled_ghosts.py - do not edit by hand",
        "* GhostBlitTable: ACT_COLOR*16 + (ACT_SPR&7)*2 + (X&1) -> abs addresses",
        "* Each blit: Y = SHR offset, DBR = $01, returns via RTS",
        "*",
        "",
        "GhostBlitGo",
        "* X = index*2 into GhostBlitTable; JMP so blit RTS returns to caller.",
        "\tjmp\t(GhostBlitTable,x)",
        "",
        "GhostBlitTable",
    ]

    stats = BlitStats()
    body_lines: list[str] = []
    nblits = 0
    for ci, (name, bank, base_code, nframes) in enumerate(SLOTS):
        nib = nibble_map(pal, args.palette_rom, bank)
        desc = "eyes" if bank is None else f"bank=#{bank:02X} pens={nib[1]},{nib[15]},{nib[6]}"
        for frame in range(NFRAMES):
            f = frame % nframes
            for tag in ("E", "O"):
                lines.append(
                    f"\tda\tCG{ci}_{f}{tag}\t; {name} {desc} spr=${base_code + f:02X}"
                    f" {'odd' if tag == 'O' else 'even'}"
                )
        for f in range(nframes):
            base = (base_code + f) * SPR_BYTES
            for spr_sheet, msk_sheet, tag in ((spr_e, msk_e, "E"), (spr_o, msk_o, "O")):
                colored = remap(spr_sheet[base : base + SPR_BYTES], nib)
                if bank is None:
                    msk = mask_from_colored(colored)
                else:
                    msk = msk_sheet[base : base + SPR_BYTES]
                if args.word16:
                    check_equivalence(colored, msk)
                body_lines.extend(
                    emit_blit(f"CG{ci}_{f}{tag}", colored, msk, stats, word16=args.word16)
                )
                nblits += 1

    lines.append("")
    lines.extend(body_lines)
    # Restore assemble-time MX after sep #$20 routines
    lines.append("\tmx\t%00")
    lines.append("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"wrote {args.out} ({nblits} blits, {stats})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
