#!/usr/bin/env python3
"""Generate the phase 3 entry table and C hooks from lower/entries.txt.

Manifest lines, grouped under [file] headers (the .c / .s base name):

    name  result  param-kinds...

`name=label` calls assembly routine `label` for C function `name`, for
functions whose name is also a RAM symbol (pill_bitmap).

Result kinds: v (void), b (byte, bool), w (word), c (Coord, y low x high).
Param kinds, one per C parameter in order:
    B  Board *          not passed
    R  WorkRam *        not passed (the 65816 uses absolute addresses)
    b  byte or bool
    w  16-bit value
    c  Coord            16-bit, y low x high
    p  pointer into Board.mem, passed as its 16-bit bus address

Registers, in parameter order: a byte takes the first free of A, X, Y,
then one direct-page byte; a word takes the first free of X, Y, then two
direct-page bytes (from $00). A byte result comes back in A, a word or
Coord in X.

Writes lower/entries.s (one JSR/RTL stub per function, 4 bytes each, at
the start of lower.bin), lower/host/entries.h (ids, the function
table, and one LH_<name> hook macro per function), and lower/entry_ids.s
(LE_<name> stub offsets for the IIgs host).

Usage:
  python3 py/gen_lower_entries.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "lower" / "entries.txt"
OUT_S = ROOT / "lower" / "entries.s"
OUT_H = ROOT / "lower" / "host" / "entries.h"
OUT_IDS = ROOT / "lower" / "entry_ids.s"

RESULTS = {"v", "b", "w", "c"}
PARAMS = {"B", "R", "b", "w", "c", "p"}
LABELS: dict[str, str] = {}


def parse() -> list[tuple[str, str, str, list[str]]]:
    fns = []
    group = None
    seen = set()
    for n, raw in enumerate(MANIFEST.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        if line.startswith("[") and line.endswith("]"):
            group = line[1:-1].strip()
            continue
        parts = line.split()
        if group is None:
            raise SystemExit(f"{MANIFEST}:{n}: entry before any [file]")
        if len(parts) < 2:
            raise SystemExit(f"{MANIFEST}:{n}: need name and result")
        name, res, params = parts[0], parts[1], parts[2:]
        name, _, label = name.partition("=")
        LABELS[name] = label or name
        if res not in RESULTS:
            raise SystemExit(f"{MANIFEST}:{n}: bad result kind {res}")
        for k in params:
            if k not in PARAMS:
                raise SystemExit(f"{MANIFEST}:{n}: bad param kind {k}")
        if name in seen:
            raise SystemExit(f"{MANIFEST}:{n}: {name} listed twice")
        seen.add(name)
        fns.append((group, name, res, params))
    return fns


def assign(params: list[str]) -> list[tuple[int, str, str]]:
    """(param index, kind, location) for each passed parameter."""
    free = {"A": True, "X": True, "Y": True}
    dp = 0
    out = []
    for i, k in enumerate(params):
        if k in ("B", "R"):
            continue
        if k == "b":
            for r in ("A", "X", "Y"):
                if free[r]:
                    free[r] = False
                    out.append((i, k, r))
                    break
            else:
                out.append((i, k, f"dp{dp}"))
                dp += 1
        else:
            for r in ("X", "Y"):
                if free[r]:
                    free[r] = False
                    out.append((i, k, r))
                    break
            else:
                out.append((i, k, f"dp{dp}"))
                dp += 2
    return out


def c_value(kind: str, expr: str) -> str:
    if kind == "b":
        return f"(uint16_t)(uint8_t)({expr})"
    if kind == "w":
        return f"(uint16_t)({expr})"
    if kind == "c":
        return f"lower_coord_word({expr})"
    if kind == "p":
        return f"lower_mem_addr((const void *)({expr}))"
    raise AssertionError(kind)


def emit_h(fns) -> str:
    lines = [
        "/* Generated by py/gen_lower_entries.py from lower/entries.txt. */",
        "#ifndef LOWER_ENTRIES_H",
        "#define LOWER_ENTRIES_H",
        "",
        "enum {",
    ]
    for i, (_, name, _, _) in enumerate(fns):
        lines.append(f"\tLF_{name} = {i},")
    lines += [f"\tLF_COUNT = {len(fns)}", "};", ""]
    table = ["#if defined(LOWER_FN_TABLE) && !defined(LOWER_FN_TABLE_DONE)",
             "#define LOWER_FN_TABLE_DONE",
             "static const LowerFn k_lower_fns[LF_COUNT > 0 ? LF_COUNT : 1] = {"]
    for group, name, res, _ in fns:
        table.append(f"\t{{\"{name}\", \"{group}\", '{res}'}},")
    if not fns:
        table.append("\t{0, 0, 0},")
    table += ["};", "#endif", ""]

    for group, name, res, params in fns:
        if group == "selftest":
            continue
        ps = [f"p{i}" for i in range(len(params))]
        call = f"{name}({', '.join(ps)})"
        body = []
        body.append("\tint lm_ = lower_enter(LF_%s); \\" % name)
        body.append("\tif (lm_) { \\")
        body.append("\t\tL65Regs lr_ = {0, 0, 0}; \\")
        for i, kind, loc in assign(params):
            val = c_value(kind, ps[i])
            if loc in ("A", "X", "Y"):
                body.append(f"\t\tlr_.{loc.lower()} = {val}; \\")
            else:
                off = int(loc[2:])
                if kind == "b":
                    body.append(f"\t\tlower_dp({off}, (uint8_t)({val})); \\")
                else:
                    body.append(f"\t\tlower_dp({off}, (uint8_t)({val})); \\")
                    body.append(f"\t\tlower_dp({off + 1}, (uint8_t)(({val}) >> 8)); \\")
        if res == "v":
            body.append(f"\t\tif (lm_ == 1) {{ lower_c_begin(LF_{name}); {call}; lower_c_end(LF_{name}); }} \\")
            body.append(f"\t\tuint32_t lw_ = lower_run(LF_{name}, &lr_); \\")
            body.append(f"\t\tif (lm_ == 1) lower_finish(LF_{name}, 0, lw_, &lr_); \\")
            body.append("\t\treturn; \\")
        else:
            if res == "c":
                pack = "lower_coord_word(lc_c)"
                decl = f"Coord lc_c = {{0, 0}}; uint32_t lc_ = 0; \\"
                cset = f"lc_c = {call}; lc_ = {pack};"
            else:
                decl = "uint32_t lc_ = 0; \\"
                mask = "0xFFu" if res == "b" else "0xFFFFu"
                cset = f"lc_ = (uint32_t)({call}) & {mask};"
            body.append(f"\t\t{decl}")
            body.append(f"\t\tif (lm_ == 1) {{ lower_c_begin(LF_{name}); {cset} lower_c_end(LF_{name}); }} \\")
            body.append(f"\t\tuint32_t lw_ = lower_run(LF_{name}, &lr_); \\")
            body.append(f"\t\tif (lm_ == 1) lower_finish(LF_{name}, lc_, lw_, &lr_); \\")
            body.append("\t\tuint32_t lr2_ = lm_ == 1 ? lc_ : lw_; \\")
            if res == "c":
                body.append("\t\treturn lower_word_coord((uint16_t)lr2_); \\")
            elif res == "b":
                body.append("\t\treturn (uint8_t)lr2_; \\")
            else:
                body.append("\t\treturn (uint16_t)lr2_; \\")
        body.append("\t} \\")
        lines.append(f"#define LH_{name}({', '.join(ps)}) do {{ \\")
        lines += body
        lines.append("} while (0)")
        lines.append("")
    lines += ["#endif", ""]
    lines += table
    return "\n".join(lines)


def emit_s(fns) -> str:
    lines = [
        "* Generated by py/gen_lower_entries.py from lower/entries.txt.",
        "* Entry n is at $4*n: JSR to the routine, RTL to the caller.",
        "",
    ]
    for i, (group, name, res, params) in enumerate(fns):
        regs = ", ".join(f"{loc}=p{j}:{k}" for j, k, loc in assign(params))
        out = {"v": "", "b": " -> A", "w": " -> X", "c": " -> X"}[res]
        lines.append(f"\tjsr\t{LABELS[name]}\t; {i} {group}: ({regs}){out}")
        lines.append("\trtl")
    lines.append("")
    return "\n".join(lines)


def emit_ids(fns) -> str:
    lines = [
        "* Generated by py/gen_lower_entries.py from lower/entries.txt.",
        "* LE_<name>: the offset of the entry stub in lower.bin, for JSL",
        "* from a host that loads lower.bin at the start of a bank.",
        "",
    ]
    for i, (_group, name, _res, _params) in enumerate(fns):
        lines.append(f"LE_{name}\tequ\t${4 * i:04X}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    fns = parse()
    OUT_S.write_text(emit_s(fns), encoding="utf-8")
    OUT_H.write_text(emit_h(fns), encoding="utf-8")
    OUT_IDS.write_text(emit_ids(fns), encoding="utf-8")
    print(f"wrote {OUT_S}, {OUT_H} and {OUT_IDS} ({len(fns)} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
