#!/usr/bin/env python3
"""Arcade tile color banks -> SHR pen maps for the lowered host's tile renderer.

Each arcade tile cell has a color RAM byte; its low 5 bits pick one of 32
4-pen banks in 82s126.4a, and each bank pen indexes the 16-color 82s123.7f.
This writes, per bank, a 16-entry nibble map (tile pixel value -> SHR pen):

  nibbles 0-3   bank pen -> color ROM index -> STABLE_ROM_TO_SHR (gen_palette)
  nibbles 4-15  unchanged (tiles6.bin only uses 0-3)

then, as rows 32-63 (bank + 32), the same bank as a maze: pen 1 as above,
pen 2 (wall fill) to MAZE_FILL_PEN and pen 3 (wall outline) to
MAZE_OUTLINE_PEN, whose colors SetMazePens loads per maze. Plus a flag per
bank that is 1 when its map is the identity, so the host can copy those
cells raw. See docs/ColorMap.md.

Usage:
  python3 py/gen_tile_banks.py
  python3 py/gen_tile_banks.py --palette-rom mspacman/82s126.4a -o iigs/tile_bank_data.s
  python3 py/gen_tile_banks.py --list
"""

from __future__ import annotations

import argparse
import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_COLOR_ROM = ROOT / "mspacman" / "82s123.7f"
DEFAULT_PALETTE_ROM = ROOT / "mspacman" / "82s126.4a"
DEFAULT_OUT = ROOT / "iigs" / "tile_bank_data.s"
NUM_BANKS = 32


def _load_pal():
    path = ROOT / "py" / "gen_palette.py"
    spec = importlib.util.spec_from_file_location("gen_palette", path)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod


def bank_nibble_map(pal, palette_rom: Path, bank: int) -> list[int]:
    rom_pens = pal.load_palette_pens(palette_rom, bank)
    nib = list(range(16))
    for i, ci in enumerate(rom_pens):
        nib[i] = pal.STABLE_ROM_TO_SHR[ci & 15]
    return nib


def maze_nibble_map(pal, palette_rom: Path, bank: int) -> list[int]:
    nib = bank_nibble_map(pal, palette_rom, bank)
    nib[2] = pal.MAZE_FILL_PEN
    nib[3] = pal.MAZE_OUTLINE_PEN
    return nib


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--color-rom", type=Path, default=DEFAULT_COLOR_ROM)
    ap.add_argument("--palette-rom", type=Path, default=DEFAULT_PALETTE_ROM)
    ap.add_argument("-o", "--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--list", action="store_true", help="print every bank's pens and RGBs")
    args = ap.parse_args()

    pal = _load_pal()
    colors = pal.load_prom_colors(args.color_rom)
    maps = [bank_nibble_map(pal, args.palette_rom, b) for b in range(NUM_BANKS)]
    raw = [int(m == list(range(16))) for m in maps]

    if args.list:
        for b in range(NUM_BANKS):
            rom_pens = pal.load_palette_pens(args.palette_rom, b)
            rgb = [colors[p] for p in rom_pens]
            print(f"#{b:02X} rom={rom_pens} shr={maps[b][:4]} raw={raw[b]} rgb={rgb}")

    lines = [
        "*",
        "* Generated by py/gen_tile_banks.py - do not edit by hand",
        "* TileBankPens: 64 rows x 16 bytes, tile nibble -> SHR pen. Row b is",
        "* bank b; row 32+b is bank b as a maze (walls on the maze pens)",
        "* TileBankRaw: 1 when the bank's map is the identity (copy raw)",
        "*",
        "",
        "TileBankPens",
    ]
    for b, m in enumerate(maps):
        lines.append("\tdb\t" + ",".join(f"${p:02X}" for p in m) + f"\t; #{b:02X}")
    for b in range(NUM_BANKS):
        m = maze_nibble_map(pal, args.palette_rom, b)
        lines.append("\tdb\t" + ",".join(f"${p:02X}" for p in m) + f"\t; #{b:02X} maze")
    lines.append("\tdb\t0\t\t; word reads of the last entry")
    lines.append("")
    lines.append("TileBankRaw")
    for row in range(0, NUM_BANKS, 16):
        lines.append("\tdb\t" + ",".join(str(r) for r in raw[row : row + 16]))
    lines.append("")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"wrote {args.out} ({NUM_BANKS} banks, raw: "
          + " ".join(f"#{b:02X}" for b in range(NUM_BANKS) if raw[b]) + ")")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
