#!/usr/bin/env python3
"""Reference generator for ScreenXY row LUT: [y] = y * 160.

Runtime builds the same table at ROW_ADDR ($02/8B00) via InitRowAddr —
Merlin flat binaries put label longs in bank $00, so the table is not
assembled into the code image. This script remains for dumps / checks.

Usage:
  python3 py/gen_row_addr.py -o /tmp/row_addr_data.s
"""

from __future__ import annotations

import argparse
from pathlib import Path

SHR_ROW_BYTES = 160
# Full 8-bit Y index so ScreenXY never walks off the table.
NUM_ROWS = 256


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-o", "--out", type=Path, required=True)
    args = ap.parse_args()

    lines = [
        "*",
        "* Generated by py/gen_row_addr.py — do not edit by hand",
        f"* RowAddr[y] = y * {SHR_ROW_BYTES} (word); y = 0..{NUM_ROWS - 1}",
        "*",
        "",
        "RowAddr",
    ]
    vals = [y * SHR_ROW_BYTES for y in range(NUM_ROWS)]
    per_line = 8
    for i in range(0, NUM_ROWS, per_line):
        chunk = vals[i : i + per_line]
        lines.append("\tdw\t" + ",".join(str(v) for v in chunk))
    lines.append("")
    args.out.write_text("\n".join(lines) + "\n")
    print(f"wrote {args.out} ({NUM_ROWS} words, {NUM_ROWS * 2} bytes)")


if __name__ == "__main__":
    main()
