#!/usr/bin/env python3
"""Generate iigs/seg_work.s — GS/OS OMF work-RAM data segment.

Layout mirrors static $02/8000+ so field offsets match locked #4D/#4E anchors.
Usage: python3 py/gen_seg_work.py
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "iigs" / "seg_work.s"

# (name, addr, size) — size 0 = alias label at addr (no storage)
SYMBOLS = [
    ("TILEMAP", 0x8000, 868),
    ("ACTORS", 0x8400, 96),
    ("RAM4D", 0x8460, 0),
    ("RED_Y", 0x8460, 1),
    ("RED_X", 0x8461, 1),
    ("PINK_Y", 0x8462, 1),
    ("PINK_X", 0x8463, 1),
    ("BLUE_Y", 0x8464, 1),
    ("BLUE_X", 0x8465, 1),
    ("ORANGE_Y", 0x8466, 1),
    ("ORANGE_X", 0x8467, 1),
    ("PAC_Y", 0x8468, 1),
    ("PAC_X", 0x8469, 1),
    ("RED_TILE_Y", 0x846A, 1),
    ("RED_TILE_X", 0x846B, 1),
    ("PINK_TILE_Y", 0x846C, 1),
    ("PINK_TILE_X", 0x846D, 1),
    ("BLUE_TILE_Y", 0x846E, 1),
    ("BLUE_TILE_X", 0x846F, 1),
    ("ORANGE_TILE_Y", 0x8470, 1),
    ("ORANGE_TILE_X", 0x8471, 1),
    ("RED_TILE_DY", 0x8474, 2),
    ("PINK_TILE_DY", 0x8476, 2),
    ("BLUE_TILE_DY", 0x8478, 2),
    ("ORANGE_TILE_DY", 0x847A, 2),
    ("PAC_TILE_DY", 0x847C, 1),
    ("PAC_TILE_DX", 0x847D, 1),
    ("PAC_WANT_DY", 0x8486, 1),
    ("PAC_WANT_DX", 0x8487, 1),
    ("RED_PREV_DIR", 0x8488, 1),
    ("PINK_PREV_DIR", 0x8489, 1),
    ("BLUE_PREV_DIR", 0x848A, 1),
    ("ORANGE_PREV_DIR", 0x848B, 1),
    ("RED_DIR", 0x848C, 1),
    ("PINK_DIR", 0x848D, 1),
    ("BLUE_DIR", 0x848E, 1),
    ("ORANGE_DIR", 0x848F, 1),
    ("PAC_DIR", 0x8490, 1),
    ("PAC_TILE_Y", 0x8499, 1),
    ("PAC_TILE_X", 0x849A, 1),
    ("PATH_BEST_DIR", 0x849B, 1),
    ("PAC_WANT_DIR", 0x849C, 1),
    ("PATH_OPP_DIR", 0x849D, 1),
    ("PATH_CUR_Y", 0x849E, 1),
    ("PATH_CUR_X", 0x849F, 1),
    ("PATH_DST_Y", 0x84A0, 1),
    ("PATH_DST_X", 0x84A1, 1),
    ("PATH_TMP_Y", 0x84A2, 1),
    ("PATH_TMP_X", 0x84A3, 1),
    ("PATH_MIN_LO", 0x84A4, 1),
    ("SPD_PAC_NORM", 0x84A6, 4),
    ("SPD_PAC_ENERG", 0x84AA, 4),
    ("SPD_RED_NORM", 0x84B6, 4),
    ("GHOST_ORIENT_TBL", 0x84E6, 14),
    ("GHOST_HOME_MOVE", 0x84F4, 1),
    ("LEAVE_HOME_UNITS", 0x84F5, 2),
    ("LEAVE_HOME_IDLE", 0x84F7, 2),
    ("PAC_MOVE_DELAY", 0x84FD, 1),
    ("PILLS_SINCE_PAC_MOVE", 0x84FE, 1),
    ("PILLS_AFTER_DEATH", 0x84FF, 1),
    ("RED_SUBSTATE", 0x8500, 1),
    ("PINK_SUBSTATE", 0x8501, 1),
    ("BLUE_SUBSTATE", 0x8502, 1),
    ("ORANGE_SUBSTATE", 0x8503, 1),
    ("POWER_PILL_ACT", 0x8506, 1),
    ("RED_FRIGHT", 0x8507, 1),
    ("PINK_FRIGHT", 0x8508, 1),
    ("BLUE_FRIGHT", 0x8509, 1),
    ("ORANGE_FRIGHT", 0x850A, 1),
    ("RED_STATE", 0x850B, 1),
    ("PINK_STATE", 0x850C, 1),
    ("BLUE_STATE", 0x850D, 1),
    ("ORANGE_STATE", 0x850E, 1),
    ("RED_REVERSE", 0x8511, 1),
    ("PINK_REVERSE", 0x8512, 1),
    ("BLUE_REVERSE", 0x8513, 1),
    ("ORANGE_REVERSE", 0x8514, 1),
    ("PINK_EXIT_LIMIT", 0x8518, 1),
    ("BLUE_EXIT_LIMIT", 0x8519, 1),
    ("ORANGE_EXIT_LIMIT", 0x851A, 1),
    ("FRIGHT_TIME", 0x851D, 2),
    ("GHOST_ORIENT_IDX", 0x8521, 1),
    ("GHOST_ORIENT_CNT", 0x8522, 2),
    ("PATH_TRY_DIR", 0x8527, 1),
    ("FRIGHT_FLASH_CNT", 0x8528, 1),
    ("FRIGHT_FLASH_PHASE", 0x8529, 1),
    ("FRIGHT_TIMER", 0x852B, 2),
    ("RAM4E", 0x8560, 0),
    ("GAME_MODE", 0x8560, 1),
    ("LEVEL_STATE", 0x8564, 1),
    ("DOTS_EATEN", 0x856E, 1),
    ("PINK_EXIT_CNT", 0x856F, 1),
    ("BLUE_EXIT_CNT", 0x8570, 1),
    ("ORANGE_EXIT_CNT", 0x8571, 1),
    ("DIED_THIS_LEVEL", 0x8572, 1),
    ("LEVEL_NUMBER", 0x8573, 1),
    ("LIVES_REAL", 0x8575, 1),
    ("STICK_IN0", 0x8590, 1),
    ("FRUIT_ACTIVE", 0x8591, 1),
    ("FRUIT_PIXEL_Y", 0x8592, 1),
    ("FRUIT_PIXEL_X", 0x8593, 1),
    ("DEATH_TIMER", 0x8594, 1),
    ("CLEAR_TIMER", 0x8595, 1),
    ("FRUIT_TIMER", 0x8596, 1),
    ("FRUIT_SPAWNED", 0x8597, 1),
    ("DIRTY_COUNT", 0x8800, 2),
    ("DIRTY_LIST", 0x8802, 0xFE),
    ("FRAME_COUNT", 0x8900, 2),
    ("EAT_INDEX", 0x8902, 2),
    ("DEMO_FREEZE", 0x8904, 1),
    ("POWER_FLASH_CNT", 0x8906, 1),
    ("SCORE_LO", 0x8908, 1),
    ("SCORE_MID", 0x8909, 1),
    ("SCORE_HI", 0x890A, 1),
    ("HISCORE_LO", 0x890B, 1),
    ("HISCORE_MID", 0x890C, 1),
    ("HISCORE_HI", 0x890D, 1),
    ("LIVES", 0x890E, 1),
    ("LEVEL", 0x890F, 1),
    ("ROW_ADDR", 0x8B00, 512),
    ("ROW_BCK", 0x8D00, 512),
]


def main() -> None:
    ents = sorted({n for n, _, _ in SYMBOLS})
    lines = [
        "*",
        "* GS/OS OMF work-RAM segment (generated by py/gen_seg_work.py).",
        "* Mirrors static $02/8000+ layout; loader relocates >SYMBOL refs.",
        "*",
        "\trel",
    ]
    for i in range(0, len(ents), 6):
        lines.append("\tent\t" + ",".join(ents[i : i + 6]))
    lines.append("")

    at: dict[int, list[tuple[str, int]]] = defaultdict(list)
    for name, addr, size in SYMBOLS:
        at[addr].append((name, size))

    pos = 0x8000
    for addr in sorted(at):
        if addr > pos:
            lines.append(f"\tds\t${addr - pos:X}\t\t; pad to ${addr:04X}")
            pos = addr
        aliases = [(n, s) for n, s in at[addr] if s == 0]
        storage = [(n, s) for n, s in at[addr] if s != 0]
        for n, _ in aliases:
            lines.append(f"{n}")
        if not storage:
            continue
        # One storage reservation; extra names at same addr are aliases above
        name, size = storage[0]
        for n, s in storage[1:]:
            if s != size:
                raise SystemExit(f"size conflict at ${addr:04X}: {name}/{n}")
            lines.append(f"{n}")
        lines.append(f"{name}\tds\t{size}")
        pos = addr + size

    lines.append("")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} (work end ${pos:04X}, {len(ents)} symbols)")


if __name__ == "__main__":
    main()
