#!/usr/bin/env python3
"""Generate iigs/seg_work.s — GS/OS OMF work-RAM data segment.

Layout mirrors static $02/A000+ so field offsets match locked #4D/#4E anchors.
Usage: python3 py/gen_seg_work.py
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "iigs" / "seg_work.s"

# (name, addr, size) — size 0 = alias label at addr (no storage)
SYMBOLS = [
    ("TILEMAP", 0xA000, 868),
    ("ACTORS", 0xA400, 96),
    ("RAM4D", 0xA460, 0),
    ("RED_Y", 0xA460, 1),
    ("RED_X", 0xA461, 1),
    ("PINK_Y", 0xA462, 1),
    ("PINK_X", 0xA463, 1),
    ("BLUE_Y", 0xA464, 1),
    ("BLUE_X", 0xA465, 1),
    ("ORANGE_Y", 0xA466, 1),
    ("ORANGE_X", 0xA467, 1),
    ("PAC_Y", 0xA468, 1),
    ("PAC_X", 0xA469, 1),
    ("RED_TILE_Y", 0xA46A, 1),
    ("RED_TILE_X", 0xA46B, 1),
    ("PINK_TILE_Y", 0xA46C, 1),
    ("PINK_TILE_X", 0xA46D, 1),
    ("BLUE_TILE_Y", 0xA46E, 1),
    ("BLUE_TILE_X", 0xA46F, 1),
    ("ORANGE_TILE_Y", 0xA470, 1),
    ("ORANGE_TILE_X", 0xA471, 1),
    ("RED_TILE_DY", 0xA474, 2),
    ("PINK_TILE_DY", 0xA476, 2),
    ("BLUE_TILE_DY", 0xA478, 2),
    ("ORANGE_TILE_DY", 0xA47A, 2),
    ("PAC_TILE_DY", 0xA47C, 1),
    ("PAC_TILE_DX", 0xA47D, 1),
    ("PAC_WANT_DY", 0xA486, 1),
    ("PAC_WANT_DX", 0xA487, 1),
    ("RED_PREV_DIR", 0xA488, 1),
    ("PINK_PREV_DIR", 0xA489, 1),
    ("BLUE_PREV_DIR", 0xA48A, 1),
    ("ORANGE_PREV_DIR", 0xA48B, 1),
    ("RED_DIR", 0xA48C, 1),
    ("PINK_DIR", 0xA48D, 1),
    ("BLUE_DIR", 0xA48E, 1),
    ("ORANGE_DIR", 0xA48F, 1),
    ("PAC_DIR", 0xA490, 1),
    ("PAC_TILE_Y", 0xA499, 1),
    ("PAC_TILE_X", 0xA49A, 1),
    ("PATH_BEST_DIR", 0xA49B, 1),
    ("PAC_WANT_DIR", 0xA49C, 1),
    ("PATH_OPP_DIR", 0xA49D, 1),
    ("PATH_CUR_Y", 0xA49E, 1),
    ("PATH_CUR_X", 0xA49F, 1),
    ("PATH_DST_Y", 0xA4A0, 1),
    ("PATH_DST_X", 0xA4A1, 1),
    ("PATH_TMP_Y", 0xA4A2, 1),
    ("PATH_TMP_X", 0xA4A3, 1),
    ("PATH_MIN_LO", 0xA4A4, 1),
    ("SPD_PAC_NORM", 0xA4A6, 4),
    ("SPD_PAC_ENERG", 0xA4AA, 4),
    ("SPD_RED_NORM", 0xA4B6, 4),
    ("SPD_RED_BLUE", 0xA4BA, 4),  # == #4D5A fright (level1: shared ghost blue pat)
    ("GHOST_ORIENT_TBL", 0xA4E6, 14),
    ("GHOST_HOME_MOVE", 0xA4F4, 1),
    ("LEAVE_HOME_UNITS", 0xA4F5, 2),
    ("LEAVE_HOME_IDLE", 0xA4F7, 2),
    ("PAC_MOVE_DELAY", 0xA4FD, 1),
    ("PILLS_SINCE_PAC_MOVE", 0xA4FE, 1),
    ("PILLS_AFTER_DEATH", 0xA4FF, 1),
    ("RED_SUBSTATE", 0xA500, 1),
    ("PINK_SUBSTATE", 0xA501, 1),
    ("BLUE_SUBSTATE", 0xA502, 1),
    ("ORANGE_SUBSTATE", 0xA503, 1),
    ("GHOSTS_KILLED_PENDING", 0xA504, 1),  # == #4DA4
    ("EAT_FREEZE_TIMER", 0xA505, 1),  # soft: RST#30 $4A stand-in
    ("POWER_PILL_ACT", 0xA506, 1),
    ("RED_FRIGHT", 0xA507, 1),
    ("PINK_FRIGHT", 0xA508, 1),
    ("BLUE_FRIGHT", 0xA509, 1),
    ("ORANGE_FRIGHT", 0xA50A, 1),
    ("RED_STATE", 0xA50B, 1),
    ("PINK_STATE", 0xA50C, 1),
    ("BLUE_STATE", 0xA50D, 1),
    ("ORANGE_STATE", 0xA50E, 1),
    ("RED_REVERSE", 0xA511, 1),
    ("PINK_REVERSE", 0xA512, 1),
    ("BLUE_REVERSE", 0xA513, 1),
    ("ORANGE_REVERSE", 0xA514, 1),
    ("PINK_EXIT_LIMIT", 0xA518, 1),
    ("BLUE_EXIT_LIMIT", 0xA519, 1),
    ("ORANGE_EXIT_LIMIT", 0xA51A, 1),
    ("FRIGHT_TIME", 0xA51D, 2),
    ("GHOST_ORIENT_IDX", 0xA521, 1),
    ("GHOST_ORIENT_CNT", 0xA522, 2),
    ("PATH_TRY_DIR", 0xA527, 1),
    ("FRIGHT_FLASH_CNT", 0xA528, 1),
    ("FRIGHT_FLASH_PHASE", 0xA529, 1),
    ("KILL_GHOST_STATE", 0xA52A, 1),  # soft (== arcade #4DAB; RED_STATE occupies that slot)
    ("FRIGHT_TIMER", 0xA52B, 2),
    ("GHOSTS_KILLED_COUNT", 0xA530, 1),  # == #4DD0
    ("KILLED_GHOST_ANIM", 0xA531, 1),  # == #4DD1

    ("RAM4E", 0xA560, 0),
    ("GAME_MODE", 0xA560, 1),
    ("LEVEL_STATE", 0xA564, 1),
    ("DOTS_EATEN", 0xA56E, 1),
    ("PINK_EXIT_CNT", 0xA56F, 1),
    ("BLUE_EXIT_CNT", 0xA570, 1),
    ("ORANGE_EXIT_CNT", 0xA571, 1),
    ("DIED_THIS_LEVEL", 0xA572, 1),
    ("LEVEL_NUMBER", 0xA573, 1),
    ("LIVES_REAL", 0xA575, 1),
    ("STICK_IN0", 0xA590, 1),
    ("FRUIT_ACTIVE", 0xA591, 1),
    ("FRUIT_PIXEL_Y", 0xA592, 1),
    ("FRUIT_PIXEL_X", 0xA593, 1),
    ("DEATH_TIMER", 0xA594, 1),
    ("CLEAR_TIMER", 0xA595, 1),
    ("FRUIT_TIMER", 0xA596, 1),
    ("FRUIT_SPAWNED", 0xA597, 1),
    ("DIRTY_COUNT", 0xA800, 2),
    ("DIRTY_LIST", 0xA802, 0xFE),
    ("FRAME_COUNT", 0xA900, 2),
    ("EAT_INDEX", 0xA902, 2),
    ("DEMO_FREEZE", 0xA904, 1),
    ("POWER_FLASH_CNT", 0xA906, 1),
    ("SCORE_LO", 0xA908, 1),
    ("SCORE_MID", 0xA909, 1),
    ("SCORE_HI", 0xA90A, 1),
    ("HISCORE_LO", 0xA90B, 1),
    ("HISCORE_MID", 0xA90C, 1),
    ("HISCORE_HI", 0xA90D, 1),
    ("LIVES", 0xA90E, 1),
    ("LEVEL", 0xA90F, 1),
    ("ROW_ADDR", 0xAB00, 512),
    ("ROW_BCK", 0xAD00, 512),
]


def main() -> None:
    ents = sorted({n for n, _, _ in SYMBOLS})
    lines = [
        "*",
        "* GS/OS OMF work-RAM segment (generated by py/gen_seg_work.py).",
        "* Mirrors static $02/A000+ layout; loader relocates >SYMBOL refs.",
        "*",
        "\trel",
    ]
    for i in range(0, len(ents), 6):
        lines.append("\tent\t" + ",".join(ents[i : i + 6]))
    lines.append("")

    at: dict[int, list[tuple[str, int]]] = defaultdict(list)
    for name, addr, size in SYMBOLS:
        at[addr].append((name, size))

    pos = 0xA000
    for addr in sorted(at):
        if addr > pos:
            lines.append(f"\tds\t${addr - pos:X}\t\t; pad to ${addr:04X}")
            pos = addr
        aliases = [(n, s) for n, s in at[addr] if s == 0]
        storage = [(n, s) for n, s in at[addr] if s != 0]
        for n, _ in aliases:
            lines.append(f"{n}")
        if not storage:
            continue
        # One storage reservation; extra names at same addr are aliases above
        name, size = storage[0]
        for n, s in storage[1:]:
            if s != size:
                raise SystemExit(f"size conflict at ${addr:04X}: {name}/{n}")
            lines.append(f"{n}")
        lines.append(f"{name}\tds\t{size}")
        pos = addr + size

    lines.append("")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} (work end ${pos:04X}, {len(ents)} symbols)")


if __name__ == "__main__":
    main()
