#!/usr/bin/env python3
"""Emit compiled 65816 masked blits for Ms. Pac and Pac-Man walk frames.

Ms. Pac: 4 directions × 3 mouths × even/odd. Arcade source is the walk
patch #869C–#86EA. Sprite index is code & $3F; bits 7/6 are X/Y flip.
Pac-Man (the act intermissions' Otto) follows in the same table at
ACT_SPR 12..23: wide / partial / closed, from sprites $1B $19 $32
(east), $1A $2E $32 (south), and the H / V flips of those.

Art is the even 14×12 cell from build/gfx sprites14x12.bin (make gfx);
color bank #09 prebaked into §2 SHR pens.

  index = (ACT_SPR)*2 + (X & 1)  → MsPacBlitTable
  ACT_SPR = dir*3 + mouth, plus 12 for Pac-Man

Adjacent opaque bytes are coalesced into 16-bit ops by py/blit_emit.py.

Usage:
  python3 py/gen_compiled_mspac.py
  python3 py/gen_compiled_mspac.py --gfx build/gfx -o iigs/compiled_mspac.s
  python3 py/gen_compiled_mspac.py --no-word16    # 8-bit only, for A/B
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from blit_emit import BlitStats, check_equivalence, emit_blit  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_GFX = ROOT / "build" / "gfx"
DEFAULT_PALETTE_ROM = ROOT / "mspacman-orig" / "82s126.4a"
DEFAULT_OUT = ROOT / "iigs" / "compiled_mspac.s"

COLOR_BANK = 0x09

# (dir, mouth, rom_index, h_flip, v_flip, label)
# Mouth slots match harness phase tables (E/N: 0,1,2,1; S/W: 0,1,0,2).
FRAMES = (
    (0, 0, 0x2F, False, False, "E0"),
    (0, 1, 0x37, False, False, "E1"),
    (0, 2, 0x2D, False, False, "E2"),
    (1, 0, 0x34, False, False, "S0"),
    (1, 1, 0x31, False, False, "S1"),
    (1, 2, 0x33, False, False, "S2"),
    (2, 0, 0x35, False, False, "W0"),
    (2, 1, 0x2D, True, False, "W1"),
    (2, 2, 0x2F, True, False, "W2"),
    (3, 0, 0x33, True, True, "N0"),
    (3, 1, 0x36, False, False, "N1"),
    (3, 2, 0x31, True, True, "N2"),
)

# Pac-Man. ACT_SPR = 12 + dir*3 + mouth. Mouth 0 wide, 1 partial, 2 closed.
# The closed mouth is the circle $32 in every direction (one blit, four slots).
PAC_BASE = 12
PAC_FRAMES = (
    (0, 0, 0x1B, False, False, "E0"),
    (0, 1, 0x19, False, False, "E1"),
    (0, 2, 0x32, False, False, "E2"),
    (1, 0, 0x1A, False, False, "S0"),
    (1, 1, 0x2E, False, False, "S1"),
    (1, 2, 0x32, False, False, "S2"),
    (2, 0, 0x1B, True, False, "W0"),
    (2, 1, 0x19, True, False, "W1"),
    (2, 2, 0x32, True, False, "W2"),
    (3, 0, 0x1A, False, True, "N0"),
    (3, 1, 0x2E, False, True, "N1"),
    (3, 2, 0x32, False, True, "N2"),
)


def _load_gfx():
    path = ROOT / "py" / "gen_shr_gfx.py"
    spec = importlib.util.spec_from_file_location("gen_shr_gfx", path)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod


def _load_pal():
    path = ROOT / "py" / "gen_palette.py"
    spec = importlib.util.spec_from_file_location("gen_palette", path)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod


def bank_to_shr_map(palette_rom: Path, bank: int) -> tuple[int, int, int, int]:
    pal = _load_pal()
    rom_pens = pal.load_palette_pens(palette_rom, bank)
    return tuple(pal.STABLE_ROM_TO_SHR[p & 15] for p in rom_pens)  # type: ignore[return-value]


def remap_img(img: list[list[int]], shr_map: tuple[int, ...]) -> list[list[int]]:
    return [[shr_map[p & 3] for p in row] for row in img]


def flip_h(img: list[list[int]]) -> list[list[int]]:
    return [row[::-1] for row in img]


def build_cell(gfx, sheet: bytes, spr_code: int, h_flip: bool, v_flip: bool, shr_map):
    art = gfx.unpack_sprite_arcade(sheet, spr_code)
    if v_flip:
        art = gfx.flip_v(art)
    if h_flip:
        art = flip_h(art)
    even = remap_img(art, shr_map)
    odd = gfx.shift_odd_cell(even)
    return (
        gfx.pack_4bpp_rows(even),
        bytes(gfx.pack_4bpp_rows(gfx.mask_from_pens(even))),
        gfx.pack_4bpp_rows(odd),
        bytes(gfx.pack_4bpp_rows(gfx.mask_from_pens(odd))),
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--gfx", type=Path, default=DEFAULT_GFX)
    ap.add_argument("--palette-rom", type=Path, default=DEFAULT_PALETTE_ROM)
    ap.add_argument("-o", "--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument(
        "--no-word16",
        dest="word16",
        action="store_false",
        help="emit 8-bit ops only (pre-optimization output, for A/B)",
    )
    args = ap.parse_args()

    sheet_path = args.gfx / "sprites14x12.bin"
    if not sheet_path.is_file():
        raise SystemExit(f"missing {sheet_path} (run make gfx)")

    gfx = _load_gfx()
    sheet = sheet_path.read_bytes()
    shr_map = bank_to_shr_map(args.palette_rom, COLOR_BANK)

    lines: list[str] = [
        "*",
        "* Generated by py/gen_compiled_mspac.py - do not edit by hand",
        "* MsPacBlitTable: ACT_SPR*2 + (X&1) -> abs addresses",
        "* ACT_SPR 0..11 Ms. Pac, 12..23 Pac-Man (dir*3+mouth)",
        "* each blit Y=SHR offset, DBR=$01",
        "*",
        "",
        "MsPacBlitGo",
        "* X = index*2 into MsPacBlitTable; JMP so blit RTS returns to caller.",
        "\tjmp\t(MsPacBlitTable,x)",
        "",
        "MsPacBlitTable",
    ]

    labels: list[str] = []
    for dir_, mouth, spr_code, h_flip, v_flip, name in FRAMES:
        for parity, tag in enumerate(("E", "O")):
            lab = f"MP{dir_}{mouth}_{tag}"
            labels.append(lab)
            flips = ("", "H", "V", "HV")[int(h_flip) + 2 * int(v_flip)]
            lines.append(
                f"\tda\t{lab}\t; {name} spr=${spr_code:02X}"
                f"{('+' + flips) if flips else ''} "
                f"{'odd' if parity else 'even'}"
            )

    for i, (dir_, mouth, *_) in enumerate(PAC_FRAMES):
        if i != dir_ * 3 + mouth:
            raise SystemExit(f"PAC_FRAMES[{i}] is not dir*3+mouth")
    pac_cells = [
        build_cell(gfx, sheet, spr_code, h_flip, v_flip, shr_map)
        for _, _, spr_code, h_flip, v_flip, _ in PAC_FRAMES
    ]
    # Identical art (the closed circle under every flip) shares one blit.
    pac_shared: dict[tuple[bytes, ...], tuple[str, str]] = {}
    pac_unique: list[tuple[str, str, tuple, tuple]] = []
    for spec, cells in zip(PAC_FRAMES, pac_cells):
        dir_, mouth, spr_code, h_flip, v_flip, name = spec
        key = cells
        if key not in pac_shared:
            lab_e, lab_o = f"PM{dir_}{mouth}_E", f"PM{dir_}{mouth}_O"
            pac_shared[key] = (lab_e, lab_o)
            pac_unique.append((lab_e, lab_o, spec, cells))
        lab_e, lab_o = pac_shared[key]
        flips = ("", "H", "V", "HV")[int(h_flip) + 2 * int(v_flip)]
        note = f"spr=${spr_code:02X}{('+' + flips) if flips else ''}"
        lines.append(f"\tda\t{lab_e}\t; P{name} {note} even")
        lines.append(f"\tda\t{lab_o}\t; P{name} {note} odd")
        labels.extend((lab_e, lab_o))

    lines.append("")
    body: list[str] = []
    stats = BlitStats()

    for dir_, mouth, spr_code, h_flip, v_flip, name in FRAMES:
        even_s, even_m, odd_s, odd_m = build_cell(
            gfx, sheet, spr_code, h_flip, v_flip, shr_map
        )
        for tag, spr, msk in (("E", even_s, even_m), ("O", odd_s, odd_m)):
            lab = f"MP{dir_}{mouth}_{tag}"
            if args.word16:
                check_equivalence(bytes(spr), msk)
            body.extend(emit_blit(lab, bytes(spr), msk, stats, word16=args.word16))
            flips = ("", "H", "V", "HV")[int(h_flip) + 2 * int(v_flip)]
            print(
                f"  {lab}: {name} spr=${spr_code:02X}"
                f"{('+' + flips) if flips else ''} map={shr_map}"
            )

    for lab_e, lab_o, spec, cells in pac_unique:
        dir_, mouth, spr_code, h_flip, v_flip, name = spec
        even_s, even_m, odd_s, odd_m = cells
        flips = ("", "H", "V", "HV")[int(h_flip) + 2 * int(v_flip)]
        for lab, spr, msk in ((lab_e, even_s, even_m), (lab_o, odd_s, odd_m)):
            if args.word16:
                check_equivalence(bytes(spr), msk)
            body.extend(emit_blit(lab, bytes(spr), msk, stats, word16=args.word16))
        print(
            f"  {lab_e}/{lab_o}: P{name} spr=${spr_code:02X}"
            f"{('+' + flips) if flips else ''} map={shr_map}"
        )

    lines.extend(body)
    lines.append("\tmx\t%00")
    lines.append("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"wrote {args.out} ({len(labels)} blits, {stats})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
