#!/usr/bin/env python3
"""Emit compiled 65816 masked blits for point sprites.

Two sets, one table. Ghost slots stay 0–3 so the eat-ghost path is unchanged:

  Ghost $28–$2B (j_1235: 200/400/800/1600)
      (ACT_SPR & 3)*2 + (X & 1)              → slots 0–3

  Fruit $08–$0F (eat_fruit: fruit_points+2 → 100/200/500/700/1000/2000/5000)
      (4 + (ACT_SPR & 7))*2 + (X & 1)        → slots 4–11

Art is the even 14×12 cell from build/gfx sprites14x12.bin (make gfx).

Usage:
  python3 py/gen_compiled_points.py
  python3 py/gen_compiled_points.py --gfx build/gfx -o iigs/compiled_points.s
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from blit_emit import BlitStats, check_equivalence, emit_blit  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_GFX = ROOT / "build" / "gfx"
DEFAULT_OUT = ROOT / "iigs" / "compiled_points.s"

# Ghost first (slots 0–3), then fruit (slots 4–11). Bank is unused:
# opaque ink is forced to SHR pen 1 (white), same as ColorMap.md.
POINTS = (
    (0x28, "Pts200"),
    (0x29, "Pts400"),
    (0x2A, "Pts800"),
    (0x2B, "Pts1600"),
    (0x08, "Pts100"),
    (0x09, "Pts200f"),
    (0x0A, "Pts500"),
    (0x0B, "Pts700"),
    (0x0C, "Pts1000"),
    (0x0D, "Pts2000"),
    (0x0E, "Pts5000"),
    (0x0F, "Pts5000J"),  # Junior; unused in Ms. Pac, same 5000 as banana
)
# Arcade j_1235 uses color bank $18. PROM→§2 would map opaque ink to
# SHR pen 9 (cyan) — unreadable. Bake eye-white pen 1 ($0DDF) instead.
POINTS_SHR_MAP = (0, 1, 1, 1)


def _load_gfx():
    path = ROOT / "py" / "gen_shr_gfx.py"
    spec = importlib.util.spec_from_file_location("gen_shr_gfx", path)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod


def remap_img(img: list[list[int]], shr_map: tuple[int, ...]) -> list[list[int]]:
    return [[shr_map[p & 3] for p in row] for row in img]


def build_cell(gfx, sheet: bytes, spr_code: int, shr_map: tuple[int, ...]):
    even = remap_img(gfx.unpack_sprite_arcade(sheet, spr_code), shr_map)
    odd = gfx.shift_odd_cell(even)
    return (
        gfx.pack_4bpp_rows(even),
        bytes(gfx.pack_4bpp_rows(gfx.mask_from_pens(even))),
        gfx.pack_4bpp_rows(odd),
        bytes(gfx.pack_4bpp_rows(gfx.mask_from_pens(odd))),
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--gfx", type=Path, default=DEFAULT_GFX)
    ap.add_argument("-o", "--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument(
        "--no-word16",
        dest="word16",
        action="store_false",
        help="emit 8-bit ops only",
    )
    args = ap.parse_args()

    sheet_path = args.gfx / "sprites14x12.bin"
    if not sheet_path.is_file():
        raise SystemExit(f"missing {sheet_path} (run make gfx)")

    gfx = _load_gfx()
    sheet = sheet_path.read_bytes()
    shr_map = POINTS_SHR_MAP

    lines: list[str] = [
        "*",
        "* Generated by py/gen_compiled_points.py - do not edit by hand",
        "* Ghost $28-$2B: (ACT_SPR&3)*2 + (X&1) -> slots 0-3",
        "* Fruit $08-$0F: (4+(ACT_SPR&7))*2 + (X&1) -> slots 4-11",
        "* Opaque ink forced to SHR pen 1 (white).",
        "*",
        "",
        "PointsBlitGo",
        "* X = index*2 into PointsBlitTable; JMP so blit RTS returns to caller.",
        "\tjmp\t(PointsBlitTable,x)",
        "",
        "PointsBlitTable",
    ]

    labels: list[str] = []
    for fi, (spr_code, name) in enumerate(POINTS):
        for parity, tag in enumerate(("E", "O")):
            lab = f"CP{fi}_{tag}"
            labels.append(lab)
            lines.append(
                f"\tda\t{lab}\t; {name} spr=${spr_code:02X} white "
                f"{'odd' if parity else 'even'}"
            )

    lines.append("")
    body: list[str] = []
    stats = BlitStats()

    for fi, (spr_code, name) in enumerate(POINTS):
        even_s, even_m, odd_s, odd_m = build_cell(gfx, sheet, spr_code, shr_map)
        for tag, spr, msk in (("E", even_s, even_m), ("O", odd_s, odd_m)):
            lab = f"CP{fi}_{tag}"
            if args.word16:
                check_equivalence(bytes(spr), msk)
            body.extend(emit_blit(lab, bytes(spr), msk, stats, word16=args.word16))
            print(f"  {lab}: {name} map={shr_map}")

    lines.extend(body)
    lines.append("\tmx\t%00")
    lines.append("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"wrote {args.out} ({len(labels)} blits, {stats})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
