#!/usr/bin/env python3
"""Emit unrolled masked blit from pre-colored ghost work buffers (Merlin32).

On entry: X = work base (sprite at +0..83, mask at +84..167), Y = SHR offset.
Body color is already baked into the sprite bytes — no RemapBodyByte.

Usage:
  python3 py/gen_ghost_work_blit.py -o iigs/ghost_work_blit.s
"""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = ROOT / "iigs" / "ghost_work_blit.s"
ROWS = 12
COLS = 7
MASK_OFF = 84
SHR_BASE = 0x2000  # must be hex — decimal 2000 is $07D0 (corrupts / can hit I/O)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-o", "--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args()

    lines = [
        "*",
        "* Generated by py/gen_ghost_work_blit.py — do not edit by hand",
        "* MaskedBlitWork: X=work base (spr+0, mask+84), Y=SHR offset",
        "*",
        "",
        "MaskedBlitWork",
        "\tphp",
        "\tsep\t#$20",
    ]
    for row in range(ROWS):
        scr = row * 160
        base = row * COLS
        lines.append(f"* row {row}")
        for col in range(COLS):
            o = base + col
            abs_addr = SHR_BASE + scr + col
            lines.append(f"\tlda\t>BANK2+{MASK_OFF + o},x")
            lines.append("\teor\t#$FF")
            lines.append(f"\tand\t${abs_addr:04X},y")
            lines.append("\tsta\t>R_TMP")
            lines.append(f"\tlda\t>BANK2+{o},x")
            lines.append(f"\tand\t>BANK2+{MASK_OFF + o},x")
            lines.append("\tora\t>R_TMP")
            lines.append(f"\tsta\t${abs_addr:04X},y")
    # Restore Merlin assemble-time MX: sep #$20 above would otherwise leave
    # following PUT files assembling 8-bit immediates (ADC #n eats the RTS).
    lines += ["\tplp", "\trts", "\tmx\t%00", ""]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {args.out} ({ROWS * COLS} byte blits unrolled)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
