#!/usr/bin/env python3
"""Emit compiled 65816 masked blits for eat-ghost point sprites $28–$2B.

Arcade j_1235: ghost sprite ← $27+count (200/400/800/1600), color bank $18.
Prebakes bank $18 into §2 SHR pens. Index:

  (ACT_SPR & 3)*2 + (X & 1)  → PointsBlitTable

Usage:
  python3 py/gen_compiled_points.py
  python3 py/gen_compiled_points.py --sprites mspacman-orig/5f -o iigs/compiled_points.s
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from blit_emit import BlitStats, check_equivalence, emit_blit  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SPRITE_ROM = ROOT / "mspacman-orig" / "5f"
DEFAULT_OUT = ROOT / "iigs" / "compiled_points.s"

# (sprite ROM code, name) — bank always $18
POINTS = (
    (0x28, "Pts200"),
    (0x29, "Pts400"),
    (0x2A, "Pts800"),
    (0x2B, "Pts1600"),
)
# Arcade j_1235 uses color bank $18. PROM→§2 would map opaque ink to
# SHR pen 9 (cyan) — unreadable. Bake eye-white pen 1 ($0DDF) instead.
POINTS_SHR_MAP = (0, 1, 1, 1)


def _load_gfx():
    path = ROOT / "py" / "gen_shr_gfx.py"
    spec = importlib.util.spec_from_file_location("gen_shr_gfx", path)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod


def remap_img(img: list[list[int]], shr_map: tuple[int, ...]) -> list[list[int]]:
    return [[shr_map[p & 3] for p in row] for row in img]


def build_cell(gfx, rom: bytes, spr_code: int, shr_map: tuple[int, ...]):
    raw = gfx.decode_sprite(rom, spr_code)
    art = gfx.area_resample(gfx.upright_sprite(raw), gfx.SPRITE_ART, gfx.SPRITE_ART)
    even = remap_img(gfx.pad_sprite_14x12(art), shr_map)
    odd = gfx.shift_odd_cell(even)
    return (
        gfx.pack_4bpp_rows(even),
        bytes(gfx.pack_4bpp_rows(gfx.mask_from_pens(even))),
        gfx.pack_4bpp_rows(odd),
        bytes(gfx.pack_4bpp_rows(gfx.mask_from_pens(odd))),
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--sprites", type=Path, default=DEFAULT_SPRITE_ROM)
    ap.add_argument("-o", "--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument(
        "--no-word16",
        dest="word16",
        action="store_false",
        help="emit 8-bit ops only",
    )
    args = ap.parse_args()

    if not args.sprites.is_file():
        raise SystemExit(f"missing sprite ROM {args.sprites}")

    gfx = _load_gfx()
    rom = args.sprites.read_bytes()
    shr_map = POINTS_SHR_MAP

    lines: list[str] = [
        "*",
        "* Generated by py/gen_compiled_points.py - do not edit by hand",
        "* PointsBlitTable: (ACT_SPR&3)*2 + (X&1) -> abs addresses",
        "* Sprites $28-$2B; opaque ink forced to SHR pen 1 (white).",
        "*",
        "",
        "PointsBlitGo",
        "* X = index*2 into PointsBlitTable; JMP so blit RTS returns to caller.",
        "\tjmp\t(PointsBlitTable,x)",
        "",
        "PointsBlitTable",
    ]

    labels: list[str] = []
    for fi, (spr_code, name) in enumerate(POINTS):
        for parity, tag in enumerate(("E", "O")):
            lab = f"CP{fi}_{tag}"
            labels.append(lab)
            lines.append(
                f"\tda\t{lab}\t; {name} spr=${spr_code:02X} white "
                f"{'odd' if parity else 'even'}"
            )

    lines.append("")
    body: list[str] = []
    stats = BlitStats()

    for fi, (spr_code, name) in enumerate(POINTS):
        even_s, even_m, odd_s, odd_m = build_cell(gfx, rom, spr_code, shr_map)
        for tag, spr, msk in (("E", even_s, even_m), ("O", odd_s, odd_m)):
            lab = f"CP{fi}_{tag}"
            if args.word16:
                check_equivalence(bytes(spr), msk)
            body.extend(emit_blit(lab, bytes(spr), msk, stats, word16=args.word16))
            print(f"  {lab}: {name} map={shr_map}")

    lines.extend(body)
    lines.append("\tmx\t%00")
    lines.append("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"wrote {args.out} ({len(labels)} blits, {stats})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
