#!/usr/bin/env python3
"""Emit compiled 65816 masked blits for Ms. Pac fruit sprites $00–$07.

Decodes 5f ROM (upright + 16→12 + pad 14×12 + odd shift), prebakes each
fruit's arcade color bank from table #879D into §2 SHR pens, and writes
Merlin32 routines:

  index = (ACT_SPR & 7)*2 + (X & 1)  → FruitBlitTable

Junior bank #00 is all-black in the PROM; override to #09 so it is visible.

Usage:
  python3 py/gen_compiled_fruits.py
  python3 py/gen_compiled_fruits.py --sprites mspacman-orig/5f -o iigs/compiled_fruits.s
"""

from __future__ import annotations

import argparse
import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SPRITE_ROM = ROOT / "mspacman-orig" / "5f"
DEFAULT_COLOR_ROM = ROOT / "mspacman-orig" / "82s123.7f"
DEFAULT_PALETTE_ROM = ROOT / "mspacman-orig" / "82s126.4a"
DEFAULT_OUT = ROOT / "iigs" / "compiled_fruits.s"

SPR_BYTES = 84
ROWS = 12
COLS = 7
SHR_BASE = 0x2000
ROW_BYTES = 160

# Ms. Pac #879D: (sprite, color bank, name). Junior bank 0 → #09 override.
FRUITS = (
    (0, 0x14, "Cherry"),
    (1, 0x0F, "Strawberry"),
    (2, 0x15, "Orange"),
    (3, 0x07, "Pretzel"),
    (4, 0x14, "Apple"),
    (5, 0x15, "Pear"),
    (6, 0x16, "Banana"),
    (7, 0x09, "Junior"),  # table lists #00; PROM bank 0 is blank
)

# Color-ROM index → preferred SHR pen (§2; red→5, pale→1 not COL_POWER)
_ROM_TO_SHR = {
    0: 0,
    1: 5,
    2: 6,
    3: 7,
    4: 0,
    5: 9,
    6: 10,
    7: 11,
    8: 0,
    9: 13,
    10: 0,
    11: 15,
    12: 4,
    13: 8,
    14: 2,
    15: 1,
}


def _load_gfx():
    path = ROOT / "py" / "gen_shr_gfx.py"
    spec = importlib.util.spec_from_file_location("gen_shr_gfx", path)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod


def _load_pal():
    path = ROOT / "py" / "gen_palette.py"
    spec = importlib.util.spec_from_file_location("gen_palette", path)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod


def bank_to_shr_map(palette_rom: Path, bank: int) -> tuple[int, int, int, int]:
    """Arcade bank pens 0–3 → SHR pen indices."""
    pal = _load_pal()
    rom_pens = pal.load_palette_pens(palette_rom, bank)
    return tuple(_ROM_TO_SHR[p & 15] for p in rom_pens)  # type: ignore[return-value]


def remap_img(img: list[list[int]], shr_map: tuple[int, ...]) -> list[list[int]]:
    return [[shr_map[p & 3] for p in row] for row in img]


def emit_blit(label: str, spr: bytes, msk: bytes) -> tuple[list[str], int, int]:
    lines = [
        label,
        "\tphp",
        "\tsep\t#$20",
    ]
    full = partial = 0
    for row in range(ROWS):
        for col in range(COLS):
            i = row * COLS + col
            m = msk[i]
            if m == 0:
                continue
            addr = SHR_BASE + row * ROW_BYTES + col
            s = spr[i] & m
            if m == 0xFF:
                lines.append(f"\tlda\t#${s:02X}")
                lines.append(f"\tsta\t${addr:04X},y")
                full += 1
            else:
                lines.append(f"\tlda\t${addr:04X},y")
                lines.append(f"\tand\t#${m ^ 0xFF:02X}")
                lines.append(f"\tora\t#${s:02X}")
                lines.append(f"\tsta\t${addr:04X},y")
                partial += 1
    lines += ["\tplp", "\trts", ""]
    return lines, full, partial


def build_fruit_cell(gfx, rom: bytes, spr_code: int, shr_map: tuple[int, ...]):
    raw = gfx.decode_sprite(rom, spr_code)
    # Area resample keeps more fruit mass than nearest subsample (cherries were ~26 px).
    art = gfx.area_resample(gfx.upright_sprite(raw), gfx.SPRITE_ART, gfx.SPRITE_ART)
    even = remap_img(gfx.pad_sprite_14x12(art), shr_map)
    odd = gfx.shift_odd_cell(even)
    return (
        gfx.pack_4bpp_rows(even),
        bytes(gfx.pack_4bpp_rows(gfx.mask_from_pens(even))),
        gfx.pack_4bpp_rows(odd),
        bytes(gfx.pack_4bpp_rows(gfx.mask_from_pens(odd))),
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--sprites", type=Path, default=DEFAULT_SPRITE_ROM)
    ap.add_argument("--color-rom", type=Path, default=DEFAULT_COLOR_ROM)
    ap.add_argument("--palette-rom", type=Path, default=DEFAULT_PALETTE_ROM)
    ap.add_argument("-o", "--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args()

    if not args.sprites.is_file():
        raise SystemExit(f"missing sprite ROM {args.sprites}")

    gfx = _load_gfx()
    rom = args.sprites.read_bytes()

    lines: list[str] = [
        "*",
        "* Generated by py/gen_compiled_fruits.py - do not edit by hand",
        "* FruitBlitTable: (ACT_SPR&7)*2 + (X&1) -> abs addresses",
        "* Each blit: Y = SHR offset, DBR = $01, returns via RTS",
        "*",
        "",
        "FruitBlitGo",
        "* X = index*2 into FruitBlitTable; JMP so blit RTS returns to caller.",
        "\tjmp\t(FruitBlitTable,x)",
        "",
        "FruitBlitTable",
    ]

    labels: list[str] = []
    for fi, (spr_code, bank, name) in enumerate(FRUITS):
        for parity, tag in enumerate(("E", "O")):
            lab = f"CF{fi}_{tag}"
            labels.append(lab)
            lines.append(
                f"\tda\t{lab}\t; {name} spr=${spr_code:02X} bank=#{bank:02X} "
                f"{'odd' if parity else 'even'}"
            )

    lines.append("")
    body: list[str] = []
    total_full = total_part = 0

    for fi, (spr_code, bank, name) in enumerate(FRUITS):
        shr_map = bank_to_shr_map(args.palette_rom, bank)
        even_s, even_m, odd_s, odd_m = build_fruit_cell(gfx, rom, spr_code, shr_map)
        for tag, spr, msk in (("E", even_s, even_m), ("O", odd_s, odd_m)):
            lab = f"CF{fi}_{tag}"
            blit, full, part = emit_blit(lab, spr, msk)
            body.extend(blit)
            total_full += full
            total_part += part
            print(f"  {lab}: {name} bank=#{bank:02X} map={shr_map}")

    lines.extend(body)
    lines.append("\tmx\t%00")
    lines.append("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(
        f"wrote {args.out} ({len(labels)} blits, "
        f"{total_full} solid + {total_part} partial byte ops)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
