#!/usr/bin/env python3
"""Namco WSG sound PROM -> DOC wave samples and frequency tables (iigs/wave_data.s).

The arcade's eight waveforms are 32 samples of 4 bits in 82s126.1m. The
lowered IIgs host (iigs/lower_sound.s) gives each a 4 KB DOC table at
DOC_WAVE_ADDR + wave * $1000: one cycle, each sample repeated 128 times,
as $80 + (nib - 8) * 6 ($50-$AA, peak |sample - $80| is $30; never
$00, which halts an oscillator). A free-running DOC
oscillator wraps one entry short of its table (MAME, GSSquared); with
4096 entries per cycle that is 1/128 of a sample, where a 256-byte table
holding 8 cycles drops a whole sample every 8 cycles (an audible buzz).

Four oscillators are enabled (voices on 0-2, 3 halted), so the scan rate
SR is 7159090 / 8 / 6, about 149 kHz, above the arcade's 96 kHz. A voice's
20-bit WSG frequency F plays F * 96000 / 2^20 Hz; a table at resolution R
plays SR * D / 2^(17+R) cycles a second, so

  D = F * 12000 * 2^R / SR

R = 3 keeps the lowest game notes within 0.6% and the highest the game
plays (F = $9800) at D of about 25,000; D saturates at $FFFF. F arrives as
five nibbles, so D is a sum of FreqNib0..FreqNib4 lookups (24.8 fixed
point, 4 bytes per entry), plus $80 to round. The check
(py/gs2_lower_check.py) imports the constants and doc_freq() /
doc_samples() from here.

Usage:
  python3 py/gen_wave_data.py [--prom mspacman/82s126.1m] [-o iigs/wave_data.s]
"""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_PROM = ROOT / "mspacman" / "82s126.1m"
DEFAULT_OUT = ROOT / "iigs" / "wave_data.s"

DOC_CLOCK = 7159090
DOC_OSCS = 4
SR = DOC_CLOCK / 8 / (DOC_OSCS + 2)
SR_INT = DOC_CLOCK // 8 // (DOC_OSCS + 2)  # GSSquared's reported output rate
DOC_E1 = (DOC_OSCS - 1) * 2
WAVES = 8
WAVE_SAMPLES = 32
TABLE_SIZE_CODE = 4  # 256 << 4 = 4096 bytes
TABLE_BYTES = 256 << TABLE_SIZE_CODE
STRETCH = TABLE_BYTES // WAVE_SAMPLES
RESOLUTION = 3
DOC_WAVE_ADDR = 0x8000
SAMPLE_SCALE = 6  # $80 + (nib-8)*6: nibble 0 is $50, peak |s-$80| is $30
FIX = 256  # 24.8


def nib_table(k: int) -> list[int]:
    return [round(n * 16**k * 12000 * 2**RESOLUTION * FIX / SR) for n in range(16)]


TABLES = [nib_table(k) for k in range(5)]


def doc_freq(nibbles: list[int]) -> int:
    """D for five frequency nibbles, low first (voices 1 and 2 pass 0 first)."""
    acc = FIX // 2
    for k, n in enumerate(nibbles):
        acc += TABLES[k][n & 15]
    return min(acc // FIX, 0xFFFF)


def wave_page(wave: int) -> int:
    """The DOC wavetable pointer register value for a wave."""
    return (DOC_WAVE_ADDR + (wave & 7) * TABLE_BYTES) >> 8


def doc_byte(nib: int) -> int:
    """WSG nibble -> DOC sample. $80 is zero; scale 6 so nibble 0 is $50."""
    b = 0x80 + ((nib & 15) - 8) * SAMPLE_SCALE
    return 1 if b == 0 else b


def doc_samples(prom: bytes) -> bytes:
    """The DOC RAM image from DOC_WAVE_ADDR: 8 tables of TABLE_BYTES."""
    out = bytearray()
    for w in range(WAVES):
        for i in range(WAVE_SAMPLES):
            out += bytes([doc_byte(prom[w * WAVE_SAMPLES + i])]) * STRETCH
    return bytes(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--prom", type=Path, default=DEFAULT_PROM)
    ap.add_argument("-o", "--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args()

    prom = args.prom.read_bytes()
    if len(prom) != 256:
        raise SystemExit(f"{args.prom}: expected 256 bytes, got {len(prom)}")
    if sum(t[15] for t in TABLES) + FIX // 2 >= 1 << 32:
        raise SystemExit("frequency tables overflow 32 bits")

    lines = [
        "*",
        "* Generated by py/gen_wave_data.py - do not edit by hand",
        "* WaveSamples: the 8 WSG waves, 32 bytes each, $80+(nib-8)*6",
        f"* FreqNib0-4: D contribution of frequency nibble k, 24.8 (SR {SR:.2f} Hz,",
        f"* resolution {RESOLUTION}, {TABLE_BYTES}-byte tables)",
        "*",
        "",
        "WaveSamples",
    ]
    for w in range(WAVES):
        s = [doc_byte(prom[w * 32 + i]) for i in range(32)]
        for h in (0, 16):
            lines.append("\tdb\t" + ",".join(f"${b:02X}" for b in s[h : h + 16])
                         + (f"\t; wave {w}" if h == 0 else ""))
    for k, t in enumerate(TABLES):
        lines.append("")
        lines.append(f"FreqNib{k}")
        for n in range(0, 16, 4):
            lines.append("\tadrl\t" + ",".join(f"${v:08X}" for v in t[n : n + 4]))
    lines.append("")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"wrote {args.out} (SR {SR:.2f} Hz, D for F=$9800 ${doc_freq([0, 0, 8, 9, 0]):04X}, "
          f"for F=$80 {doc_freq([0, 8, 0, 0, 0])})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
