#!/usr/bin/env python3
"""Generate src/ram.inc from py/ram_symbols.py.

Usage:
  python3 py/gen_ram_inc.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(Path(__file__).resolve().parent))
from ram_symbols import SYMBOLS  # noqa: E402

OUT = ROOT / "src" / "ram.inc"


def main() -> int:
    lines = [
        ";; Auto-generated by py/gen_ram_inc.py — curated documented RAM/IO symbols",
        ";; Do not hand-edit unless coordinating with py/ram_symbols.py",
        "",
    ]
    for addr in sorted(SYMBOLS):
        name, comment = SYMBOLS[addr]
        lines.append(f"{name:<28} EQU  #{addr:04X}\t; {comment}")
    lines.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({len(SYMBOLS)} symbols)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
