#!/usr/bin/env python3
"""Documented Pac-Man / Ms. Pac-Man RAM, I/O, and related symbols.

Curated from the header commentary in mspac.asm plus existing sound EQU names.
Used by gen_ram_inc.py and label_abs_mem.py.
"""

from __future__ import annotations

# addr -> (symbol, comment)
# Prefer clear snake_case; keep classic sound names (CH1_*) where already established.
SYMBOLS: dict[int, tuple[str, str]] = {
    # --- Sprite shadow RAM (4C00) ---
    0x4C00: ("spr_unk_4c00", "unknown"),
    0x4C01: ("spr_unk_4c01", "unknown"),
    0x4C02: ("spr_red_code", "red ghost sprite number"),
    0x4C03: ("spr_red_color", "red ghost color entry"),
    0x4C04: ("spr_pink_code", "pink ghost sprite number"),
    0x4C05: ("spr_pink_color", "pink ghost color entry"),
    0x4C06: ("spr_blue_code", "blue ghost sprite number"),
    0x4C07: ("spr_blue_color", "blue ghost color entry"),
    0x4C08: ("spr_orange_code", "orange ghost sprite number"),
    0x4C09: ("spr_orange_color", "orange ghost color entry"),
    0x4C0A: ("spr_pac_code", "pacman sprite number"),
    0x4C0B: ("spr_pac_color", "pacman color entry"),
    0x4C0C: ("spr_fruit_code", "fruit sprite number"),
    0x4C0D: ("spr_fruit_color", "fruit color entry"),
    0x4C20: ("spr_hw_data", "sprite data for hardware sprite system"),
    0x4C22: ("spr_pos_base", "sprite positions for spriteram2 (4C22-4C2F)"),
    0x4C32: ("spr_code_base", "sprite number/color for spriteram (4C32-4C3F)"),
    # Fruit path (also named COUNT/BCNT/PATH in docs)
    0x4C40: ("fruit_path_index", "COUNT: current place in fruit path"),
    0x4C41: ("fruit_bounce_index", "BCNT: current place within bounce"),
    0x4C42: ("fruit_path_ptr", "PATH: pointer to current fruit path (lo)"),
    0x4C43: ("fruit_path_ptr_hi", "PATH: pointer to current fruit path (hi)"),
    # Tasks / timers
    0x4C80: ("task_list_tail_ptr", "pointer to end of non-IRQ task list (lo)"),
    0x4C81: ("task_list_tail_ptr_hi", "pointer to end of non-IRQ task list (hi)"),
    0x4C82: ("task_list_head_ptr", "pointer to beginning of task list (lo)"),
    0x4C83: ("task_list_head_ptr_hi", "pointer to beginning of task list (hi)"),
    0x4C84: ("SOUND_COUNTER", "VBLANK sound counter (also SOUND_COUNTER)"),
    0x4C85: ("timer_unused_4c85", "8-bit counter unused"),
    0x4C86: ("clock_hundredths", "clock counter: hundredths"),
    0x4C87: ("clock_seconds", "clock counter: seconds"),
    0x4C88: ("clock_minutes", "clock counter: minutes"),
    0x4C89: ("clock_hours", "clock counter: hours"),
    0x4C8A: ("clock_limit_changes", "counter-limit changes this frame"),
    0x4C8B: ("rng_unused_4c8b", "random (unused)"),
    0x4C8C: ("rng_unused_4c8c", "random (unused)"),
    0x4C90: ("timed_task_list", "IRQ scheduled tasks (4C90-4CBF), 16 x 3 bytes"),
    0x4CC0: ("main_task_list", "non-IRQ tasks (4CC0-4CCF), 16 x 2 bytes"),
    # Ghost / pac pixel & tile state (4D00)
    0x4D00: ("red_y", "red ghost Y pixel"),
    0x4D01: ("red_x", "red ghost X pixel"),
    0x4D02: ("pink_y", "pink ghost Y pixel"),
    0x4D03: ("pink_x", "pink ghost X pixel"),
    0x4D04: ("blue_y", "blue ghost Y pixel"),
    0x4D05: ("blue_x", "blue ghost X pixel"),
    0x4D06: ("orange_y", "orange ghost Y pixel"),
    0x4D07: ("orange_x", "orange ghost X pixel"),
    0x4D08: ("pac_y", "pacman Y pixel"),
    0x4D09: ("pac_x", "pacman X pixel"),
    0x4D0A: ("red_tile_y", "red ghost Y tile (mid)"),
    0x4D0B: ("red_tile_x", "red ghost X tile (mid)"),
    0x4D0C: ("pink_tile_y", "pink ghost Y tile (mid)"),
    0x4D0D: ("pink_tile_x", "pink ghost X tile (mid)"),
    0x4D0E: ("blue_tile_y", "blue ghost Y tile (mid)"),
    0x4D0F: ("blue_tile_x", "blue ghost X tile (mid)"),
    0x4D10: ("orange_tile_y", "orange ghost Y tile (mid)"),
    0x4D11: ("orange_tile_x", "orange ghost X tile (mid)"),
    0x4D12: ("pac_demo_tile_y", "pacman tile Y in demo/cutscenes"),
    0x4D13: ("pac_demo_tile_x", "pacman tile X in demo/cutscenes"),
    0x4D14: ("red_tile_dy", "red ghost Y tile delta"),
    0x4D15: ("red_tile_dx", "red ghost X tile delta"),
    0x4D16: ("pink_tile_dy", "pink ghost Y tile delta"),
    0x4D17: ("pink_tile_dx", "pink ghost X tile delta"),
    0x4D18: ("blue_tile_dy", "blue ghost Y tile delta"),
    0x4D19: ("blue_tile_dx", "blue ghost X tile delta"),
    0x4D1A: ("orange_tile_dy", "orange ghost Y tile delta"),
    0x4D1B: ("orange_tile_dx", "orange ghost X tile delta"),
    0x4D1C: ("pac_tile_dy", "pacman Y tile delta"),
    0x4D1D: ("pac_tile_dx", "pacman X tile delta"),
    0x4D1E: ("red_tile_dy2", "red ghost Y tile changes"),
    0x4D1F: ("red_tile_dx2", "red ghost X tile changes"),
    0x4D20: ("pink_tile_dy2", "pink ghost Y tile changes"),
    0x4D21: ("pink_tile_dx2", "pink ghost X tile changes"),
    0x4D22: ("blue_tile_dy2", "blue ghost Y tile changes"),
    0x4D23: ("blue_tile_dx2", "blue ghost X tile changes"),
    0x4D24: ("orange_tile_dy2", "orange ghost Y tile changes"),
    0x4D25: ("orange_tile_dx2", "orange ghost X tile changes"),
    0x4D26: ("pac_wanted_tile_dy", "wanted pacman tile Y changes"),
    0x4D27: ("pac_wanted_tile_dx", "wanted pacman tile X changes"),
    0x4D28: ("red_prev_dir", "previous red orientation"),
    0x4D29: ("pink_prev_dir", "previous pink orientation"),
    0x4D2A: ("blue_prev_dir", "previous blue orientation"),
    0x4D2B: ("orange_prev_dir", "previous orange orientation"),
    0x4D2C: ("red_dir", "red ghost orientation"),
    0x4D2D: ("pink_dir", "pink ghost orientation"),
    0x4D2E: ("blue_dir", "blue ghost orientation"),
    0x4D2F: ("orange_dir", "orange ghost orientation"),
    0x4D30: ("pac_dir", "pacman orientation"),
    0x4D31: ("red_tile_y2", "red ghost Y tile position 2"),
    0x4D32: ("red_tile_x2", "red ghost X tile position 2"),
    0x4D33: ("pink_tile_y2", "pink ghost Y tile position 2"),
    0x4D34: ("pink_tile_x2", "pink ghost X tile position 2"),
    0x4D35: ("blue_tile_y2", "blue ghost Y tile position 2"),
    0x4D36: ("blue_tile_x2", "blue ghost X tile position 2"),
    0x4D37: ("orange_tile_y2", "orange ghost Y tile position 2"),
    0x4D38: ("orange_tile_x2", "orange ghost X tile position 2"),
    0x4D39: ("pac_tile_y", "pacman Y tile position"),
    0x4D3A: ("pac_tile_x", "pacman X tile position"),
    0x4D3B: ("path_best_dir", "pathfinding: best orientation found"),
    0x4D3C: ("pac_wanted_dir", "wanted pacman orientation"),
    0x4D3D: ("path_opposite_dir", "pathfinding: opposite orientation"),
    0x4D3E: ("path_cur_tile_lo", "pathfinding: current tile (lo)"),
    0x4D3F: ("path_cur_tile_hi", "pathfinding: current tile (hi)"),
    0x4D40: ("path_dest_tile_lo", "pathfinding: destination tile (lo)"),
    0x4D41: ("path_dest_tile_hi", "pathfinding: destination tile (hi)"),
    0x4D42: ("path_temp_pos_lo", "pathfinding: temp resulting position (lo)"),
    0x4D43: ("path_temp_pos_hi", "pathfinding: temp resulting position (hi)"),
    0x4D44: ("path_min_dist_lo", "pathfinding: minimum distance^2 (lo)"),
    0x4D45: ("path_min_dist_hi", "pathfinding: minimum distance^2 (hi)"),
    0x4D46: ("speed_pat_pac_normal", "speed patterns: pacman normal (4D46-4D49)"),
    0x4D4A: ("speed_pat_pac_energized", "speed patterns: pacman big-pill (4D4A-4D4D)"),
    0x4D4E: ("speed_pat_diff2", "speed patterns: second difficulty (4D4E-4D51)"),
    0x4D52: ("speed_pat_diff1", "speed patterns: first difficulty (4D52-4D55)"),
    0x4D56: ("speed_pat_red_normal", "speed patterns: red normal"),
    0x4D5A: ("speed_pat_red_blue", "speed patterns: red blue/frightened"),
    0x4D5E: ("speed_pat_red_tunnel", "speed patterns: red tunnel"),
    0x4D62: ("speed_pat_pink_normal", "speed patterns: pink normal"),
    0x4D66: ("speed_pat_pink_blue", "speed patterns: pink blue"),
    0x4D6A: ("speed_pat_pink_tunnel", "speed patterns: pink tunnel"),
    0x4D6E: ("speed_pat_blue_normal", "speed patterns: blue normal"),
    0x4D72: ("speed_pat_blue_blue", "speed patterns: blue blue"),
    0x4D76: ("speed_pat_blue_tunnel", "speed patterns: blue tunnel"),
    0x4D7A: ("speed_pat_orange_normal", "speed patterns: orange normal"),
    0x4D7E: ("speed_pat_orange_blue", "speed patterns: orange blue"),
    0x4D82: ("speed_pat_orange_tunnel", "speed patterns: orange tunnel"),
    0x4D86: ("ghost_orient_table", "difficulty ghost orientation change table (4D86-4D93)"),
    0x4D94: ("ghost_home_move_counter", "counter: ghost movement inside home"),
    0x4D95: ("ghost_leave_home_units_lo", "units before ghost leaves home (lo)"),
    0x4D96: ("ghost_leave_home_units_hi", "units before ghost leaves home (hi)"),
    0x4D97: ("ghost_leave_home_idle_lo", "inactivity counter for leave-home (lo)"),
    0x4D98: ("ghost_leave_home_idle_hi", "inactivity counter for leave-home (hi)"),
    0x4D99: ("red_tunnel_slow", "red in tunnel slowdown area"),
    0x4D9A: ("pink_tunnel_slow", "pink in tunnel slowdown area"),
    0x4D9B: ("blue_tunnel_slow", "blue in tunnel slowdown area"),
    0x4D9C: ("orange_tunnel_slow", "orange in tunnel slowdown area"),
    0x4D9D: ("pac_move_delay", "delay to update pacman movement"),
    0x4D9E: ("pills_since_pac_move", "pills eaten before last pacman move"),
    0x4D9F: ("pills_after_death", "pills eaten after death (ghost release)"),
    0x4DA0: ("red_substate", "red ghost substate if alive"),
    0x4DA1: ("pink_substate", "pink ghost substate if alive"),
    0x4DA2: ("blue_substate", "blue ghost substate if alive"),
    0x4DA3: ("orange_substate", "orange ghost substate if alive"),
    0x4DA4: ("ghosts_killed_pending", "# ghosts killed but collision not done yet"),
    0x4DA5: ("pac_death_anim", "pacman dead animation state"),
    0x4DA6: ("power_pill_active", "power pill effect active"),
    0x4DA7: ("red_frightened", "red ghost blue/frightened flag"),
    0x4DA8: ("pink_frightened", "pink ghost blue/frightened flag"),
    0x4DA9: ("blue_frightened", "blue ghost blue/frightened flag"),
    0x4DAA: ("orange_frightened", "orange ghost blue/frightened flag"),
    0x4DAB: ("kill_ghost_state", "killing ghost state (0=none, 1-4=which)"),
    0x4DAC: ("red_state", "red ghost state (alive/dead/home…)"),
    0x4DAD: ("pink_state", "pink ghost state"),
    0x4DAE: ("blue_state", "blue ghost state"),
    0x4DAF: ("orange_state", "orange ghost state"),
    0x4DB0: ("diff_unused_4db0", "difficulty related, appears unused"),
    0x4DB1: ("red_reverse_flag", "red change-orientation flag"),
    0x4DB2: ("pink_reverse_flag", "pink change-orientation flag"),
    0x4DB3: ("blue_reverse_flag", "blue change-orientation flag"),
    0x4DB4: ("orange_reverse_flag", "orange change-orientation flag"),
    0x4DB5: ("pac_reverse_flag", "pacman change-orientation flag (doc typo 4bd5)"),
    0x4DB6: ("cruise_elroy_1", "1st difficulty / cruise elroy 1 flag"),
    0x4DB7: ("cruise_elroy_2", "2nd difficulty / cruise elroy 2 flag"),
    0x4DB8: ("pink_exit_limit", "pink leave-home pill counter limit"),
    0x4DB9: ("blue_exit_limit", "blue leave-home pill counter limit"),
    0x4DBA: ("orange_exit_limit", "orange leave-home pill counter limit"),
    0x4DBB: ("elroy1_pill_threshold", "pills remaining for cruise elroy 1"),
    0x4DBC: ("elroy2_pill_threshold", "pills remaining for cruise elroy 2"),
    0x4DBD: ("frightened_time_lo", "frightened duration (lo)"),
    0x4DBE: ("frightened_time_hi", "frightened duration (hi)"),
    0x4DBF: ("pac_entering_tunnel", "1 if pacman about to enter tunnel"),
    0x4DC0: ("ghost_anim_phase", "changes every 8 frames; ghost anim"),
    0x4DC1: ("ghost_orient_index", "orientation-change table index"),
    0x4DC2: ("ghost_orient_counter_lo", "ghost orientation change counter (lo)"),
    0x4DC3: ("ghost_orient_counter_hi", "ghost orientation change counter (hi)"),
    0x4DC4: ("frame_div8_counter", "0..8; do work every 8 frames"),
    0x4DC5: ("death_counter_lo", "counter after pacman killed (lo)"),
    0x4DC6: ("death_counter_hi", "counter after pacman killed (hi)"),
    0x4DC7: ("path_try_dir", "current orientation being tried"),
    0x4DC8: ("frightened_flash_counter", "ghost color flash under big pill"),
    0x4DC9: ("rng_rom_ptr_lo", "RNG ROM pointer (lo), routine 2A23"),
    0x4DCA: ("rng_rom_ptr_hi", "RNG ROM pointer (hi)"),
    0x4DCB: ("frightened_timer_lo", "blue-ghost timer (lo); ceases at 0"),
    0x4DCC: ("frightened_timer_hi", "blue-ghost timer (hi)"),
    0x4DCE: ("coin_blink_counter", "after insert coin; LED / 1UP blink"),
    0x4DCF: ("power_pill_flash_counter", "power pill flash counter"),
    0x4DD0: ("ghosts_killed_count", "current killed ghosts 0..4"),
    0x4DD1: ("killed_ghost_anim", "killed ghost animation state"),
    0x4DD2: ("fruit_pos_lo", "FRUITP: fruit position (lo)"),
    0x4DD3: ("fruit_pos_hi", "FRUITP: fruit position (hi)"),
    0x4DD4: ("fruit_points", "FVALUE: fruit points entry, or 0"),
    0x4DD6: ("start_button_wait", "LED/start-button wait state"),
    # Main state / players / level (4E00)
    0x4E00: ("game_mode", "main routine number (init/demo/coin/play)"),
    0x4E01: ("game_mode_sub0", "main routine 0 subroutine #"),
    0x4E02: ("game_mode_sub1", "main routine 1 subroutine # (attract/demo)"),
    0x4E03: ("game_mode_sub2", "main routine 2 subroutine #"),
    0x4E04: ("level_state", "level state subroutine # (2=pause ghosts)"),
    0x4E06: ("cutscene1_state", "first cutscene state (pac-man)"),
    0x4E07: ("cutscene2_state", "second cutscene state"),
    0x4E08: ("cutscene3_state", "third cutscene state"),
    0x4E09: ("player_number", "current player: 0=P1, 1=P2"),
    0x4E0A: ("difficulty_ptr_lo", "pointer to current difficulty settings (lo)"),
    0x4E0B: ("difficulty_ptr_hi", "pointer to current difficulty settings (hi)"),
    0x4E0C: ("fruit1_released", "FIRSTF: first fruit released/appeared"),
    0x4E0D: ("fruit2_released", "SECONDF: second fruit flag"),
    0x4E0E: ("dots_eaten", "DOTSEAT: pills eaten this level"),
    0x4E0F: ("pink_exit_counter", "pill counter toward pink leaving home"),
    0x4E10: ("blue_exit_counter", "pill counter toward blue leaving home"),
    0x4E11: ("orange_exit_counter", "pill counter toward orange leaving home"),
    0x4E12: ("died_this_level", "1 after dying; cleared when ghosts leave via 4D9F"),
    0x4E13: ("level_number", "current level"),
    0x4E14: ("lives_real", "real number of lives"),
    0x4E15: ("lives_displayed", "number of lives displayed"),
    0x4E16: ("pill_bitmap", "pill bitmaps (4E16-4E33)"),
    0x4E34: ("power_pill_data", "power pill data (4E34-4E37)"),
    0x4E38: ("level_data_copy", "copy of level data (4E38-4E65)"),
    0x4E66: ("in_service_hist", "last 4 SERVICE1 samples"),
    0x4E67: ("in_coin2_hist", "last 4 COIN2 samples"),
    0x4E68: ("in_coin1_hist", "last 4 COIN1 samples"),
    0x4E69: ("coin_counter", "coin→credits counter"),
    0x4E6A: ("coin_counter_timeout", "coin counter timeout"),
    0x4E6B: ("dip_coins_per_credit", "coins per credit (from DSW)"),
    0x4E6C: ("coins_inserted", "number of coins inserted"),
    0x4E6D: ("dip_credits_per_coin", "credits per coin"),
    0x4E6E: ("credits", "credits; 0xFF = free play"),
    0x4E6F: ("dip_lives", "lives per game (from DSW)"),
    0x4E70: ("num_players", "0=1 player, 1=2 players"),
    0x4E71: ("dip_bonus_life", "bonus life threshold"),
    0x4E72: ("dip_cocktail", "cocktail mode"),
    0x4E73: ("dip_difficulty_ptr_lo", "difficulty settings pointer (lo)"),
    0x4E74: ("dip_difficulty_ptr_hi", "difficulty settings pointer (hi)"),
    0x4E75: ("ghost_names_mode", "ghost names mode 0/1"),
    0x4E80: ("score_p1_lo", "P1 score byte CC"),
    0x4E81: ("score_p1_mid", "P1 score byte BB"),
    0x4E82: ("score_p1_hi", "P1 score byte AA"),
    0x4E83: ("bonus_life_p1", "P1 got bonus life?"),
    0x4E84: ("score_p2_lo", "P2 score byte CC"),
    0x4E85: ("score_p2_mid", "P2 score byte BB"),
    0x4E86: ("score_p2_hi", "P2 score byte AA"),
    0x4E87: ("bonus_life_p2", "P2 got bonus life?"),
    0x4E88: ("high_score_lo", "high score byte CC"),
    0x4E89: ("high_score_mid", "high score byte BB"),
    0x4E8A: ("high_score_hi", "high score byte AA"),
    # Sound hardware shadow (keep established names)
    0x4E8C: ("CH1_FREQ0", "ch1 freq nibble 0"),
    0x4E8D: ("CH1_FREQ1", "ch1 freq nibble 1"),
    0x4E8E: ("CH1_FREQ2", "ch1 freq nibble 2"),
    0x4E8F: ("CH1_FREQ3", "ch1 freq nibble 3"),
    0x4E90: ("CH1_FREQ4", "ch1 freq nibble 4"),
    0x4E91: ("CH1_VOL", "ch1 volume"),
    0x4E92: ("CH2_FREQ1", "ch2 freq nibble 1"),
    0x4E93: ("CH2_FREQ2", "ch2 freq nibble 2"),
    0x4E94: ("CH2_FREQ3", "ch2 freq nibble 3"),
    0x4E95: ("CH2_FREQ4", "ch2 freq nibble 4"),
    0x4E96: ("CH2_VOL", "ch2 volume"),
    0x4E97: ("CH3_FREQ1", "ch3 freq nibble 1"),
    0x4E98: ("CH3_FREQ2", "ch3 freq nibble 2"),
    0x4E99: ("CH3_FREQ3", "ch3 freq nibble 3"),
    0x4E9A: ("CH3_FREQ4", "ch3 freq nibble 4"),
    0x4E9B: ("CH3_VOL", "ch3 volume"),
    0x4E9C: ("CH1_E_NUM", "ch1 effects bitmask"),
    0x4E9D: ("CH1_E_1", "ch1 effect unused"),
    0x4E9E: ("CH1_E_CUR_BIT", "ch1 current effect"),
    0x4E9F: ("CH1_E_TABLE0", "ch1 effect params"),
    0x4EA0: ("CH1_E_TABLE1", "ch1 effect params"),
    0x4EA1: ("CH1_E_TABLE2", "ch1 effect params"),
    0x4EA2: ("CH1_E_TABLE3", "ch1 effect params"),
    0x4EA3: ("CH1_E_TABLE4", "ch1 effect params"),
    0x4EA4: ("CH1_E_TABLE5", "ch1 effect params"),
    0x4EA5: ("CH1_E_TABLE6", "ch1 effect params"),
    0x4EA6: ("CH1_E_TABLE7", "ch1 effect params"),
    0x4EA7: ("CH1_E_TYPE", "ch1 effect type"),
    0x4EA8: ("CH1_E_DURATION", "ch1 effect duration"),
    0x4EA9: ("CH1_E_DIR", "ch1 effect dir"),
    0x4EAA: ("CH1_E_BASE_FREQ", "ch1 effect base freq"),
    0x4EAB: ("CH1_E_VOL", "ch1 effect volume"),
    0x4EAC: ("CH2_E_NUM", "ch2 effects block (same layout as CH1_E_*)"),
    0x4EAF: ("CH2_E_TABLE0", "ch2 effect table0"),
    0x4EBC: ("CH3_E_NUM", "ch3 effects / BNOISE bounce noise bit5"),
    0x4EBF: ("CH3_E_TABLE0", "ch3 effect table0"),
    0x4ECC: ("CH1_W_NUM", "ch1 wave bitmask"),
    0x4ECD: ("CH1_W_1", "ch1 wave unused"),
    0x4ECE: ("CH1_W_CUR_BIT", "ch1 current wave"),
    0x4ECF: ("CH1_W_SEL", "ch1 wave select"),
    0x4ED0: ("CH1_W_4", "ch1 wave"),
    0x4ED1: ("CH1_W_5", "ch1 wave"),
    0x4ED2: ("CH1_W_OFFSET1", "ch1 wave ROM offset lo"),
    0x4ED3: ("CH1_W_OFFSET2", "ch1 wave ROM offset hi"),
    0x4ED4: ("CH1_W_8", "ch1 wave"),
    0x4ED5: ("CH1_W_9", "ch1 wave"),
    0x4ED6: ("CH1_W_A", "ch1 wave"),
    0x4ED7: ("CH1_W_TYPE", "ch1 wave type"),
    0x4ED8: ("CH1_W_DURATION", "ch1 wave duration"),
    0x4ED9: ("CH1_W_DIR", "ch1 wave dir"),
    0x4EDA: ("CH1_W_BASE_FREQ", "ch1 wave base freq"),
    0x4EDB: ("CH1_W_VOL", "ch1 wave volume"),
    0x4EDC: ("CH2_W_NUM", "ch2 wave block"),
    0x4EDD: ("CH2_W_1", "ch2 wave unused"),
    0x4EDE: ("CH2_W_CUR_BIT", "ch2 current wave"),
    0x4EDF: ("CH2_W_SEL", "ch2 wave select"),
    0x4EEC: ("CH3_W_NUM", "ch3 wave block"),
    0x4EED: ("CH3_W_1", "ch3 wave unused"),
    0x4EEE: ("CH3_W_CUR_BIT", "ch3 current wave"),
    0x4EEF: ("CH3_W_SEL", "ch3 wave select"),
    0x4F00: ("intermission_flag", "1 during intermission / parts of attract"),
    0x4F01: ("cpu_stack_base", "CPU stack region (4F01-4FBF)"),
    0x4FF0: ("sprite_ram", "sprite RAM (4FF0-4FFF)"),
    # Memory-mapped I/O
    0x5000: ("IN0", "inputs: joy1 / rack test / coins / service"),
    0x5001: ("irq_enable", "interrupt enable (common pac HW)"),
    0x5002: ("sound_enable", "sound enable"),
    0x5003: ("flip_screen", "flip screen / cocktail"),
    0x5004: ("lamp_p1", "player 1 lamp"),
    0x5005: ("lamp_p2", "player 2 lamp"),
    0x5006: ("coin_lockout", "coin lockout"),
    0x5007: ("coin_counter_out", "coin counter output / watchdog kick"),
    0x5040: ("IN1", "inputs: joy2 / service / start / cocktail dip"),
    0x5045: ("sound_voice1", "namco WSG voice regs region"),
    0x5080: ("DSW1", "DIP switch 1"),
    0x50C0: ("watchdog", "watchdog / kick the dog"),
    # Documented ROM sound tables (from header EQU block)
    0x3B30: ("EFFECT_TABLE_1", "channel 1 effects table"),
    0x3B40: ("EFFECT_TABLE_2", "channel 2 effects table"),
    0x3B80: ("EFFECT_TABLE_3", "channel 3 effects table"),
    0x9685: ("SONG_TABLE_1", "Ms. Pac ch1 song table"),
    0x967D: ("SONG_TABLE_2", "Ms. Pac ch2 song table"),
    0x968D: ("SONG_TABLE_3", "Ms. Pac ch3 song table"),
}


def by_symbol() -> dict[str, int]:
    out: dict[str, int] = {}
    for addr, (name, _) in SYMBOLS.items():
        if name in out and out[name] != addr:
            raise ValueError(f"duplicate symbol {name}")
        out[name] = addr
    return out
