/* Generated by py/gen_lower_entries.py from lower/entries.txt. */
#ifndef LOWER_ENTRIES_H
#define LOWER_ENTRIES_H

enum {
	LF_st_add = 0,
	LF_st_bcd = 1,
	LF_st_store16 = 2,
	LF_st_load16 = 3,
	LF_lift_random_byte = 4,
	LF_rom_random = 5,
	LF_dir_step = 6,
	LF_coord_add = 7,
	LF_coord_eq = 8,
	LF_coord_word = 9,
	LF_word_coord = 10,
	LF_pos_to_tile = 11,
	LF_tile_cell = 12,
	LF_tile_at = 13,
	LF_color_at = 14,
	LF_is_wall = 15,
	LF_tunnel_wrap = 16,
	LF_speed_tick = 17,
	LF_queue_task = 18,
	LF_task_next_level_state = 19,
	LF_load_difficulty = 20,
	LF_update_elroy = 21,
	LF_siren_update = 22,
	LF_draw_block = 23,
	LF_draw_icon = 24,
	LF_draw_fruit_row = 25,
	LF_draw_message = 26,
	LF_draw_tile_list = 27,
	LF_text_task = 28,
	LF_draw_1up = 29,
	LF_draw_2up = 30,
	LF_clear_label = 31,
	LF_update_lamps = 32,
	LF_hud_blink = 33,
	LF_draw_score = 34,
	LF_draw_player_score = 35,
	LF_draw_lives = 36,
	LF_award_life = 37,
	LF_add_score = 38,
	LF_draw_lives_row = 39,
	LF_draw_bonus_digits = 40,
	LF_read_dip_switches = 41,
	LF_draw_scores = 42,
	LF_show_credits = 43,
	LF_draw_midway_logo = 44,
	LF_marquee_bulbs = 45,
	LF_show_card = 46,
	LF_open_marquee = 47,
	LF_attract_step = 48,
	LF_maze_word = 49,
	LF_power_pill_cell = 50,
	LF_flash_power_pills = 51,
	LF_pill_bitmap = 52,
	LF_reset_pills = 53,
	LF_draw_pills = 54,
	LF_erase_pills = 55,
	LF_clear_colors = 56,
	LF_clear_screen = 57,
	LF_draw_maze = 58,
	LF_wall_color = 59,
	LF_maze_colors = 60,
	LF_demo_mode = 61,
	LF_clear_actors = 62,
	LF_house_timer = 63,
	LF_place_actors = 64,
	LF_add_coin = 65,
	LF_coin_meter = 66,
	LF_coin_inputs = 67,
	LF_clock_tick = 68,
	LF_advance_level_state = 69,
	LF_advance_play_state = 70,
	LF_advance_attract_state = 71,
	LF_advance_eaten_ghost_anim = 72,
	LF_clear_ready = 73,
	LF_advance_cutscene1 = 74,
	LF_advance_cutscene2 = 75,
	LF_advance_cutscene3 = 76,
	LF_timers_run = 77,
	LF_queue_timed = 78,
	LF_clear_fruit = 79,
	LF_clear_fruit_pos = 80,
	LF_choose_path = 81,
	LF_release_fruit = 82,
	LF_next_bounce = 83,
	LF_end_of_path = 84,
	LF_move_fruit = 85,
	LF_best_dir = 86,
	LF_random_dir = 87,
	LF_random_corner = 88,
	LF_aim_red = 89,
	LF_aim_pink = 90,
	LF_aim_blue = 91,
	LF_aim_orange = 92,
	LF_demo_steer = 93,
	LF_color_eyes = 94,
	LF_start_fright = 95,
	LF_fright_countdown = 96,
	LF_flash_ghosts = 97,
	LF_ghost_hit = 98,
	LF_tile_collision = 99,
	LF_pixel_collision = 100,
	LF_show_eaten_ghost = 101,
	LF_move_ghosts = 102,
	LF_return_all_eyes = 103,
	LF_mark_eaten_ghost = 104,
	LF_move_in_house = 105,
	LF_release_by_pills = 106,
	LF_count_house_pill = 107,
	LF_release_idle_ghost = 108,
	LF_ghost_anim_tick = 109,
	LF_reversal_timer = 110,
	LF_wall_ahead = 111,
	LF_eat_pill = 112,
	LF_arrive = 113,
	LF_pac_step = 114,
	LF_adopt = 115,
	LF_try_turn = 116,
	LF_want = 117,
	LF_face = 118,
	LF_demo_move = 119,
	LF_steer = 120,
	LF_move_pac = 121,
	LF_clear_actor_positions = 122,
	LF_pac_death = 123,
	LF_sound_effects = 124,
	LF_sound_songs = 125,
	LF_cutscene2_sprites = 126,
	LF_cutscene1_positions = 127,
	LF_cutscene3_sprites = 128,
	LF_cutscene1_sprites = 129,
	LF_load_scripts = 130,
	LF_run_cutscene = 131,
	LF_run_act = 132,
	LF_sprites_upright = 133,
	LF_sprites_cocktail = 134,
	LF_play_pass = 135,
	LF_play_frame = 136,
	LF_draw_prompt = 137,
	LF_begin_game = 138,
	LF_wait_start = 139,
	LF_set_up_game = 140,
	LF_start_play = 141,
	LF_press_start = 142,
	LF_flip_for_player = 143,
	LF_wait_level_state = 144,
	LF_swap_players = 145,
	LF_new_game = 146,
	LF_opening = 147,
	LF_playing = 148,
	LF_life_lost = 149,
	LF_next_turn = 150,
	LF_game_over = 151,
	LF_get_ready = 152,
	LF_board_clear = 153,
	LF_flash_maze = 154,
	LF_clear_board = 155,
	LF_intermission = 156,
	LF_next_board = 157,
	LF_level_step = 158,
	LF_power_on = 159,
	LF_attract = 160,
	LF_game_mode_step = 161,
	LF_game_start = 162,
	LF_sched_tasks = 163,
	LF_vblank = 164,
	LF_c_only_frame = 165,
	LF_COUNT = 166
};

#define LH_lift_random_byte(p0) do { \
	int lm_ = lower_enter(LF_lift_random_byte); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		uint32_t lc_ = 0; \
		if (lm_ == 1) { lower_c_begin(LF_lift_random_byte); lc_ = (uint32_t)(lift_random_byte(p0)) & 0xFFu; lower_c_end(LF_lift_random_byte); } \
		uint32_t lw_ = lower_run(LF_lift_random_byte, &lr_); \
		if (lm_ == 1) lower_finish(LF_lift_random_byte, lc_, lw_, &lr_); \
		uint32_t lr2_ = lm_ == 1 ? lc_ : lw_; \
		return (uint8_t)lr2_; \
	} \
} while (0)

#define LH_rom_random(p0) do { \
	int lm_ = lower_enter(LF_rom_random); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		uint32_t lc_ = 0; \
		if (lm_ == 1) { lower_c_begin(LF_rom_random); lc_ = (uint32_t)(rom_random(p0)) & 0xFFu; lower_c_end(LF_rom_random); } \
		uint32_t lw_ = lower_run(LF_rom_random, &lr_); \
		if (lm_ == 1) lower_finish(LF_rom_random, lc_, lw_, &lr_); \
		uint32_t lr2_ = lm_ == 1 ? lc_ : lw_; \
		return (uint8_t)lr2_; \
	} \
} while (0)

#define LH_dir_step(p0, p1) do { \
	int lm_ = lower_enter(LF_dir_step); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p1); \
		Coord lc_c = {0, 0}; uint32_t lc_ = 0; \
		if (lm_ == 1) { lower_c_begin(LF_dir_step); lc_c = dir_step(p0, p1); lc_ = lower_coord_word(lc_c); lower_c_end(LF_dir_step); } \
		uint32_t lw_ = lower_run(LF_dir_step, &lr_); \
		if (lm_ == 1) lower_finish(LF_dir_step, lc_, lw_, &lr_); \
		uint32_t lr2_ = lm_ == 1 ? lc_ : lw_; \
		return lower_word_coord((uint16_t)lr2_); \
	} \
} while (0)

#define LH_coord_add(p0, p1) do { \
	int lm_ = lower_enter(LF_coord_add); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.x = lower_coord_word(p0); \
		lr_.y = lower_coord_word(p1); \
		Coord lc_c = {0, 0}; uint32_t lc_ = 0; \
		if (lm_ == 1) { lower_c_begin(LF_coord_add); lc_c = coord_add(p0, p1); lc_ = lower_coord_word(lc_c); lower_c_end(LF_coord_add); } \
		uint32_t lw_ = lower_run(LF_coord_add, &lr_); \
		if (lm_ == 1) lower_finish(LF_coord_add, lc_, lw_, &lr_); \
		uint32_t lr2_ = lm_ == 1 ? lc_ : lw_; \
		return lower_word_coord((uint16_t)lr2_); \
	} \
} while (0)

#define LH_coord_eq(p0, p1) do { \
	int lm_ = lower_enter(LF_coord_eq); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.x = lower_coord_word(p0); \
		lr_.y = lower_coord_word(p1); \
		uint32_t lc_ = 0; \
		if (lm_ == 1) { lower_c_begin(LF_coord_eq); lc_ = (uint32_t)(coord_eq(p0, p1)) & 0xFFu; lower_c_end(LF_coord_eq); } \
		uint32_t lw_ = lower_run(LF_coord_eq, &lr_); \
		if (lm_ == 1) lower_finish(LF_coord_eq, lc_, lw_, &lr_); \
		uint32_t lr2_ = lm_ == 1 ? lc_ : lw_; \
		return (uint8_t)lr2_; \
	} \
} while (0)

#define LH_coord_word(p0) do { \
	int lm_ = lower_enter(LF_coord_word); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.x = lower_coord_word(p0); \
		uint32_t lc_ = 0; \
		if (lm_ == 1) { lower_c_begin(LF_coord_word); lc_ = (uint32_t)(coord_word(p0)) & 0xFFFFu; lower_c_end(LF_coord_word); } \
		uint32_t lw_ = lower_run(LF_coord_word, &lr_); \
		if (lm_ == 1) lower_finish(LF_coord_word, lc_, lw_, &lr_); \
		uint32_t lr2_ = lm_ == 1 ? lc_ : lw_; \
		return (uint16_t)lr2_; \
	} \
} while (0)

#define LH_word_coord(p0) do { \
	int lm_ = lower_enter(LF_word_coord); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.x = (uint16_t)(p0); \
		Coord lc_c = {0, 0}; uint32_t lc_ = 0; \
		if (lm_ == 1) { lower_c_begin(LF_word_coord); lc_c = word_coord(p0); lc_ = lower_coord_word(lc_c); lower_c_end(LF_word_coord); } \
		uint32_t lw_ = lower_run(LF_word_coord, &lr_); \
		if (lm_ == 1) lower_finish(LF_word_coord, lc_, lw_, &lr_); \
		uint32_t lr2_ = lm_ == 1 ? lc_ : lw_; \
		return lower_word_coord((uint16_t)lr2_); \
	} \
} while (0)

#define LH_pos_to_tile(p0) do { \
	int lm_ = lower_enter(LF_pos_to_tile); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.x = lower_coord_word(p0); \
		Coord lc_c = {0, 0}; uint32_t lc_ = 0; \
		if (lm_ == 1) { lower_c_begin(LF_pos_to_tile); lc_c = pos_to_tile(p0); lc_ = lower_coord_word(lc_c); lower_c_end(LF_pos_to_tile); } \
		uint32_t lw_ = lower_run(LF_pos_to_tile, &lr_); \
		if (lm_ == 1) lower_finish(LF_pos_to_tile, lc_, lw_, &lr_); \
		uint32_t lr2_ = lm_ == 1 ? lc_ : lw_; \
		return lower_word_coord((uint16_t)lr2_); \
	} \
} while (0)

#define LH_tile_cell(p0) do { \
	int lm_ = lower_enter(LF_tile_cell); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.x = lower_coord_word(p0); \
		uint32_t lc_ = 0; \
		if (lm_ == 1) { lower_c_begin(LF_tile_cell); lc_ = (uint32_t)(tile_cell(p0)) & 0xFFFFu; lower_c_end(LF_tile_cell); } \
		uint32_t lw_ = lower_run(LF_tile_cell, &lr_); \
		if (lm_ == 1) lower_finish(LF_tile_cell, lc_, lw_, &lr_); \
		uint32_t lr2_ = lm_ == 1 ? lc_ : lw_; \
		return (uint16_t)lr2_; \
	} \
} while (0)

#define LH_tile_at(p0, p1) do { \
	int lm_ = lower_enter(LF_tile_at); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.x = lower_coord_word(p1); \
		uint32_t lc_ = 0; \
		if (lm_ == 1) { lower_c_begin(LF_tile_at); lc_ = (uint32_t)(tile_at(p0, p1)) & 0xFFu; lower_c_end(LF_tile_at); } \
		uint32_t lw_ = lower_run(LF_tile_at, &lr_); \
		if (lm_ == 1) lower_finish(LF_tile_at, lc_, lw_, &lr_); \
		uint32_t lr2_ = lm_ == 1 ? lc_ : lw_; \
		return (uint8_t)lr2_; \
	} \
} while (0)

#define LH_color_at(p0, p1) do { \
	int lm_ = lower_enter(LF_color_at); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.x = lower_coord_word(p1); \
		uint32_t lc_ = 0; \
		if (lm_ == 1) { lower_c_begin(LF_color_at); lc_ = (uint32_t)(color_at(p0, p1)) & 0xFFu; lower_c_end(LF_color_at); } \
		uint32_t lw_ = lower_run(LF_color_at, &lr_); \
		if (lm_ == 1) lower_finish(LF_color_at, lc_, lw_, &lr_); \
		uint32_t lr2_ = lm_ == 1 ? lc_ : lw_; \
		return (uint8_t)lr2_; \
	} \
} while (0)

#define LH_is_wall(p0) do { \
	int lm_ = lower_enter(LF_is_wall); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p0); \
		uint32_t lc_ = 0; \
		if (lm_ == 1) { lower_c_begin(LF_is_wall); lc_ = (uint32_t)(is_wall(p0)) & 0xFFu; lower_c_end(LF_is_wall); } \
		uint32_t lw_ = lower_run(LF_is_wall, &lr_); \
		if (lm_ == 1) lower_finish(LF_is_wall, lc_, lw_, &lr_); \
		uint32_t lr2_ = lm_ == 1 ? lc_ : lw_; \
		return (uint8_t)lr2_; \
	} \
} while (0)

#define LH_tunnel_wrap(p0, p1) do { \
	int lm_ = lower_enter(LF_tunnel_wrap); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p1); \
		uint32_t lc_ = 0; \
		if (lm_ == 1) { lower_c_begin(LF_tunnel_wrap); lc_ = (uint32_t)(tunnel_wrap(p0, p1)) & 0xFFu; lower_c_end(LF_tunnel_wrap); } \
		uint32_t lw_ = lower_run(LF_tunnel_wrap, &lr_); \
		if (lm_ == 1) lower_finish(LF_tunnel_wrap, lc_, lw_, &lr_); \
		uint32_t lr2_ = lm_ == 1 ? lc_ : lw_; \
		return (uint8_t)lr2_; \
	} \
} while (0)

#define LH_speed_tick(p0) do { \
	int lm_ = lower_enter(LF_speed_tick); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.x = lower_mem_addr((const void *)(p0)); \
		uint32_t lc_ = 0; \
		if (lm_ == 1) { lower_c_begin(LF_speed_tick); lc_ = (uint32_t)(speed_tick(p0)) & 0xFFu; lower_c_end(LF_speed_tick); } \
		uint32_t lw_ = lower_run(LF_speed_tick, &lr_); \
		if (lm_ == 1) lower_finish(LF_speed_tick, lc_, lw_, &lr_); \
		uint32_t lr2_ = lm_ == 1 ? lc_ : lw_; \
		return (uint8_t)lr2_; \
	} \
} while (0)

#define LH_queue_task(p0, p1, p2) do { \
	int lm_ = lower_enter(LF_queue_task); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p1); \
		lr_.x = (uint16_t)(uint8_t)(p2); \
		if (lm_ == 1) { lower_c_begin(LF_queue_task); queue_task(p0, p1, p2); lower_c_end(LF_queue_task); } \
		uint32_t lw_ = lower_run(LF_queue_task, &lr_); \
		if (lm_ == 1) lower_finish(LF_queue_task, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_task_next_level_state(p0, p1) do { \
	int lm_ = lower_enter(LF_task_next_level_state); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p1); \
		if (lm_ == 1) { lower_c_begin(LF_task_next_level_state); task_next_level_state(p0, p1); lower_c_end(LF_task_next_level_state); } \
		uint32_t lw_ = lower_run(LF_task_next_level_state, &lr_); \
		if (lm_ == 1) lower_finish(LF_task_next_level_state, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_load_difficulty(p0, p1) do { \
	int lm_ = lower_enter(LF_load_difficulty); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p1); \
		if (lm_ == 1) { lower_c_begin(LF_load_difficulty); load_difficulty(p0, p1); lower_c_end(LF_load_difficulty); } \
		uint32_t lw_ = lower_run(LF_load_difficulty, &lr_); \
		if (lm_ == 1) lower_finish(LF_load_difficulty, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_update_elroy(p0) do { \
	int lm_ = lower_enter(LF_update_elroy); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_update_elroy); update_elroy(p0); lower_c_end(LF_update_elroy); } \
		uint32_t lw_ = lower_run(LF_update_elroy, &lr_); \
		if (lm_ == 1) lower_finish(LF_update_elroy, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_siren_update(p0) do { \
	int lm_ = lower_enter(LF_siren_update); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_siren_update); siren_update(p0); lower_c_end(LF_siren_update); } \
		uint32_t lw_ = lower_run(LF_siren_update, &lr_); \
		if (lm_ == 1) lower_finish(LF_siren_update, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_draw_block(p0, p1, p2) do { \
	int lm_ = lower_enter(LF_draw_block); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.x = (uint16_t)(p1); \
		lr_.a = (uint16_t)(uint8_t)(p2); \
		if (lm_ == 1) { lower_c_begin(LF_draw_block); draw_block(p0, p1, p2); lower_c_end(LF_draw_block); } \
		uint32_t lw_ = lower_run(LF_draw_block, &lr_); \
		if (lm_ == 1) lower_finish(LF_draw_block, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_draw_icon(p0, p1, p2) do { \
	int lm_ = lower_enter(LF_draw_icon); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.x = (uint16_t)(p1); \
		lr_.a = (uint16_t)(uint8_t)(p2); \
		if (lm_ == 1) { lower_c_begin(LF_draw_icon); draw_icon(p0, p1, p2); lower_c_end(LF_draw_icon); } \
		uint32_t lw_ = lower_run(LF_draw_icon, &lr_); \
		if (lm_ == 1) lower_finish(LF_draw_icon, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_draw_fruit_row(p0) do { \
	int lm_ = lower_enter(LF_draw_fruit_row); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_draw_fruit_row); draw_fruit_row(p0); lower_c_end(LF_draw_fruit_row); } \
		uint32_t lw_ = lower_run(LF_draw_fruit_row, &lr_); \
		if (lm_ == 1) lower_finish(LF_draw_fruit_row, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_draw_message(p0, p1) do { \
	int lm_ = lower_enter(LF_draw_message); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p1); \
		if (lm_ == 1) { lower_c_begin(LF_draw_message); draw_message(p0, p1); lower_c_end(LF_draw_message); } \
		uint32_t lw_ = lower_run(LF_draw_message, &lr_); \
		if (lm_ == 1) lower_finish(LF_draw_message, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_draw_tile_list(p0, p1) do { \
	int lm_ = lower_enter(LF_draw_tile_list); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.x = (uint16_t)(p1); \
		if (lm_ == 1) { lower_c_begin(LF_draw_tile_list); draw_tile_list(p0, p1); lower_c_end(LF_draw_tile_list); } \
		uint32_t lw_ = lower_run(LF_draw_tile_list, &lr_); \
		if (lm_ == 1) lower_finish(LF_draw_tile_list, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_text_task(p0, p1) do { \
	int lm_ = lower_enter(LF_text_task); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p1); \
		if (lm_ == 1) { lower_c_begin(LF_text_task); text_task(p0, p1); lower_c_end(LF_text_task); } \
		uint32_t lw_ = lower_run(LF_text_task, &lr_); \
		if (lm_ == 1) lower_finish(LF_text_task, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_draw_1up(p0) do { \
	int lm_ = lower_enter(LF_draw_1up); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_draw_1up); draw_1up(p0); lower_c_end(LF_draw_1up); } \
		uint32_t lw_ = lower_run(LF_draw_1up, &lr_); \
		if (lm_ == 1) lower_finish(LF_draw_1up, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_draw_2up(p0) do { \
	int lm_ = lower_enter(LF_draw_2up); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_draw_2up); draw_2up(p0); lower_c_end(LF_draw_2up); } \
		uint32_t lw_ = lower_run(LF_draw_2up, &lr_); \
		if (lm_ == 1) lower_finish(LF_draw_2up, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_clear_label(p0, p1) do { \
	int lm_ = lower_enter(LF_clear_label); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.x = (uint16_t)(p1); \
		if (lm_ == 1) { lower_c_begin(LF_clear_label); clear_label(p0, p1); lower_c_end(LF_clear_label); } \
		uint32_t lw_ = lower_run(LF_clear_label, &lr_); \
		if (lm_ == 1) lower_finish(LF_clear_label, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_update_lamps(p0, p1) do { \
	int lm_ = lower_enter(LF_update_lamps); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p1); \
		if (lm_ == 1) { lower_c_begin(LF_update_lamps); update_lamps(p0, p1); lower_c_end(LF_update_lamps); } \
		uint32_t lw_ = lower_run(LF_update_lamps, &lr_); \
		if (lm_ == 1) lower_finish(LF_update_lamps, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_hud_blink(p0) do { \
	int lm_ = lower_enter(LF_hud_blink); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_hud_blink); hud_blink(p0); lower_c_end(LF_hud_blink); } \
		uint32_t lw_ = lower_run(LF_hud_blink, &lr_); \
		if (lm_ == 1) lower_finish(LF_hud_blink, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_draw_score(p0, p1, p2, p3) do { \
	int lm_ = lower_enter(LF_draw_score); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.x = (uint16_t)(p1); \
		lr_.y = lower_mem_addr((const void *)(p2)); \
		lr_.a = (uint16_t)(uint8_t)(p3); \
		if (lm_ == 1) { lower_c_begin(LF_draw_score); draw_score(p0, p1, p2, p3); lower_c_end(LF_draw_score); } \
		uint32_t lw_ = lower_run(LF_draw_score, &lr_); \
		if (lm_ == 1) lower_finish(LF_draw_score, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_draw_player_score(p0, p1) do { \
	int lm_ = lower_enter(LF_draw_player_score); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_draw_player_score); draw_player_score(p0, p1); lower_c_end(LF_draw_player_score); } \
		uint32_t lw_ = lower_run(LF_draw_player_score, &lr_); \
		if (lm_ == 1) lower_finish(LF_draw_player_score, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_draw_lives(p0, p1) do { \
	int lm_ = lower_enter(LF_draw_lives); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p1); \
		if (lm_ == 1) { lower_c_begin(LF_draw_lives); draw_lives(p0, p1); lower_c_end(LF_draw_lives); } \
		uint32_t lw_ = lower_run(LF_draw_lives, &lr_); \
		if (lm_ == 1) lower_finish(LF_draw_lives, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_award_life(p0, p1, p2) do { \
	int lm_ = lower_enter(LF_award_life); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.x = lower_mem_addr((const void *)(p2)); \
		if (lm_ == 1) { lower_c_begin(LF_award_life); award_life(p0, p1, p2); lower_c_end(LF_award_life); } \
		uint32_t lw_ = lower_run(LF_award_life, &lr_); \
		if (lm_ == 1) lower_finish(LF_award_life, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_add_score(p0, p1) do { \
	int lm_ = lower_enter(LF_add_score); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p1); \
		if (lm_ == 1) { lower_c_begin(LF_add_score); add_score(p0, p1); lower_c_end(LF_add_score); } \
		uint32_t lw_ = lower_run(LF_add_score, &lr_); \
		if (lm_ == 1) lower_finish(LF_add_score, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_draw_lives_row(p0) do { \
	int lm_ = lower_enter(LF_draw_lives_row); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_draw_lives_row); draw_lives_row(p0); lower_c_end(LF_draw_lives_row); } \
		uint32_t lw_ = lower_run(LF_draw_lives_row, &lr_); \
		if (lm_ == 1) lower_finish(LF_draw_lives_row, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_draw_bonus_digits(p0) do { \
	int lm_ = lower_enter(LF_draw_bonus_digits); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_draw_bonus_digits); draw_bonus_digits(p0); lower_c_end(LF_draw_bonus_digits); } \
		uint32_t lw_ = lower_run(LF_draw_bonus_digits, &lr_); \
		if (lm_ == 1) lower_finish(LF_draw_bonus_digits, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_read_dip_switches(p0) do { \
	int lm_ = lower_enter(LF_read_dip_switches); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_read_dip_switches); read_dip_switches(p0); lower_c_end(LF_read_dip_switches); } \
		uint32_t lw_ = lower_run(LF_read_dip_switches, &lr_); \
		if (lm_ == 1) lower_finish(LF_read_dip_switches, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_draw_scores(p0) do { \
	int lm_ = lower_enter(LF_draw_scores); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_draw_scores); draw_scores(p0); lower_c_end(LF_draw_scores); } \
		uint32_t lw_ = lower_run(LF_draw_scores, &lr_); \
		if (lm_ == 1) lower_finish(LF_draw_scores, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_show_credits(p0) do { \
	int lm_ = lower_enter(LF_show_credits); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_show_credits); show_credits(p0); lower_c_end(LF_show_credits); } \
		uint32_t lw_ = lower_run(LF_show_credits, &lr_); \
		if (lm_ == 1) lower_finish(LF_show_credits, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_draw_midway_logo(p0) do { \
	int lm_ = lower_enter(LF_draw_midway_logo); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_draw_midway_logo); draw_midway_logo(p0); lower_c_end(LF_draw_midway_logo); } \
		uint32_t lw_ = lower_run(LF_draw_midway_logo, &lr_); \
		if (lm_ == 1) lower_finish(LF_draw_midway_logo, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_marquee_bulbs(p0) do { \
	int lm_ = lower_enter(LF_marquee_bulbs); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_marquee_bulbs); marquee_bulbs(p0); lower_c_end(LF_marquee_bulbs); } \
		uint32_t lw_ = lower_run(LF_marquee_bulbs, &lr_); \
		if (lm_ == 1) lower_finish(LF_marquee_bulbs, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_show_card(p0, p1) do { \
	int lm_ = lower_enter(LF_show_card); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p1); \
		if (lm_ == 1) { lower_c_begin(LF_show_card); show_card(p0, p1); lower_c_end(LF_show_card); } \
		uint32_t lw_ = lower_run(LF_show_card, &lr_); \
		if (lm_ == 1) lower_finish(LF_show_card, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_open_marquee(p0) do { \
	int lm_ = lower_enter(LF_open_marquee); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_open_marquee); open_marquee(p0); lower_c_end(LF_open_marquee); } \
		uint32_t lw_ = lower_run(LF_open_marquee, &lr_); \
		if (lm_ == 1) lower_finish(LF_open_marquee, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_attract_step(p0) do { \
	int lm_ = lower_enter(LF_attract_step); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_attract_step); attract_step(p0); lower_c_end(LF_attract_step); } \
		uint32_t lw_ = lower_run(LF_attract_step, &lr_); \
		if (lm_ == 1) lower_finish(LF_attract_step, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_maze_word(p0, p1) do { \
	int lm_ = lower_enter(LF_maze_word); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.x = (uint16_t)(p1); \
		uint32_t lc_ = 0; \
		if (lm_ == 1) { lower_c_begin(LF_maze_word); lc_ = (uint32_t)(maze_word(p0, p1)) & 0xFFFFu; lower_c_end(LF_maze_word); } \
		uint32_t lw_ = lower_run(LF_maze_word, &lr_); \
		if (lm_ == 1) lower_finish(LF_maze_word, lc_, lw_, &lr_); \
		uint32_t lr2_ = lm_ == 1 ? lc_ : lw_; \
		return (uint16_t)lr2_; \
	} \
} while (0)

#define LH_power_pill_cell(p0, p1) do { \
	int lm_ = lower_enter(LF_power_pill_cell); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p1); \
		uint32_t lc_ = 0; \
		if (lm_ == 1) { lower_c_begin(LF_power_pill_cell); lc_ = (uint32_t)(power_pill_cell(p0, p1)) & 0xFFFFu; lower_c_end(LF_power_pill_cell); } \
		uint32_t lw_ = lower_run(LF_power_pill_cell, &lr_); \
		if (lm_ == 1) lower_finish(LF_power_pill_cell, lc_, lw_, &lr_); \
		uint32_t lr2_ = lm_ == 1 ? lc_ : lw_; \
		return (uint16_t)lr2_; \
	} \
} while (0)

#define LH_flash_power_pills(p0) do { \
	int lm_ = lower_enter(LF_flash_power_pills); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_flash_power_pills); flash_power_pills(p0); lower_c_end(LF_flash_power_pills); } \
		uint32_t lw_ = lower_run(LF_flash_power_pills, &lr_); \
		if (lm_ == 1) lower_finish(LF_flash_power_pills, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_pill_bitmap(p0) do { \
	int lm_ = lower_enter(LF_pill_bitmap); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_pill_bitmap); pill_bitmap(p0); lower_c_end(LF_pill_bitmap); } \
		uint32_t lw_ = lower_run(LF_pill_bitmap, &lr_); \
		if (lm_ == 1) lower_finish(LF_pill_bitmap, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_reset_pills(p0) do { \
	int lm_ = lower_enter(LF_reset_pills); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_reset_pills); reset_pills(p0); lower_c_end(LF_reset_pills); } \
		uint32_t lw_ = lower_run(LF_reset_pills, &lr_); \
		if (lm_ == 1) lower_finish(LF_reset_pills, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_draw_pills(p0) do { \
	int lm_ = lower_enter(LF_draw_pills); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_draw_pills); draw_pills(p0); lower_c_end(LF_draw_pills); } \
		uint32_t lw_ = lower_run(LF_draw_pills, &lr_); \
		if (lm_ == 1) lower_finish(LF_draw_pills, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_erase_pills(p0) do { \
	int lm_ = lower_enter(LF_erase_pills); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_erase_pills); erase_pills(p0); lower_c_end(LF_erase_pills); } \
		uint32_t lw_ = lower_run(LF_erase_pills, &lr_); \
		if (lm_ == 1) lower_finish(LF_erase_pills, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_clear_colors(p0) do { \
	int lm_ = lower_enter(LF_clear_colors); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_clear_colors); clear_colors(p0); lower_c_end(LF_clear_colors); } \
		uint32_t lw_ = lower_run(LF_clear_colors, &lr_); \
		if (lm_ == 1) lower_finish(LF_clear_colors, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_clear_screen(p0, p1) do { \
	int lm_ = lower_enter(LF_clear_screen); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p1); \
		if (lm_ == 1) { lower_c_begin(LF_clear_screen); clear_screen(p0, p1); lower_c_end(LF_clear_screen); } \
		uint32_t lw_ = lower_run(LF_clear_screen, &lr_); \
		if (lm_ == 1) lower_finish(LF_clear_screen, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_draw_maze(p0) do { \
	int lm_ = lower_enter(LF_draw_maze); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_draw_maze); draw_maze(p0); lower_c_end(LF_draw_maze); } \
		uint32_t lw_ = lower_run(LF_draw_maze, &lr_); \
		if (lm_ == 1) lower_finish(LF_draw_maze, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_wall_color(p0, p1) do { \
	int lm_ = lower_enter(LF_wall_color); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p1); \
		uint32_t lc_ = 0; \
		if (lm_ == 1) { lower_c_begin(LF_wall_color); lc_ = (uint32_t)(wall_color(p0, p1)) & 0xFFu; lower_c_end(LF_wall_color); } \
		uint32_t lw_ = lower_run(LF_wall_color, &lr_); \
		if (lm_ == 1) lower_finish(LF_wall_color, lc_, lw_, &lr_); \
		uint32_t lr2_ = lm_ == 1 ? lc_ : lw_; \
		return (uint8_t)lr2_; \
	} \
} while (0)

#define LH_maze_colors(p0, p1) do { \
	int lm_ = lower_enter(LF_maze_colors); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p1); \
		if (lm_ == 1) { lower_c_begin(LF_maze_colors); maze_colors(p0, p1); lower_c_end(LF_maze_colors); } \
		uint32_t lw_ = lower_run(LF_maze_colors, &lr_); \
		if (lm_ == 1) lower_finish(LF_maze_colors, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_demo_mode(p0) do { \
	int lm_ = lower_enter(LF_demo_mode); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_demo_mode); demo_mode(p0); lower_c_end(LF_demo_mode); } \
		uint32_t lw_ = lower_run(LF_demo_mode, &lr_); \
		if (lm_ == 1) lower_finish(LF_demo_mode, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_clear_actors(p0) do { \
	int lm_ = lower_enter(LF_clear_actors); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_clear_actors); clear_actors(p0); lower_c_end(LF_clear_actors); } \
		uint32_t lw_ = lower_run(LF_clear_actors, &lr_); \
		if (lm_ == 1) lower_finish(LF_clear_actors, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_house_timer(p0, p1) do { \
	int lm_ = lower_enter(LF_house_timer); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p1); \
		if (lm_ == 1) { lower_c_begin(LF_house_timer); house_timer(p0, p1); lower_c_end(LF_house_timer); } \
		uint32_t lw_ = lower_run(LF_house_timer, &lr_); \
		if (lm_ == 1) lower_finish(LF_house_timer, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_place_actors(p0, p1) do { \
	int lm_ = lower_enter(LF_place_actors); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p1); \
		if (lm_ == 1) { lower_c_begin(LF_place_actors); place_actors(p0, p1); lower_c_end(LF_place_actors); } \
		uint32_t lw_ = lower_run(LF_place_actors, &lr_); \
		if (lm_ == 1) lower_finish(LF_place_actors, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_add_coin(p0) do { \
	int lm_ = lower_enter(LF_add_coin); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_add_coin); add_coin(p0); lower_c_end(LF_add_coin); } \
		uint32_t lw_ = lower_run(LF_add_coin, &lr_); \
		if (lm_ == 1) lower_finish(LF_add_coin, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_coin_meter(p0) do { \
	int lm_ = lower_enter(LF_coin_meter); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_coin_meter); coin_meter(p0); lower_c_end(LF_coin_meter); } \
		uint32_t lw_ = lower_run(LF_coin_meter, &lr_); \
		if (lm_ == 1) lower_finish(LF_coin_meter, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_coin_inputs(p0) do { \
	int lm_ = lower_enter(LF_coin_inputs); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_coin_inputs); coin_inputs(p0); lower_c_end(LF_coin_inputs); } \
		uint32_t lw_ = lower_run(LF_coin_inputs, &lr_); \
		if (lm_ == 1) lower_finish(LF_coin_inputs, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_clock_tick(p0) do { \
	int lm_ = lower_enter(LF_clock_tick); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_clock_tick); clock_tick(p0); lower_c_end(LF_clock_tick); } \
		uint32_t lw_ = lower_run(LF_clock_tick, &lr_); \
		if (lm_ == 1) lower_finish(LF_clock_tick, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_advance_level_state(p0) do { \
	int lm_ = lower_enter(LF_advance_level_state); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_advance_level_state); advance_level_state(p0); lower_c_end(LF_advance_level_state); } \
		uint32_t lw_ = lower_run(LF_advance_level_state, &lr_); \
		if (lm_ == 1) lower_finish(LF_advance_level_state, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_advance_play_state(p0) do { \
	int lm_ = lower_enter(LF_advance_play_state); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_advance_play_state); advance_play_state(p0); lower_c_end(LF_advance_play_state); } \
		uint32_t lw_ = lower_run(LF_advance_play_state, &lr_); \
		if (lm_ == 1) lower_finish(LF_advance_play_state, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_advance_attract_state(p0) do { \
	int lm_ = lower_enter(LF_advance_attract_state); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_advance_attract_state); advance_attract_state(p0); lower_c_end(LF_advance_attract_state); } \
		uint32_t lw_ = lower_run(LF_advance_attract_state, &lr_); \
		if (lm_ == 1) lower_finish(LF_advance_attract_state, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_advance_eaten_ghost_anim(p0) do { \
	int lm_ = lower_enter(LF_advance_eaten_ghost_anim); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_advance_eaten_ghost_anim); advance_eaten_ghost_anim(p0); lower_c_end(LF_advance_eaten_ghost_anim); } \
		uint32_t lw_ = lower_run(LF_advance_eaten_ghost_anim, &lr_); \
		if (lm_ == 1) lower_finish(LF_advance_eaten_ghost_anim, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_clear_ready(p0) do { \
	int lm_ = lower_enter(LF_clear_ready); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_clear_ready); clear_ready(p0); lower_c_end(LF_clear_ready); } \
		uint32_t lw_ = lower_run(LF_clear_ready, &lr_); \
		if (lm_ == 1) lower_finish(LF_clear_ready, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_advance_cutscene1(p0) do { \
	int lm_ = lower_enter(LF_advance_cutscene1); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_advance_cutscene1); advance_cutscene1(p0); lower_c_end(LF_advance_cutscene1); } \
		uint32_t lw_ = lower_run(LF_advance_cutscene1, &lr_); \
		if (lm_ == 1) lower_finish(LF_advance_cutscene1, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_advance_cutscene2(p0) do { \
	int lm_ = lower_enter(LF_advance_cutscene2); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_advance_cutscene2); advance_cutscene2(p0); lower_c_end(LF_advance_cutscene2); } \
		uint32_t lw_ = lower_run(LF_advance_cutscene2, &lr_); \
		if (lm_ == 1) lower_finish(LF_advance_cutscene2, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_advance_cutscene3(p0) do { \
	int lm_ = lower_enter(LF_advance_cutscene3); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_advance_cutscene3); advance_cutscene3(p0); lower_c_end(LF_advance_cutscene3); } \
		uint32_t lw_ = lower_run(LF_advance_cutscene3, &lr_); \
		if (lm_ == 1) lower_finish(LF_advance_cutscene3, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_timers_run(p0) do { \
	int lm_ = lower_enter(LF_timers_run); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_timers_run); timers_run(p0); lower_c_end(LF_timers_run); } \
		uint32_t lw_ = lower_run(LF_timers_run, &lr_); \
		if (lm_ == 1) lower_finish(LF_timers_run, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_queue_timed(p0, p1, p2, p3) do { \
	int lm_ = lower_enter(LF_queue_timed); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p1); \
		lr_.x = (uint16_t)(uint8_t)(p2); \
		lr_.y = (uint16_t)(uint8_t)(p3); \
		uint32_t lc_ = 0; \
		if (lm_ == 1) { lower_c_begin(LF_queue_timed); lc_ = (uint32_t)(queue_timed(p0, p1, p2, p3)) & 0xFFu; lower_c_end(LF_queue_timed); } \
		uint32_t lw_ = lower_run(LF_queue_timed, &lr_); \
		if (lm_ == 1) lower_finish(LF_queue_timed, lc_, lw_, &lr_); \
		uint32_t lr2_ = lm_ == 1 ? lc_ : lw_; \
		return (uint8_t)lr2_; \
	} \
} while (0)

#define LH_clear_fruit(p0) do { \
	int lm_ = lower_enter(LF_clear_fruit); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_clear_fruit); clear_fruit(p0); lower_c_end(LF_clear_fruit); } \
		uint32_t lw_ = lower_run(LF_clear_fruit, &lr_); \
		if (lm_ == 1) lower_finish(LF_clear_fruit, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_clear_fruit_pos(p0) do { \
	int lm_ = lower_enter(LF_clear_fruit_pos); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_clear_fruit_pos); clear_fruit_pos(p0); lower_c_end(LF_clear_fruit_pos); } \
		uint32_t lw_ = lower_run(LF_clear_fruit_pos, &lr_); \
		if (lm_ == 1) lower_finish(LF_clear_fruit_pos, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_choose_path(p0, p1) do { \
	int lm_ = lower_enter(LF_choose_path); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.x = (uint16_t)(p1); \
		uint32_t lc_ = 0; \
		if (lm_ == 1) { lower_c_begin(LF_choose_path); lc_ = (uint32_t)(choose_path(p0, p1)) & 0xFFFFu; lower_c_end(LF_choose_path); } \
		uint32_t lw_ = lower_run(LF_choose_path, &lr_); \
		if (lm_ == 1) lower_finish(LF_choose_path, lc_, lw_, &lr_); \
		uint32_t lr2_ = lm_ == 1 ? lc_ : lw_; \
		return (uint16_t)lr2_; \
	} \
} while (0)

#define LH_release_fruit(p0) do { \
	int lm_ = lower_enter(LF_release_fruit); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_release_fruit); release_fruit(p0); lower_c_end(LF_release_fruit); } \
		uint32_t lw_ = lower_run(LF_release_fruit, &lr_); \
		if (lm_ == 1) lower_finish(LF_release_fruit, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_next_bounce(p0, p1) do { \
	int lm_ = lower_enter(LF_next_bounce); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p1); \
		if (lm_ == 1) { lower_c_begin(LF_next_bounce); next_bounce(p0, p1); lower_c_end(LF_next_bounce); } \
		uint32_t lw_ = lower_run(LF_next_bounce, &lr_); \
		if (lm_ == 1) lower_finish(LF_next_bounce, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_end_of_path(p0) do { \
	int lm_ = lower_enter(LF_end_of_path); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_end_of_path); end_of_path(p0); lower_c_end(LF_end_of_path); } \
		uint32_t lw_ = lower_run(LF_end_of_path, &lr_); \
		if (lm_ == 1) lower_finish(LF_end_of_path, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_move_fruit(p0) do { \
	int lm_ = lower_enter(LF_move_fruit); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_move_fruit); move_fruit(p0); lower_c_end(LF_move_fruit); } \
		uint32_t lw_ = lower_run(LF_move_fruit, &lr_); \
		if (lm_ == 1) lower_finish(LF_move_fruit, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_best_dir(p0, p1, p2, p3) do { \
	int lm_ = lower_enter(LF_best_dir); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.x = lower_coord_word(p1); \
		lr_.y = lower_coord_word(p2); \
		lr_.a = (uint16_t)(uint8_t)(p3); \
		uint32_t lc_ = 0; \
		if (lm_ == 1) { lower_c_begin(LF_best_dir); lc_ = (uint32_t)(best_dir(p0, p1, p2, p3)) & 0xFFu; lower_c_end(LF_best_dir); } \
		uint32_t lw_ = lower_run(LF_best_dir, &lr_); \
		if (lm_ == 1) lower_finish(LF_best_dir, lc_, lw_, &lr_); \
		uint32_t lr2_ = lm_ == 1 ? lc_ : lw_; \
		return (uint8_t)lr2_; \
	} \
} while (0)

#define LH_random_dir(p0, p1, p2) do { \
	int lm_ = lower_enter(LF_random_dir); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.x = lower_coord_word(p1); \
		lr_.a = (uint16_t)(uint8_t)(p2); \
		uint32_t lc_ = 0; \
		if (lm_ == 1) { lower_c_begin(LF_random_dir); lc_ = (uint32_t)(random_dir(p0, p1, p2)) & 0xFFu; lower_c_end(LF_random_dir); } \
		uint32_t lw_ = lower_run(LF_random_dir, &lr_); \
		if (lm_ == 1) lower_finish(LF_random_dir, lc_, lw_, &lr_); \
		uint32_t lr2_ = lm_ == 1 ? lc_ : lw_; \
		return (uint8_t)lr2_; \
	} \
} while (0)

#define LH_random_corner(p0) do { \
	int lm_ = lower_enter(LF_random_corner); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		Coord lc_c = {0, 0}; uint32_t lc_ = 0; \
		if (lm_ == 1) { lower_c_begin(LF_random_corner); lc_c = random_corner(p0); lc_ = lower_coord_word(lc_c); lower_c_end(LF_random_corner); } \
		uint32_t lw_ = lower_run(LF_random_corner, &lr_); \
		if (lm_ == 1) lower_finish(LF_random_corner, lc_, lw_, &lr_); \
		uint32_t lr2_ = lm_ == 1 ? lc_ : lw_; \
		return lower_word_coord((uint16_t)lr2_); \
	} \
} while (0)

#define LH_aim_red(p0) do { \
	int lm_ = lower_enter(LF_aim_red); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_aim_red); aim_red(p0); lower_c_end(LF_aim_red); } \
		uint32_t lw_ = lower_run(LF_aim_red, &lr_); \
		if (lm_ == 1) lower_finish(LF_aim_red, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_aim_pink(p0) do { \
	int lm_ = lower_enter(LF_aim_pink); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_aim_pink); aim_pink(p0); lower_c_end(LF_aim_pink); } \
		uint32_t lw_ = lower_run(LF_aim_pink, &lr_); \
		if (lm_ == 1) lower_finish(LF_aim_pink, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_aim_blue(p0) do { \
	int lm_ = lower_enter(LF_aim_blue); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_aim_blue); aim_blue(p0); lower_c_end(LF_aim_blue); } \
		uint32_t lw_ = lower_run(LF_aim_blue, &lr_); \
		if (lm_ == 1) lower_finish(LF_aim_blue, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_aim_orange(p0) do { \
	int lm_ = lower_enter(LF_aim_orange); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_aim_orange); aim_orange(p0); lower_c_end(LF_aim_orange); } \
		uint32_t lw_ = lower_run(LF_aim_orange, &lr_); \
		if (lm_ == 1) lower_finish(LF_aim_orange, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_demo_steer(p0) do { \
	int lm_ = lower_enter(LF_demo_steer); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_demo_steer); demo_steer(p0); lower_c_end(LF_demo_steer); } \
		uint32_t lw_ = lower_run(LF_demo_steer, &lr_); \
		if (lm_ == 1) lower_finish(LF_demo_steer, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_color_eyes(p0) do { \
	int lm_ = lower_enter(LF_color_eyes); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_color_eyes); color_eyes(p0); lower_c_end(LF_color_eyes); } \
		uint32_t lw_ = lower_run(LF_color_eyes, &lr_); \
		if (lm_ == 1) lower_finish(LF_color_eyes, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_start_fright(p0) do { \
	int lm_ = lower_enter(LF_start_fright); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_start_fright); start_fright(p0); lower_c_end(LF_start_fright); } \
		uint32_t lw_ = lower_run(LF_start_fright, &lr_); \
		if (lm_ == 1) lower_finish(LF_start_fright, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_fright_countdown(p0) do { \
	int lm_ = lower_enter(LF_fright_countdown); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_fright_countdown); fright_countdown(p0); lower_c_end(LF_fright_countdown); } \
		uint32_t lw_ = lower_run(LF_fright_countdown, &lr_); \
		if (lm_ == 1) lower_finish(LF_fright_countdown, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_flash_ghosts(p0) do { \
	int lm_ = lower_enter(LF_flash_ghosts); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_flash_ghosts); flash_ghosts(p0); lower_c_end(LF_flash_ghosts); } \
		uint32_t lw_ = lower_run(LF_flash_ghosts, &lr_); \
		if (lm_ == 1) lower_finish(LF_flash_ghosts, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_ghost_hit(p0, p1) do { \
	int lm_ = lower_enter(LF_ghost_hit); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p1); \
		if (lm_ == 1) { lower_c_begin(LF_ghost_hit); ghost_hit(p0, p1); lower_c_end(LF_ghost_hit); } \
		uint32_t lw_ = lower_run(LF_ghost_hit, &lr_); \
		if (lm_ == 1) lower_finish(LF_ghost_hit, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_tile_collision(p0) do { \
	int lm_ = lower_enter(LF_tile_collision); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_tile_collision); tile_collision(p0); lower_c_end(LF_tile_collision); } \
		uint32_t lw_ = lower_run(LF_tile_collision, &lr_); \
		if (lm_ == 1) lower_finish(LF_tile_collision, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_pixel_collision(p0) do { \
	int lm_ = lower_enter(LF_pixel_collision); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_pixel_collision); pixel_collision(p0); lower_c_end(LF_pixel_collision); } \
		uint32_t lw_ = lower_run(LF_pixel_collision, &lr_); \
		if (lm_ == 1) lower_finish(LF_pixel_collision, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_show_eaten_ghost(p0) do { \
	int lm_ = lower_enter(LF_show_eaten_ghost); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_show_eaten_ghost); show_eaten_ghost(p0); lower_c_end(LF_show_eaten_ghost); } \
		uint32_t lw_ = lower_run(LF_show_eaten_ghost, &lr_); \
		if (lm_ == 1) lower_finish(LF_show_eaten_ghost, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_move_ghosts(p0) do { \
	int lm_ = lower_enter(LF_move_ghosts); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_move_ghosts); move_ghosts(p0); lower_c_end(LF_move_ghosts); } \
		uint32_t lw_ = lower_run(LF_move_ghosts, &lr_); \
		if (lm_ == 1) lower_finish(LF_move_ghosts, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_return_all_eyes(p0) do { \
	int lm_ = lower_enter(LF_return_all_eyes); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_return_all_eyes); return_all_eyes(p0); lower_c_end(LF_return_all_eyes); } \
		uint32_t lw_ = lower_run(LF_return_all_eyes, &lr_); \
		if (lm_ == 1) lower_finish(LF_return_all_eyes, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_mark_eaten_ghost(p0) do { \
	int lm_ = lower_enter(LF_mark_eaten_ghost); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_mark_eaten_ghost); mark_eaten_ghost(p0); lower_c_end(LF_mark_eaten_ghost); } \
		uint32_t lw_ = lower_run(LF_mark_eaten_ghost, &lr_); \
		if (lm_ == 1) lower_finish(LF_mark_eaten_ghost, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_move_in_house(p0) do { \
	int lm_ = lower_enter(LF_move_in_house); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_move_in_house); move_in_house(p0); lower_c_end(LF_move_in_house); } \
		uint32_t lw_ = lower_run(LF_move_in_house, &lr_); \
		if (lm_ == 1) lower_finish(LF_move_in_house, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_release_by_pills(p0) do { \
	int lm_ = lower_enter(LF_release_by_pills); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_release_by_pills); release_by_pills(p0); lower_c_end(LF_release_by_pills); } \
		uint32_t lw_ = lower_run(LF_release_by_pills, &lr_); \
		if (lm_ == 1) lower_finish(LF_release_by_pills, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_count_house_pill(p0) do { \
	int lm_ = lower_enter(LF_count_house_pill); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_count_house_pill); count_house_pill(p0); lower_c_end(LF_count_house_pill); } \
		uint32_t lw_ = lower_run(LF_count_house_pill, &lr_); \
		if (lm_ == 1) lower_finish(LF_count_house_pill, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_release_idle_ghost(p0) do { \
	int lm_ = lower_enter(LF_release_idle_ghost); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_release_idle_ghost); release_idle_ghost(p0); lower_c_end(LF_release_idle_ghost); } \
		uint32_t lw_ = lower_run(LF_release_idle_ghost, &lr_); \
		if (lm_ == 1) lower_finish(LF_release_idle_ghost, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_ghost_anim_tick(p0) do { \
	int lm_ = lower_enter(LF_ghost_anim_tick); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_ghost_anim_tick); ghost_anim_tick(p0); lower_c_end(LF_ghost_anim_tick); } \
		uint32_t lw_ = lower_run(LF_ghost_anim_tick, &lr_); \
		if (lm_ == 1) lower_finish(LF_ghost_anim_tick, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_reversal_timer(p0) do { \
	int lm_ = lower_enter(LF_reversal_timer); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_reversal_timer); reversal_timer(p0); lower_c_end(LF_reversal_timer); } \
		uint32_t lw_ = lower_run(LF_reversal_timer, &lr_); \
		if (lm_ == 1) lower_finish(LF_reversal_timer, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_wall_ahead(p0, p1) do { \
	int lm_ = lower_enter(LF_wall_ahead); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.x = lower_coord_word(p1); \
		uint32_t lc_ = 0; \
		if (lm_ == 1) { lower_c_begin(LF_wall_ahead); lc_ = (uint32_t)(wall_ahead(p0, p1)) & 0xFFu; lower_c_end(LF_wall_ahead); } \
		uint32_t lw_ = lower_run(LF_wall_ahead, &lr_); \
		if (lm_ == 1) lower_finish(LF_wall_ahead, lc_, lw_, &lr_); \
		uint32_t lr2_ = lm_ == 1 ? lc_ : lw_; \
		return (uint8_t)lr2_; \
	} \
} while (0)

#define LH_eat_pill(p0) do { \
	int lm_ = lower_enter(LF_eat_pill); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_eat_pill); eat_pill(p0); lower_c_end(LF_eat_pill); } \
		uint32_t lw_ = lower_run(LF_eat_pill, &lr_); \
		if (lm_ == 1) lower_finish(LF_eat_pill, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_arrive(p0, p1) do { \
	int lm_ = lower_enter(LF_arrive); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.x = lower_coord_word(p1); \
		if (lm_ == 1) { lower_c_begin(LF_arrive); arrive(p0, p1); lower_c_end(LF_arrive); } \
		uint32_t lw_ = lower_run(LF_arrive, &lr_); \
		if (lm_ == 1) lower_finish(LF_arrive, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_pac_step(p0) do { \
	int lm_ = lower_enter(LF_pac_step); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_pac_step); pac_step(p0); lower_c_end(LF_pac_step); } \
		uint32_t lw_ = lower_run(LF_pac_step, &lr_); \
		if (lm_ == 1) lower_finish(LF_pac_step, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_adopt(p0, p1) do { \
	int lm_ = lower_enter(LF_adopt); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p1); \
		if (lm_ == 1) { lower_c_begin(LF_adopt); adopt(p0, p1); lower_c_end(LF_adopt); } \
		uint32_t lw_ = lower_run(LF_adopt, &lr_); \
		if (lm_ == 1) lower_finish(LF_adopt, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_try_turn(p0, p1) do { \
	int lm_ = lower_enter(LF_try_turn); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p1); \
		if (lm_ == 1) { lower_c_begin(LF_try_turn); try_turn(p0, p1); lower_c_end(LF_try_turn); } \
		uint32_t lw_ = lower_run(LF_try_turn, &lr_); \
		if (lm_ == 1) lower_finish(LF_try_turn, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_want(p0, p1) do { \
	int lm_ = lower_enter(LF_want); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p1); \
		if (lm_ == 1) { lower_c_begin(LF_want); want(p0, p1); lower_c_end(LF_want); } \
		uint32_t lw_ = lower_run(LF_want, &lr_); \
		if (lm_ == 1) lower_finish(LF_want, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_face(p0, p1) do { \
	int lm_ = lower_enter(LF_face); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p1); \
		if (lm_ == 1) { lower_c_begin(LF_face); face(p0, p1); lower_c_end(LF_face); } \
		uint32_t lw_ = lower_run(LF_face, &lr_); \
		if (lm_ == 1) lower_finish(LF_face, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_demo_move(p0) do { \
	int lm_ = lower_enter(LF_demo_move); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_demo_move); demo_move(p0); lower_c_end(LF_demo_move); } \
		uint32_t lw_ = lower_run(LF_demo_move, &lr_); \
		if (lm_ == 1) lower_finish(LF_demo_move, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_steer(p0, p1, p2) do { \
	int lm_ = lower_enter(LF_steer); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p1); \
		lr_.x = (uint16_t)(uint8_t)(p2); \
		if (lm_ == 1) { lower_c_begin(LF_steer); steer(p0, p1, p2); lower_c_end(LF_steer); } \
		uint32_t lw_ = lower_run(LF_steer, &lr_); \
		if (lm_ == 1) lower_finish(LF_steer, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_move_pac(p0) do { \
	int lm_ = lower_enter(LF_move_pac); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_move_pac); move_pac(p0); lower_c_end(LF_move_pac); } \
		uint32_t lw_ = lower_run(LF_move_pac, &lr_); \
		if (lm_ == 1) lower_finish(LF_move_pac, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_clear_actor_positions(p0) do { \
	int lm_ = lower_enter(LF_clear_actor_positions); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_clear_actor_positions); clear_actor_positions(p0); lower_c_end(LF_clear_actor_positions); } \
		uint32_t lw_ = lower_run(LF_clear_actor_positions, &lr_); \
		if (lm_ == 1) lower_finish(LF_clear_actor_positions, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_pac_death(p0) do { \
	int lm_ = lower_enter(LF_pac_death); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_pac_death); pac_death(p0); lower_c_end(LF_pac_death); } \
		uint32_t lw_ = lower_run(LF_pac_death, &lr_); \
		if (lm_ == 1) lower_finish(LF_pac_death, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_sound_effects(p0) do { \
	int lm_ = lower_enter(LF_sound_effects); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_sound_effects); sound_effects(p0); lower_c_end(LF_sound_effects); } \
		uint32_t lw_ = lower_run(LF_sound_effects, &lr_); \
		if (lm_ == 1) lower_finish(LF_sound_effects, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_sound_songs(p0) do { \
	int lm_ = lower_enter(LF_sound_songs); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_sound_songs); sound_songs(p0); lower_c_end(LF_sound_songs); } \
		uint32_t lw_ = lower_run(LF_sound_songs, &lr_); \
		if (lm_ == 1) lower_finish(LF_sound_songs, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_cutscene2_sprites(p0) do { \
	int lm_ = lower_enter(LF_cutscene2_sprites); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_cutscene2_sprites); cutscene2_sprites(p0); lower_c_end(LF_cutscene2_sprites); } \
		uint32_t lw_ = lower_run(LF_cutscene2_sprites, &lr_); \
		if (lm_ == 1) lower_finish(LF_cutscene2_sprites, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_cutscene1_positions(p0) do { \
	int lm_ = lower_enter(LF_cutscene1_positions); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_cutscene1_positions); cutscene1_positions(p0); lower_c_end(LF_cutscene1_positions); } \
		uint32_t lw_ = lower_run(LF_cutscene1_positions, &lr_); \
		if (lm_ == 1) lower_finish(LF_cutscene1_positions, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_cutscene3_sprites(p0) do { \
	int lm_ = lower_enter(LF_cutscene3_sprites); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_cutscene3_sprites); cutscene3_sprites(p0); lower_c_end(LF_cutscene3_sprites); } \
		uint32_t lw_ = lower_run(LF_cutscene3_sprites, &lr_); \
		if (lm_ == 1) lower_finish(LF_cutscene3_sprites, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_cutscene1_sprites(p0) do { \
	int lm_ = lower_enter(LF_cutscene1_sprites); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_cutscene1_sprites); cutscene1_sprites(p0); lower_c_end(LF_cutscene1_sprites); } \
		uint32_t lw_ = lower_run(LF_cutscene1_sprites, &lr_); \
		if (lm_ == 1) lower_finish(LF_cutscene1_sprites, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_load_scripts(p0, p1) do { \
	int lm_ = lower_enter(LF_load_scripts); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p1); \
		if (lm_ == 1) { lower_c_begin(LF_load_scripts); load_scripts(p0, p1); lower_c_end(LF_load_scripts); } \
		uint32_t lw_ = lower_run(LF_load_scripts, &lr_); \
		if (lm_ == 1) lower_finish(LF_load_scripts, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_run_cutscene(p0, p1) do { \
	int lm_ = lower_enter(LF_run_cutscene); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p1); \
		if (lm_ == 1) { lower_c_begin(LF_run_cutscene); run_cutscene(p0, p1); lower_c_end(LF_run_cutscene); } \
		uint32_t lw_ = lower_run(LF_run_cutscene, &lr_); \
		if (lm_ == 1) lower_finish(LF_run_cutscene, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_run_act(p0, p1) do { \
	int lm_ = lower_enter(LF_run_act); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p1); \
		if (lm_ == 1) { lower_c_begin(LF_run_act); run_act(p0, p1); lower_c_end(LF_run_act); } \
		uint32_t lw_ = lower_run(LF_run_act, &lr_); \
		if (lm_ == 1) lower_finish(LF_run_act, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_sprites_upright(p0) do { \
	int lm_ = lower_enter(LF_sprites_upright); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_sprites_upright); sprites_upright(p0); lower_c_end(LF_sprites_upright); } \
		uint32_t lw_ = lower_run(LF_sprites_upright, &lr_); \
		if (lm_ == 1) lower_finish(LF_sprites_upright, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_sprites_cocktail(p0) do { \
	int lm_ = lower_enter(LF_sprites_cocktail); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_sprites_cocktail); sprites_cocktail(p0); lower_c_end(LF_sprites_cocktail); } \
		uint32_t lw_ = lower_run(LF_sprites_cocktail, &lr_); \
		if (lm_ == 1) lower_finish(LF_sprites_cocktail, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_play_pass(p0) do { \
	int lm_ = lower_enter(LF_play_pass); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_play_pass); play_pass(p0); lower_c_end(LF_play_pass); } \
		uint32_t lw_ = lower_run(LF_play_pass, &lr_); \
		if (lm_ == 1) lower_finish(LF_play_pass, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_play_frame(p0) do { \
	int lm_ = lower_enter(LF_play_frame); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_play_frame); play_frame(p0); lower_c_end(LF_play_frame); } \
		uint32_t lw_ = lower_run(LF_play_frame, &lr_); \
		if (lm_ == 1) lower_finish(LF_play_frame, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_draw_prompt(p0, p1) do { \
	int lm_ = lower_enter(LF_draw_prompt); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_draw_prompt); draw_prompt(p0, p1); lower_c_end(LF_draw_prompt); } \
		uint32_t lw_ = lower_run(LF_draw_prompt, &lr_); \
		if (lm_ == 1) lower_finish(LF_draw_prompt, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_begin_game(p0, p1) do { \
	int lm_ = lower_enter(LF_begin_game); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_begin_game); begin_game(p0, p1); lower_c_end(LF_begin_game); } \
		uint32_t lw_ = lower_run(LF_begin_game, &lr_); \
		if (lm_ == 1) lower_finish(LF_begin_game, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_wait_start(p0, p1) do { \
	int lm_ = lower_enter(LF_wait_start); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_wait_start); wait_start(p0, p1); lower_c_end(LF_wait_start); } \
		uint32_t lw_ = lower_run(LF_wait_start, &lr_); \
		if (lm_ == 1) lower_finish(LF_wait_start, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_set_up_game(p0, p1) do { \
	int lm_ = lower_enter(LF_set_up_game); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_set_up_game); set_up_game(p0, p1); lower_c_end(LF_set_up_game); } \
		uint32_t lw_ = lower_run(LF_set_up_game, &lr_); \
		if (lm_ == 1) lower_finish(LF_set_up_game, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_start_play(p0, p1) do { \
	int lm_ = lower_enter(LF_start_play); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_start_play); start_play(p0, p1); lower_c_end(LF_start_play); } \
		uint32_t lw_ = lower_run(LF_start_play, &lr_); \
		if (lm_ == 1) lower_finish(LF_start_play, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_press_start(p0) do { \
	int lm_ = lower_enter(LF_press_start); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_press_start); press_start(p0); lower_c_end(LF_press_start); } \
		uint32_t lw_ = lower_run(LF_press_start, &lr_); \
		if (lm_ == 1) lower_finish(LF_press_start, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_flip_for_player(p0) do { \
	int lm_ = lower_enter(LF_flip_for_player); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_flip_for_player); flip_for_player(p0); lower_c_end(LF_flip_for_player); } \
		uint32_t lw_ = lower_run(LF_flip_for_player, &lr_); \
		if (lm_ == 1) lower_finish(LF_flip_for_player, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_wait_level_state(p0, p1) do { \
	int lm_ = lower_enter(LF_wait_level_state); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p1); \
		if (lm_ == 1) { lower_c_begin(LF_wait_level_state); wait_level_state(p0, p1); lower_c_end(LF_wait_level_state); } \
		uint32_t lw_ = lower_run(LF_wait_level_state, &lr_); \
		if (lm_ == 1) lower_finish(LF_wait_level_state, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_swap_players(p0) do { \
	int lm_ = lower_enter(LF_swap_players); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_swap_players); swap_players(p0); lower_c_end(LF_swap_players); } \
		uint32_t lw_ = lower_run(LF_swap_players, &lr_); \
		if (lm_ == 1) lower_finish(LF_swap_players, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_new_game(p0) do { \
	int lm_ = lower_enter(LF_new_game); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_new_game); new_game(p0); lower_c_end(LF_new_game); } \
		uint32_t lw_ = lower_run(LF_new_game, &lr_); \
		if (lm_ == 1) lower_finish(LF_new_game, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_opening(p0) do { \
	int lm_ = lower_enter(LF_opening); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_opening); opening(p0); lower_c_end(LF_opening); } \
		uint32_t lw_ = lower_run(LF_opening, &lr_); \
		if (lm_ == 1) lower_finish(LF_opening, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_playing(p0) do { \
	int lm_ = lower_enter(LF_playing); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_playing); playing(p0); lower_c_end(LF_playing); } \
		uint32_t lw_ = lower_run(LF_playing, &lr_); \
		if (lm_ == 1) lower_finish(LF_playing, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_life_lost(p0) do { \
	int lm_ = lower_enter(LF_life_lost); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_life_lost); life_lost(p0); lower_c_end(LF_life_lost); } \
		uint32_t lw_ = lower_run(LF_life_lost, &lr_); \
		if (lm_ == 1) lower_finish(LF_life_lost, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_next_turn(p0) do { \
	int lm_ = lower_enter(LF_next_turn); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_next_turn); next_turn(p0); lower_c_end(LF_next_turn); } \
		uint32_t lw_ = lower_run(LF_next_turn, &lr_); \
		if (lm_ == 1) lower_finish(LF_next_turn, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_game_over(p0) do { \
	int lm_ = lower_enter(LF_game_over); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_game_over); game_over(p0); lower_c_end(LF_game_over); } \
		uint32_t lw_ = lower_run(LF_game_over, &lr_); \
		if (lm_ == 1) lower_finish(LF_game_over, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_get_ready(p0) do { \
	int lm_ = lower_enter(LF_get_ready); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_get_ready); get_ready(p0); lower_c_end(LF_get_ready); } \
		uint32_t lw_ = lower_run(LF_get_ready, &lr_); \
		if (lm_ == 1) lower_finish(LF_get_ready, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_board_clear(p0) do { \
	int lm_ = lower_enter(LF_board_clear); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_board_clear); board_clear(p0); lower_c_end(LF_board_clear); } \
		uint32_t lw_ = lower_run(LF_board_clear, &lr_); \
		if (lm_ == 1) lower_finish(LF_board_clear, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_flash_maze(p0, p1) do { \
	int lm_ = lower_enter(LF_flash_maze); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		lr_.a = (uint16_t)(uint8_t)(p1); \
		if (lm_ == 1) { lower_c_begin(LF_flash_maze); flash_maze(p0, p1); lower_c_end(LF_flash_maze); } \
		uint32_t lw_ = lower_run(LF_flash_maze, &lr_); \
		if (lm_ == 1) lower_finish(LF_flash_maze, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_clear_board(p0) do { \
	int lm_ = lower_enter(LF_clear_board); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_clear_board); clear_board(p0); lower_c_end(LF_clear_board); } \
		uint32_t lw_ = lower_run(LF_clear_board, &lr_); \
		if (lm_ == 1) lower_finish(LF_clear_board, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_intermission(p0) do { \
	int lm_ = lower_enter(LF_intermission); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_intermission); intermission(p0); lower_c_end(LF_intermission); } \
		uint32_t lw_ = lower_run(LF_intermission, &lr_); \
		if (lm_ == 1) lower_finish(LF_intermission, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_next_board(p0) do { \
	int lm_ = lower_enter(LF_next_board); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_next_board); next_board(p0); lower_c_end(LF_next_board); } \
		uint32_t lw_ = lower_run(LF_next_board, &lr_); \
		if (lm_ == 1) lower_finish(LF_next_board, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_level_step(p0) do { \
	int lm_ = lower_enter(LF_level_step); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_level_step); level_step(p0); lower_c_end(LF_level_step); } \
		uint32_t lw_ = lower_run(LF_level_step, &lr_); \
		if (lm_ == 1) lower_finish(LF_level_step, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_power_on(p0) do { \
	int lm_ = lower_enter(LF_power_on); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_power_on); power_on(p0); lower_c_end(LF_power_on); } \
		uint32_t lw_ = lower_run(LF_power_on, &lr_); \
		if (lm_ == 1) lower_finish(LF_power_on, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_attract(p0) do { \
	int lm_ = lower_enter(LF_attract); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_attract); attract(p0); lower_c_end(LF_attract); } \
		uint32_t lw_ = lower_run(LF_attract, &lr_); \
		if (lm_ == 1) lower_finish(LF_attract, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_game_mode_step(p0) do { \
	int lm_ = lower_enter(LF_game_mode_step); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_game_mode_step); game_mode_step(p0); lower_c_end(LF_game_mode_step); } \
		uint32_t lw_ = lower_run(LF_game_mode_step, &lr_); \
		if (lm_ == 1) lower_finish(LF_game_mode_step, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_game_start(p0) do { \
	int lm_ = lower_enter(LF_game_start); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_game_start); game_start(p0); lower_c_end(LF_game_start); } \
		uint32_t lw_ = lower_run(LF_game_start, &lr_); \
		if (lm_ == 1) lower_finish(LF_game_start, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_sched_tasks(p0) do { \
	int lm_ = lower_enter(LF_sched_tasks); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		uint32_t lc_ = 0; \
		if (lm_ == 1) { lower_c_begin(LF_sched_tasks); lc_ = (uint32_t)(sched_tasks(p0)) & 0xFFFFu; lower_c_end(LF_sched_tasks); } \
		uint32_t lw_ = lower_run(LF_sched_tasks, &lr_); \
		if (lm_ == 1) lower_finish(LF_sched_tasks, lc_, lw_, &lr_); \
		uint32_t lr2_ = lm_ == 1 ? lc_ : lw_; \
		return (uint16_t)lr2_; \
	} \
} while (0)

#define LH_vblank(p0) do { \
	int lm_ = lower_enter(LF_vblank); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_vblank); vblank(p0); lower_c_end(LF_vblank); } \
		uint32_t lw_ = lower_run(LF_vblank, &lr_); \
		if (lm_ == 1) lower_finish(LF_vblank, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#define LH_c_only_frame(p0) do { \
	int lm_ = lower_enter(LF_c_only_frame); \
	if (lm_) { \
		L65Regs lr_ = {0, 0, 0}; \
		if (lm_ == 1) { lower_c_begin(LF_c_only_frame); c_only_frame(p0); lower_c_end(LF_c_only_frame); } \
		uint32_t lw_ = lower_run(LF_c_only_frame, &lr_); \
		if (lm_ == 1) lower_finish(LF_c_only_frame, 0, lw_, &lr_); \
		return; \
	} \
} while (0)

#endif

#if defined(LOWER_FN_TABLE) && !defined(LOWER_FN_TABLE_DONE)
#define LOWER_FN_TABLE_DONE
static const LowerFn k_lower_fns[LF_COUNT > 0 ? LF_COUNT : 1] = {
	{"st_add", "selftest", 'b'},
	{"st_bcd", "selftest", 'b'},
	{"st_store16", "selftest", 'v'},
	{"st_load16", "selftest", 'w'},
	{"lift_random_byte", "board", 'b'},
	{"rom_random", "rng", 'b'},
	{"dir_step", "actor", 'c'},
	{"coord_add", "actor", 'c'},
	{"coord_eq", "actor", 'b'},
	{"coord_word", "actor", 'w'},
	{"word_coord", "actor", 'c'},
	{"pos_to_tile", "actor", 'c'},
	{"tile_cell", "actor", 'w'},
	{"tile_at", "actor", 'b'},
	{"color_at", "actor", 'b'},
	{"is_wall", "actor", 'b'},
	{"tunnel_wrap", "actor", 'b'},
	{"speed_tick", "actor", 'b'},
	{"queue_task", "task", 'v'},
	{"task_next_level_state", "task", 'v'},
	{"load_difficulty", "difficulty", 'v'},
	{"update_elroy", "difficulty", 'v'},
	{"siren_update", "siren", 'v'},
	{"draw_block", "draw", 'v'},
	{"draw_icon", "draw", 'v'},
	{"draw_fruit_row", "draw", 'v'},
	{"draw_message", "draw", 'v'},
	{"draw_tile_list", "draw", 'v'},
	{"text_task", "draw", 'v'},
	{"draw_1up", "hud", 'v'},
	{"draw_2up", "hud", 'v'},
	{"clear_label", "hud", 'v'},
	{"update_lamps", "hud", 'v'},
	{"hud_blink", "hud", 'v'},
	{"draw_score", "score", 'v'},
	{"draw_player_score", "score", 'v'},
	{"draw_lives", "score", 'v'},
	{"award_life", "score", 'v'},
	{"add_score", "score", 'v'},
	{"draw_lives_row", "score", 'v'},
	{"draw_bonus_digits", "score", 'v'},
	{"read_dip_switches", "score", 'v'},
	{"draw_scores", "score", 'v'},
	{"show_credits", "score", 'v'},
	{"draw_midway_logo", "attract", 'v'},
	{"marquee_bulbs", "attract", 'v'},
	{"show_card", "attract", 'v'},
	{"open_marquee", "attract", 'v'},
	{"attract_step", "attract", 'v'},
	{"maze_word", "maze", 'w'},
	{"power_pill_cell", "maze", 'w'},
	{"flash_power_pills", "maze", 'v'},
	{"pill_bitmap", "maze", 'v'},
	{"reset_pills", "maze", 'v'},
	{"draw_pills", "maze", 'v'},
	{"erase_pills", "maze", 'v'},
	{"clear_colors", "maze", 'v'},
	{"clear_screen", "maze", 'v'},
	{"draw_maze", "maze", 'v'},
	{"wall_color", "maze", 'b'},
	{"maze_colors", "maze", 'v'},
	{"demo_mode", "maze", 'v'},
	{"clear_actors", "maze", 'v'},
	{"house_timer", "maze", 'v'},
	{"place_actors", "maze", 'v'},
	{"add_coin", "coin", 'v'},
	{"coin_meter", "coin", 'v'},
	{"coin_inputs", "coin", 'v'},
	{"clock_tick", "clock", 'v'},
	{"advance_level_state", "clock", 'v'},
	{"advance_play_state", "clock", 'v'},
	{"advance_attract_state", "clock", 'v'},
	{"advance_eaten_ghost_anim", "clock", 'v'},
	{"clear_ready", "clock", 'v'},
	{"advance_cutscene1", "clock", 'v'},
	{"advance_cutscene2", "clock", 'v'},
	{"advance_cutscene3", "clock", 'v'},
	{"timers_run", "clock", 'v'},
	{"queue_timed", "clock", 'b'},
	{"clear_fruit", "fruit", 'v'},
	{"clear_fruit_pos", "fruit", 'v'},
	{"choose_path", "fruit", 'w'},
	{"release_fruit", "fruit", 'v'},
	{"next_bounce", "fruit", 'v'},
	{"end_of_path", "fruit", 'v'},
	{"move_fruit", "fruit", 'v'},
	{"best_dir", "target", 'b'},
	{"random_dir", "target", 'b'},
	{"random_corner", "target", 'c'},
	{"aim_red", "target", 'v'},
	{"aim_pink", "target", 'v'},
	{"aim_blue", "target", 'v'},
	{"aim_orange", "target", 'v'},
	{"demo_steer", "target", 'v'},
	{"color_eyes", "fright", 'v'},
	{"start_fright", "fright", 'v'},
	{"fright_countdown", "fright", 'v'},
	{"flash_ghosts", "fright", 'v'},
	{"ghost_hit", "fright", 'v'},
	{"tile_collision", "fright", 'v'},
	{"pixel_collision", "fright", 'v'},
	{"show_eaten_ghost", "fright", 'v'},
	{"move_ghosts", "ghost", 'v'},
	{"return_all_eyes", "ghost", 'v'},
	{"mark_eaten_ghost", "ghost", 'v'},
	{"move_in_house", "ghost", 'v'},
	{"release_by_pills", "ghost", 'v'},
	{"count_house_pill", "ghost", 'v'},
	{"release_idle_ghost", "ghost", 'v'},
	{"ghost_anim_tick", "ghost", 'v'},
	{"reversal_timer", "ghost", 'v'},
	{"wall_ahead", "pac", 'b'},
	{"eat_pill", "pac", 'v'},
	{"arrive", "pac", 'v'},
	{"pac_step", "pac", 'v'},
	{"adopt", "pac", 'v'},
	{"try_turn", "pac", 'v'},
	{"want", "pac", 'v'},
	{"face", "pac", 'v'},
	{"demo_move", "pac", 'v'},
	{"steer", "pac", 'v'},
	{"move_pac", "pac", 'v'},
	{"clear_actor_positions", "pac", 'v'},
	{"pac_death", "pac", 'v'},
	{"sound_effects", "sound", 'v'},
	{"sound_songs", "sound", 'v'},
	{"cutscene2_sprites", "cutscene", 'v'},
	{"cutscene1_positions", "cutscene", 'v'},
	{"cutscene3_sprites", "cutscene", 'v'},
	{"cutscene1_sprites", "cutscene", 'v'},
	{"load_scripts", "cutscene", 'v'},
	{"run_cutscene", "cutscene", 'v'},
	{"run_act", "cutscene", 'v'},
	{"sprites_upright", "sprite", 'v'},
	{"sprites_cocktail", "sprite", 'v'},
	{"play_pass", "play", 'v'},
	{"play_frame", "play", 'v'},
	{"draw_prompt", "start", 'v'},
	{"begin_game", "start", 'v'},
	{"wait_start", "start", 'v'},
	{"set_up_game", "start", 'v'},
	{"start_play", "start", 'v'},
	{"press_start", "start", 'v'},
	{"flip_for_player", "mode", 'v'},
	{"wait_level_state", "mode", 'v'},
	{"swap_players", "mode", 'v'},
	{"new_game", "mode", 'v'},
	{"opening", "mode", 'v'},
	{"playing", "mode", 'v'},
	{"life_lost", "mode", 'v'},
	{"next_turn", "mode", 'v'},
	{"game_over", "mode", 'v'},
	{"get_ready", "mode", 'v'},
	{"board_clear", "mode", 'v'},
	{"flash_maze", "mode", 'v'},
	{"clear_board", "mode", 'v'},
	{"intermission", "mode", 'v'},
	{"next_board", "mode", 'v'},
	{"level_step", "mode", 'v'},
	{"power_on", "mode", 'v'},
	{"attract", "mode", 'v'},
	{"game_mode_step", "mode", 'v'},
	{"game_start", "sched", 'v'},
	{"sched_tasks", "sched", 'w'},
	{"vblank", "vblank", 'v'},
	{"c_only_frame", "conly", 'v'},
};
#endif
