* Generated by py/gen_lower_entries.py from lower/entries.txt.
* Entry n is at $4*n: JSR to the routine, RTL to the caller.

	jsr	st_add	; 0 selftest: (A=p0:b, X=p1:b) -> A
	rtl
	jsr	st_bcd	; 1 selftest: (A=p0:b, X=p1:b) -> A
	rtl
	jsr	st_store16	; 2 selftest: (X=p0:w, Y=p1:w)
	rtl
	jsr	st_load16	; 3 selftest: (X=p0:w) -> X
	rtl
	jsr	lift_random_byte	; 4 board: () -> A
	rtl
	jsr	rom_random	; 5 rng: () -> A
	rtl
	jsr	dir_step	; 6 actor: (A=p1:b) -> X
	rtl
	jsr	coord_add	; 7 actor: (X=p0:c, Y=p1:c) -> X
	rtl
	jsr	coord_eq	; 8 actor: (X=p0:c, Y=p1:c) -> A
	rtl
	jsr	coord_word	; 9 actor: (X=p0:c) -> X
	rtl
	jsr	word_coord	; 10 actor: (X=p0:w) -> X
	rtl
	jsr	pos_to_tile	; 11 actor: (X=p0:c) -> X
	rtl
	jsr	tile_cell	; 12 actor: (X=p0:c) -> X
	rtl
	jsr	tile_at	; 13 actor: (X=p1:c) -> A
	rtl
	jsr	color_at	; 14 actor: (X=p1:c) -> A
	rtl
	jsr	is_wall	; 15 actor: (A=p0:b) -> A
	rtl
	jsr	tunnel_wrap	; 16 actor: (A=p1:b) -> A
	rtl
	jsr	speed_tick	; 17 actor: (X=p0:p) -> A
	rtl
	jsr	queue_task	; 18 task: (A=p1:b, X=p2:b)
	rtl
	jsr	task_next_level_state	; 19 task: (A=p1:b)
	rtl
	jsr	load_difficulty	; 20 difficulty: (A=p1:b)
	rtl
	jsr	update_elroy	; 21 difficulty: ()
	rtl
	jsr	siren_update	; 22 siren: ()
	rtl
	jsr	draw_block	; 23 draw: (X=p1:w, A=p2:b)
	rtl
	jsr	draw_icon	; 24 draw: (X=p1:w, A=p2:b)
	rtl
	jsr	draw_fruit_row	; 25 draw: ()
	rtl
	jsr	draw_message	; 26 draw: (A=p1:b)
	rtl
	jsr	draw_tile_list	; 27 draw: (X=p1:w)
	rtl
	jsr	text_task	; 28 draw: (A=p1:b)
	rtl
	jsr	draw_1up	; 29 hud: ()
	rtl
	jsr	draw_2up	; 30 hud: ()
	rtl
	jsr	clear_label	; 31 hud: (X=p1:w)
	rtl
	jsr	update_lamps	; 32 hud: (A=p1:b)
	rtl
	jsr	hud_blink	; 33 hud: ()
	rtl
	jsr	draw_score	; 34 score: (X=p1:w, Y=p2:p, A=p3:b)
	rtl
	jsr	draw_player_score	; 35 score: ()
	rtl
	jsr	draw_lives	; 36 score: (A=p1:b)
	rtl
	jsr	award_life	; 37 score: (X=p2:p)
	rtl
	jsr	add_score	; 38 score: (A=p1:b)
	rtl
	jsr	draw_lives_row	; 39 score: ()
	rtl
	jsr	draw_bonus_digits	; 40 score: ()
	rtl
	jsr	read_dip_switches	; 41 score: ()
	rtl
	jsr	draw_scores	; 42 score: ()
	rtl
	jsr	show_credits	; 43 score: ()
	rtl
	jsr	draw_midway_logo	; 44 attract: ()
	rtl
	jsr	marquee_bulbs	; 45 attract: ()
	rtl
	jsr	show_card	; 46 attract: (A=p1:b)
	rtl
	jsr	open_marquee	; 47 attract: ()
	rtl
	jsr	attract_step	; 48 attract: ()
	rtl
	jsr	maze_word	; 49 maze: (X=p1:w) -> X
	rtl
	jsr	power_pill_cell	; 50 maze: (A=p1:b) -> X
	rtl
	jsr	flash_power_pills	; 51 maze: ()
	rtl
	jsr	pill_bitmap_task	; 52 maze: ()
	rtl
	jsr	reset_pills	; 53 maze: ()
	rtl
	jsr	draw_pills	; 54 maze: ()
	rtl
	jsr	erase_pills	; 55 maze: ()
	rtl
	jsr	clear_colors	; 56 maze: ()
	rtl
	jsr	clear_screen	; 57 maze: (A=p1:b)
	rtl
	jsr	draw_maze	; 58 maze: ()
	rtl
	jsr	wall_color	; 59 maze: (A=p1:b) -> A
	rtl
	jsr	maze_colors	; 60 maze: (A=p1:b)
	rtl
	jsr	demo_mode	; 61 maze: ()
	rtl
	jsr	clear_actors	; 62 maze: ()
	rtl
	jsr	house_timer	; 63 maze: (A=p1:b)
	rtl
	jsr	place_actors	; 64 maze: (A=p1:b)
	rtl
	jsr	add_coin	; 65 coin: ()
	rtl
	jsr	coin_meter	; 66 coin: ()
	rtl
	jsr	coin_inputs	; 67 coin: ()
	rtl
	jsr	clock_tick	; 68 clock: ()
	rtl
	jsr	advance_level_state	; 69 clock: ()
	rtl
	jsr	advance_play_state	; 70 clock: ()
	rtl
	jsr	advance_attract_state	; 71 clock: ()
	rtl
	jsr	advance_eaten_ghost_anim	; 72 clock: ()
	rtl
	jsr	clear_ready	; 73 clock: ()
	rtl
	jsr	advance_cutscene1	; 74 clock: ()
	rtl
	jsr	advance_cutscene2	; 75 clock: ()
	rtl
	jsr	advance_cutscene3	; 76 clock: ()
	rtl
	jsr	timers_run	; 77 clock: ()
	rtl
	jsr	queue_timed	; 78 clock: (A=p1:b, X=p2:b, Y=p3:b) -> A
	rtl
	jsr	clear_fruit	; 79 fruit: ()
	rtl
	jsr	clear_fruit_pos	; 80 fruit: ()
	rtl
	jsr	choose_path	; 81 fruit: (X=p1:w) -> X
	rtl
	jsr	release_fruit	; 82 fruit: ()
	rtl
	jsr	next_bounce	; 83 fruit: (A=p1:b)
	rtl
	jsr	end_of_path	; 84 fruit: ()
	rtl
	jsr	move_fruit	; 85 fruit: ()
	rtl
	jsr	best_dir	; 86 target: (X=p1:c, Y=p2:c, A=p3:b) -> A
	rtl
	jsr	random_dir	; 87 target: (X=p1:c, A=p2:b) -> A
	rtl
	jsr	random_corner	; 88 target: () -> X
	rtl
	jsr	aim_red	; 89 target: ()
	rtl
	jsr	aim_pink	; 90 target: ()
	rtl
	jsr	aim_blue	; 91 target: ()
	rtl
	jsr	aim_orange	; 92 target: ()
	rtl
	jsr	demo_steer	; 93 target: ()
	rtl
	jsr	color_eyes	; 94 fright: ()
	rtl
	jsr	start_fright	; 95 fright: ()
	rtl
	jsr	fright_countdown	; 96 fright: ()
	rtl
	jsr	flash_ghosts	; 97 fright: ()
	rtl
	jsr	ghost_hit	; 98 fright: (A=p1:b)
	rtl
	jsr	tile_collision	; 99 fright: ()
	rtl
	jsr	pixel_collision	; 100 fright: ()
	rtl
	jsr	show_eaten_ghost	; 101 fright: ()
	rtl
	jsr	move_ghosts	; 102 ghost: ()
	rtl
	jsr	return_all_eyes	; 103 ghost: ()
	rtl
	jsr	mark_eaten_ghost	; 104 ghost: ()
	rtl
	jsr	move_in_house	; 105 ghost: ()
	rtl
	jsr	release_by_pills	; 106 ghost: ()
	rtl
	jsr	count_house_pill	; 107 ghost: ()
	rtl
	jsr	release_idle_ghost	; 108 ghost: ()
	rtl
	jsr	ghost_anim_tick	; 109 ghost: ()
	rtl
	jsr	reversal_timer	; 110 ghost: ()
	rtl
	jsr	wall_ahead	; 111 pac: (X=p1:c) -> A
	rtl
	jsr	eat_pill	; 112 pac: ()
	rtl
	jsr	arrive	; 113 pac: (X=p1:c)
	rtl
	jsr	pac_step	; 114 pac: ()
	rtl
	jsr	adopt	; 115 pac: (A=p1:b)
	rtl
	jsr	try_turn	; 116 pac: (A=p1:b)
	rtl
	jsr	want	; 117 pac: (A=p1:b)
	rtl
	jsr	face	; 118 pac: (A=p1:b)
	rtl
	jsr	demo_move	; 119 pac: ()
	rtl
	jsr	steer	; 120 pac: (A=p1:b, X=p2:b)
	rtl
	jsr	move_pac	; 121 pac: ()
	rtl
	jsr	clear_actor_positions	; 122 pac: ()
	rtl
	jsr	pac_death	; 123 pac: ()
	rtl
	jsr	sound_effects	; 124 sound: ()
	rtl
	jsr	sound_songs	; 125 sound: ()
	rtl
	jsr	cutscene2_sprites	; 126 cutscene: ()
	rtl
	jsr	cutscene1_positions	; 127 cutscene: ()
	rtl
	jsr	cutscene3_sprites	; 128 cutscene: ()
	rtl
	jsr	cutscene1_sprites	; 129 cutscene: ()
	rtl
	jsr	load_scripts	; 130 cutscene: (A=p1:b)
	rtl
	jsr	run_cutscene	; 131 cutscene: (A=p1:b)
	rtl
	jsr	run_act	; 132 cutscene: (A=p1:b)
	rtl
	jsr	sprites_upright	; 133 sprite: ()
	rtl
	jsr	sprites_cocktail	; 134 sprite: ()
	rtl
	jsr	play_pass	; 135 play: ()
	rtl
	jsr	play_frame	; 136 play: ()
	rtl
	jsr	draw_prompt	; 137 start: ()
	rtl
	jsr	begin_game	; 138 start: ()
	rtl
	jsr	wait_start	; 139 start: ()
	rtl
	jsr	set_up_game	; 140 start: ()
	rtl
	jsr	start_play	; 141 start: ()
	rtl
	jsr	press_start	; 142 start: ()
	rtl
	jsr	flip_for_player	; 143 mode: ()
	rtl
	jsr	wait_level_state	; 144 mode: (A=p1:b)
	rtl
	jsr	swap_players	; 145 mode: ()
	rtl
	jsr	new_game	; 146 mode: ()
	rtl
	jsr	opening	; 147 mode: ()
	rtl
	jsr	playing	; 148 mode: ()
	rtl
	jsr	life_lost	; 149 mode: ()
	rtl
	jsr	next_turn	; 150 mode: ()
	rtl
	jsr	game_over	; 151 mode: ()
	rtl
	jsr	get_ready	; 152 mode: ()
	rtl
	jsr	board_clear	; 153 mode: ()
	rtl
	jsr	flash_maze	; 154 mode: (A=p1:b)
	rtl
	jsr	clear_board	; 155 mode: ()
	rtl
	jsr	intermission	; 156 mode: ()
	rtl
	jsr	next_board	; 157 mode: ()
	rtl
	jsr	level_step	; 158 mode: ()
	rtl
	jsr	power_on	; 159 mode: ()
	rtl
	jsr	attract	; 160 mode: ()
	rtl
	jsr	game_mode_step	; 161 mode: ()
	rtl
	jsr	game_start	; 162 sched: ()
	rtl
	jsr	sched_tasks	; 163 sched: () -> X
	rtl
	jsr	vblank	; 164 vblank: ()
	rtl
	jsr	c_only_frame	; 165 conly: ()
	rtl
