/* Generated by py/gen_idiom_ram.py from py/ram_symbols.py.
 * Work RAM $4C00-$4FEF overlaid on Board.mem. Do not insert padding.
 */
#ifndef IDIOM_RAM_H
#define IDIOM_RAM_H

#include <stddef.h>
#include <stdint.h>

#define WORK_RAM_BASE 0x4C00u
#define WORK_RAM_END  0x4FEFu
#define WORK_RAM_SIZE 0x3F0u

/* A position or step, Y first as the game stores it. */
typedef struct Coord {
	uint8_t y;
	uint8_t x;
} Coord;

typedef struct SpriteCode {
	uint8_t code;  /* sprite number and the two flip bits */
	uint8_t color;
} SpriteCode;

typedef struct SpritePos {
	uint8_t x;
	uint8_t y;
} SpritePos;

/* A 32-bit speed pattern that rotates left once per call. The actor
 * steps when a 1 rotates out. Bytes 0-1 are the high word, 2-3 the low. */
typedef struct SpeedPattern {
	uint8_t bits[4];
} SpeedPattern;

/* One sound channel, 16 bytes. Effects and songs share the layout except
 * for bytes 3-10. Effects copy those from their 8-byte table entry. Songs
 * set them with commands F1-F4 and keep the song pointer in them. */
typedef struct SoundChannel {
	uint8_t num;      /* +0 bitmask of sounds requested */
	uint8_t unused1;  /* +1 */
	uint8_t cur_bit;  /* +2 the bit now playing */
	union {
		struct {
			uint8_t shape;       /* +3 bits 6-4 octave shift, low bits wave select */
			uint8_t base;        /* +4 starting frequency */
			uint8_t step;        /* +5 added to the frequency each frame */
			uint8_t length;      /* +6 bits 6-0 frames per sweep, bit 7 reverse */
			uint8_t repeat_step; /* +7 added to the base on each repeat */
			uint8_t repeats;     /* +8 sweeps left, 0 forever */
			uint8_t volume0;     /* +9 volume; bits 7-4 also give the type */
			uint8_t volume_step; /* +10 added to the volume on each repeat */
		} e;
		struct {
			uint8_t select;   /* +3 wave select, command F1 */
			uint8_t octave;   /* +4 command F2 */
			uint8_t unused5;  /* +5 */
			uint8_t ptr_lo;   /* +6 song pointer */
			uint8_t ptr_hi;   /* +7 */
			uint8_t unused8;  /* +8 */
			uint8_t volume0;  /* +9 volume, command F3 */
			uint8_t unused10; /* +10 */
		} w;
	};
	uint8_t type;     /* +11 volume envelope 0-15 (songs: command F4) */
	uint8_t duration; /* +12 frames left */
	uint8_t dir;      /* +13 effects: bit 0 sweeping back. songs: the note */
	uint8_t freq;     /* +14 base frequency */
	uint8_t volume;   /* +15 */
} SoundChannel;

_Static_assert(sizeof(SoundChannel) == 16, "SoundChannel");
_Static_assert(offsetof(SoundChannel, e.volume_step) == 10, "SoundChannel.e");
_Static_assert(offsetof(SoundChannel, w.ptr_lo) == 6, "SoundChannel.w");
_Static_assert(offsetof(SoundChannel, volume) == 15, "SoundChannel.volume");

typedef struct WorkRam {
	SpriteCode sprite[8]; /* $4C00 sprite code and color by slot (SPR_*). Code bits 7-6 are the flips */
	SpritePos sprite_pos[8]; /* $4C10 sprite positions by slot, in hardware order */
	SpriteCode sprite_out[8]; /* $4C20 vblank's copy of sprite[], flips rotated into bits 1-0, for $4FF0 */
	SpritePos sprite_pos_out[8]; /* $4C30 vblank's copy of sprite_pos[], for $5060 */
	uint8_t fruit_path_index; /* $4C40 COUNT: current place in fruit path */
	uint8_t fruit_bounce_index; /* $4C41 BCNT: current place within bounce */
	uint8_t fruit_path_ptr; /* $4C42 PATH: pointer to current fruit path (lo) */
	uint8_t fruit_path_ptr_hi; /* $4C43 PATH: pointer to current fruit path (hi) */
	uint8_t gap_4c44[60]; /* $4C44 undocumented */
	uint8_t task_list_tail_ptr; /* $4C80 pointer to end of non-IRQ task list (lo) */
	uint8_t task_list_tail_ptr_hi; /* $4C81 pointer to end of non-IRQ task list (hi) */
	uint8_t task_list_head_ptr; /* $4C82 pointer to beginning of task list (lo) */
	uint8_t task_list_head_ptr_hi; /* $4C83 pointer to beginning of task list (hi) */
	uint8_t SOUND_COUNTER; /* $4C84 VBLANK sound counter (also SOUND_COUNTER) */
	uint8_t timer_unused_4c85; /* $4C85 8-bit counter unused */
	uint8_t clock_hundredths; /* $4C86 clock counter: hundredths */
	uint8_t clock_seconds; /* $4C87 clock counter: seconds */
	uint8_t clock_minutes; /* $4C88 clock counter: minutes */
	uint8_t clock_hours; /* $4C89 clock counter: hours */
	uint8_t clock_limit_changes; /* $4C8A counter-limit changes this frame */
	uint8_t rng_unused_4c8b; /* $4C8B random (unused) */
	uint8_t rng_unused_4c8c; /* $4C8C random (unused) */
	uint8_t gap_4c8d[3]; /* $4C8D undocumented */
	uint8_t timed_task_list[48]; /* $4C90 IRQ scheduled tasks (4C90-4CBF), 16 x 3 bytes */
	uint8_t main_task_list[64]; /* $4CC0 non-IRQ tasks (4CC0-4CCF), 16 x 2 bytes */
	Coord pos[5]; /* $4D00 actor pixel positions (ACT_*) */
	Coord mid_tile[5]; /* $4D0A actor tile, taken at the middle of the sprite */
	Coord step[5]; /* $4D14 actor direction as a tile step */
	Coord next_step[5]; /* $4D1E ghosts' chosen step; Ms. Pac's wanted step */
	uint8_t prev_dir[4]; /* $4D28 ghosts' previous direction (ACT_*) */
	uint8_t dir[5]; /* $4D2C actor direction (ACT_*), DIR_* */
	Coord tile[5]; /* $4D31 actor tile position */
	uint8_t path_best_dir; /* $4D3B pathfinding: best orientation found */
	uint8_t pac_wanted_dir; /* $4D3C wanted pacman orientation */
	uint8_t path_opposite_dir; /* $4D3D pathfinding: opposite orientation */
	Coord path_from; /* $4D3E pathfinding: the ghost's tile */
	Coord path_target; /* $4D40 pathfinding: the target tile */
	Coord path_try; /* $4D42 pathfinding: the neighbor tile being tried */
	uint8_t path_min_dist_lo; /* $4D44 pathfinding: minimum distance^2 (lo) */
	uint8_t path_min_dist_hi; /* $4D45 pathfinding: minimum distance^2 (hi) */
	SpeedPattern pac_speed[2]; /* $4D46 Ms. Pac speed: normal, then energized */
	SpeedPattern elroy2_speed; /* $4D4E red's cruise elroy 2 speed */
	SpeedPattern elroy1_speed; /* $4D52 red's cruise elroy 1 speed */
	SpeedPattern ghost_speed[12]; /* $4D56 ghost speeds, 3 per ghost (ACT_*): SPEED_NORMAL/BLUE/TUNNEL */
	uint8_t ghost_orient_table[14]; /* $4D86 difficulty ghost orientation change table (4D86-4D93) */
	uint8_t ghost_home_move_counter; /* $4D94 counter: ghost movement inside home */
	uint8_t ghost_leave_home_units_lo; /* $4D95 units before ghost leaves home (lo) */
	uint8_t ghost_leave_home_units_hi; /* $4D96 units before ghost leaves home (hi) */
	uint8_t ghost_leave_home_idle_lo; /* $4D97 inactivity counter for leave-home (lo) */
	uint8_t ghost_leave_home_idle_hi; /* $4D98 inactivity counter for leave-home (hi) */
	uint8_t tunnel_slow[4]; /* $4D99 ghost is in a tunnel slowdown area */
	uint8_t pac_move_delay; /* $4D9D delay to update pacman movement */
	uint8_t pills_since_pac_move; /* $4D9E pills eaten before last pacman move */
	uint8_t pills_after_death; /* $4D9F pills eaten after death (ghost release) */
	uint8_t substate[4]; /* $4DA0 ghost substate while alive */
	uint8_t ghosts_killed_pending; /* $4DA4 # ghosts killed but collision not done yet */
	uint8_t pac_death_anim; /* $4DA5 pacman dead animation state */
	uint8_t power_pill_active; /* $4DA6 power pill effect active */
	uint8_t frightened[4]; /* $4DA7 ghost is blue */
	uint8_t kill_ghost_state; /* $4DAB killing ghost state (0=none, 1-4=which) */
	uint8_t ghost_state[4]; /* $4DAC ghost state: 0 alive, else eyes/returning home */
	uint8_t diff_unused_4db0; /* $4DB0 difficulty related, appears unused */
	uint8_t reverse[5]; /* $4DB1 actor must reverse (ACT_*) */
	uint8_t cruise_elroy_1; /* $4DB6 1st difficulty / cruise elroy 1 flag */
	uint8_t cruise_elroy_2; /* $4DB7 2nd difficulty / cruise elroy 2 flag */
	uint8_t pink_exit_limit; /* $4DB8 pink leave-home pill counter limit */
	uint8_t blue_exit_limit; /* $4DB9 blue leave-home pill counter limit */
	uint8_t orange_exit_limit; /* $4DBA orange leave-home pill counter limit */
	uint8_t elroy1_pill_threshold; /* $4DBB pills remaining for cruise elroy 1 */
	uint8_t elroy2_pill_threshold; /* $4DBC pills remaining for cruise elroy 2 */
	uint8_t frightened_time_lo; /* $4DBD frightened duration (lo) */
	uint8_t frightened_time_hi; /* $4DBE frightened duration (hi) */
	uint8_t pac_entering_tunnel; /* $4DBF 1 if pacman about to enter tunnel */
	uint8_t ghost_anim_phase; /* $4DC0 changes every 8 frames; ghost anim */
	uint8_t ghost_orient_index; /* $4DC1 orientation-change table index */
	uint8_t ghost_orient_counter_lo; /* $4DC2 ghost orientation change counter (lo) */
	uint8_t ghost_orient_counter_hi; /* $4DC3 ghost orientation change counter (hi) */
	uint8_t frame_div8_counter; /* $4DC4 0..8; do work every 8 frames */
	uint8_t death_counter_lo; /* $4DC5 counter after pacman killed (lo) */
	uint8_t death_counter_hi; /* $4DC6 counter after pacman killed (hi) */
	uint8_t path_try_dir; /* $4DC7 current orientation being tried */
	uint8_t frightened_flash_counter; /* $4DC8 ghost color flash under big pill */
	uint8_t rng_rom_ptr_lo; /* $4DC9 RNG ROM pointer (lo), routine 2A23 */
	uint8_t rng_rom_ptr_hi; /* $4DCA RNG ROM pointer (hi) */
	uint8_t frightened_timer_lo; /* $4DCB blue-ghost timer (lo); ceases at 0 */
	uint8_t frightened_timer_hi; /* $4DCC blue-ghost timer (hi) */
	uint8_t gap_4dcd; /* $4DCD undocumented */
	uint8_t coin_blink_counter; /* $4DCE after insert coin; LED / 1UP blink */
	uint8_t power_pill_flash_counter; /* $4DCF power pill flash counter */
	uint8_t ghosts_killed_count; /* $4DD0 current killed ghosts 0..4 */
	uint8_t killed_ghost_anim; /* $4DD1 killed ghost animation state */
	Coord fruit_pos; /* $4DD2 FRUITP: fruit position */
	uint8_t fruit_points; /* $4DD4 FVALUE: fruit points entry, or 0 */
	uint8_t gap_4dd5; /* $4DD5 undocumented */
	uint8_t start_button_wait; /* $4DD6 LED/start-button wait state */
	uint8_t gap_4dd7[41]; /* $4DD7 undocumented */
	uint8_t game_mode; /* $4E00 main routine number (init/demo/coin/play) */
	uint8_t game_mode_sub0; /* $4E01 main routine 0 subroutine # */
	uint8_t game_mode_sub1; /* $4E02 main routine 1 subroutine # (attract/demo) */
	uint8_t game_mode_sub2; /* $4E03 main routine 2 subroutine # */
	uint8_t level_state; /* $4E04 level state subroutine # (2=pause ghosts) */
	uint8_t gap_4e05; /* $4E05 undocumented */
	uint8_t cutscene1_state; /* $4E06 first cutscene state (pac-man) */
	uint8_t cutscene2_state; /* $4E07 second cutscene state */
	uint8_t cutscene3_state; /* $4E08 third cutscene state */
	uint8_t player_number; /* $4E09 current player: 0=P1, 1=P2 */
	uint8_t difficulty_ptr_lo; /* $4E0A pointer to current difficulty settings (lo) */
	uint8_t difficulty_ptr_hi; /* $4E0B pointer to current difficulty settings (hi) */
	uint8_t fruit1_released; /* $4E0C FIRSTF: first fruit released/appeared */
	uint8_t fruit2_released; /* $4E0D SECONDF: second fruit flag */
	uint8_t dots_eaten; /* $4E0E DOTSEAT: pills eaten this level */
	uint8_t pink_exit_counter; /* $4E0F pill counter toward pink leaving home */
	uint8_t blue_exit_counter; /* $4E10 pill counter toward blue leaving home */
	uint8_t orange_exit_counter; /* $4E11 pill counter toward orange leaving home */
	uint8_t died_this_level; /* $4E12 1 after dying; cleared when ghosts leave via 4D9F */
	uint8_t level_number; /* $4E13 current level */
	uint8_t lives_real; /* $4E14 real number of lives */
	uint8_t lives_displayed; /* $4E15 number of lives displayed */
	uint8_t pill_bitmap[30]; /* $4E16 pill bitmaps (4E16-4E33) */
	uint8_t power_pill_data[4]; /* $4E34 power pill data (4E34-4E37) */
	uint8_t level_data_copy[46]; /* $4E38 copy of level data (4E38-4E65) */
	uint8_t in_service_hist; /* $4E66 last 4 SERVICE1 samples */
	uint8_t in_coin2_hist; /* $4E67 last 4 COIN2 samples */
	uint8_t in_coin1_hist; /* $4E68 last 4 COIN1 samples */
	uint8_t coin_counter; /* $4E69 coin→credits counter */
	uint8_t coin_counter_timeout; /* $4E6A coin counter timeout */
	uint8_t dip_coins_per_credit; /* $4E6B coins per credit (from DSW) */
	uint8_t coins_inserted; /* $4E6C number of coins inserted */
	uint8_t dip_credits_per_coin; /* $4E6D credits per coin */
	uint8_t credits; /* $4E6E credits; 0xFF = free play */
	uint8_t dip_lives; /* $4E6F lives per game (from DSW) */
	uint8_t num_players; /* $4E70 0=1 player, 1=2 players */
	uint8_t dip_bonus_life; /* $4E71 bonus life threshold */
	uint8_t dip_cocktail; /* $4E72 cocktail mode */
	uint8_t dip_difficulty_ptr_lo; /* $4E73 difficulty settings pointer (lo) */
	uint8_t dip_difficulty_ptr_hi; /* $4E74 difficulty settings pointer (hi) */
	uint8_t ghost_names_mode; /* $4E75 ghost names mode 0/1 */
	uint8_t gap_4e76[10]; /* $4E76 undocumented */
	uint8_t score_p1_lo; /* $4E80 P1 score byte CC */
	uint8_t score_p1_mid; /* $4E81 P1 score byte BB */
	uint8_t score_p1_hi; /* $4E82 P1 score byte AA */
	uint8_t bonus_life_p1; /* $4E83 P1 got bonus life? */
	uint8_t score_p2_lo; /* $4E84 P2 score byte CC */
	uint8_t score_p2_mid; /* $4E85 P2 score byte BB */
	uint8_t score_p2_hi; /* $4E86 P2 score byte AA */
	uint8_t bonus_life_p2; /* $4E87 P2 got bonus life? */
	uint8_t high_score_lo; /* $4E88 high score byte CC */
	uint8_t high_score_mid; /* $4E89 high score byte BB */
	uint8_t high_score_hi; /* $4E8A high score byte AA */
	uint8_t gap_4e8b; /* $4E8B undocumented */
	uint8_t CH1_FREQ0; /* $4E8C ch1 freq nibble 0 */
	uint8_t CH1_FREQ1; /* $4E8D ch1 freq nibble 1 */
	uint8_t CH1_FREQ2; /* $4E8E ch1 freq nibble 2 */
	uint8_t CH1_FREQ3; /* $4E8F ch1 freq nibble 3 */
	uint8_t CH1_FREQ4; /* $4E90 ch1 freq nibble 4 */
	uint8_t CH1_VOL; /* $4E91 ch1 volume */
	uint8_t CH2_FREQ1; /* $4E92 ch2 freq nibble 1 */
	uint8_t CH2_FREQ2; /* $4E93 ch2 freq nibble 2 */
	uint8_t CH2_FREQ3; /* $4E94 ch2 freq nibble 3 */
	uint8_t CH2_FREQ4; /* $4E95 ch2 freq nibble 4 */
	uint8_t CH2_VOL; /* $4E96 ch2 volume */
	uint8_t CH3_FREQ1; /* $4E97 ch3 freq nibble 1 */
	uint8_t CH3_FREQ2; /* $4E98 ch3 freq nibble 2 */
	uint8_t CH3_FREQ3; /* $4E99 ch3 freq nibble 3 */
	uint8_t CH3_FREQ4; /* $4E9A ch3 freq nibble 4 */
	uint8_t CH3_VOL; /* $4E9B ch3 volume */
	SoundChannel effect[3]; /* $4E9C effect channels 1-3 (CH1_E_* ...) */
	SoundChannel wave[3]; /* $4ECC song channels 1-3 (CH1_W_* ...) */
	uint8_t gap_4efc[4]; /* $4EFC undocumented */
	uint8_t intermission_flag; /* $4F00 1 during intermission / parts of attract */
	uint8_t marquee_step; /* $4F01 marquee bulb phase (0-15). Inside the stack page, above its depth */
	uint8_t cutscene_script[12]; /* $4F02 cutscene actor script pointers, lo/hi per actor */
	uint8_t gap_4f0e[2]; /* $4F0E undocumented */
	uint8_t cutscene_frame[6]; /* $4F10 cutscene actor animation step */
	uint8_t gap_4f16[2]; /* $4F16 undocumented */
	uint8_t cutscene_count[6]; /* $4F18 cutscene actor command countdown */
	uint8_t gap_4f1e[2]; /* $4F1E undocumented */
	uint8_t cutscene_done[6]; /* $4F20 cutscene actor reached its END */
	uint8_t gap_4f26[10]; /* $4F26 undocumented */
	Coord cutscene_frac[6]; /* $4F30 cutscene actor sub-pixel motion, 1/16 pixel */
	uint8_t gap_4f3c[4]; /* $4F3C undocumented */
	uint8_t cutscene_anim[12]; /* $4F40 cutscene actor animation table pointers, lo/hi per actor */
	uint8_t gap_4f4c[4]; /* $4F4C undocumented */
	SpriteCode cutscene_sprite[6]; /* $4F50 cutscene sprite codes and colors, copied to sprite[1..6] */
	uint8_t cpu_stack[100]; /* $4F5C CPU stack (4F5C-4FBF) */
	uint8_t gap_4fc0[48]; /* $4FC0 undocumented */
} WorkRam;

_Static_assert(sizeof(WorkRam) == WORK_RAM_SIZE, "WorkRam size");
_Static_assert(offsetof(WorkRam, sprite) == 0x0u, "sprite");
_Static_assert(offsetof(WorkRam, sprite_pos) == 0x10u, "sprite_pos");
_Static_assert(offsetof(WorkRam, sprite_out) == 0x20u, "sprite_out");
_Static_assert(offsetof(WorkRam, sprite_pos_out) == 0x30u, "sprite_pos_out");
_Static_assert(offsetof(WorkRam, fruit_path_index) == 0x40u, "fruit_path_index");
_Static_assert(offsetof(WorkRam, fruit_bounce_index) == 0x41u, "fruit_bounce_index");
_Static_assert(offsetof(WorkRam, fruit_path_ptr) == 0x42u, "fruit_path_ptr");
_Static_assert(offsetof(WorkRam, fruit_path_ptr_hi) == 0x43u, "fruit_path_ptr_hi");
_Static_assert(offsetof(WorkRam, gap_4c44) == 0x44u, "gap_4c44");
_Static_assert(offsetof(WorkRam, task_list_tail_ptr) == 0x80u, "task_list_tail_ptr");
_Static_assert(offsetof(WorkRam, task_list_tail_ptr_hi) == 0x81u, "task_list_tail_ptr_hi");
_Static_assert(offsetof(WorkRam, task_list_head_ptr) == 0x82u, "task_list_head_ptr");
_Static_assert(offsetof(WorkRam, task_list_head_ptr_hi) == 0x83u, "task_list_head_ptr_hi");
_Static_assert(offsetof(WorkRam, SOUND_COUNTER) == 0x84u, "SOUND_COUNTER");
_Static_assert(offsetof(WorkRam, timer_unused_4c85) == 0x85u, "timer_unused_4c85");
_Static_assert(offsetof(WorkRam, clock_hundredths) == 0x86u, "clock_hundredths");
_Static_assert(offsetof(WorkRam, clock_seconds) == 0x87u, "clock_seconds");
_Static_assert(offsetof(WorkRam, clock_minutes) == 0x88u, "clock_minutes");
_Static_assert(offsetof(WorkRam, clock_hours) == 0x89u, "clock_hours");
_Static_assert(offsetof(WorkRam, clock_limit_changes) == 0x8Au, "clock_limit_changes");
_Static_assert(offsetof(WorkRam, rng_unused_4c8b) == 0x8Bu, "rng_unused_4c8b");
_Static_assert(offsetof(WorkRam, rng_unused_4c8c) == 0x8Cu, "rng_unused_4c8c");
_Static_assert(offsetof(WorkRam, gap_4c8d) == 0x8Du, "gap_4c8d");
_Static_assert(offsetof(WorkRam, timed_task_list) == 0x90u, "timed_task_list");
_Static_assert(offsetof(WorkRam, main_task_list) == 0xC0u, "main_task_list");
_Static_assert(offsetof(WorkRam, pos) == 0x100u, "pos");
_Static_assert(offsetof(WorkRam, mid_tile) == 0x10Au, "mid_tile");
_Static_assert(offsetof(WorkRam, step) == 0x114u, "step");
_Static_assert(offsetof(WorkRam, next_step) == 0x11Eu, "next_step");
_Static_assert(offsetof(WorkRam, prev_dir) == 0x128u, "prev_dir");
_Static_assert(offsetof(WorkRam, dir) == 0x12Cu, "dir");
_Static_assert(offsetof(WorkRam, tile) == 0x131u, "tile");
_Static_assert(offsetof(WorkRam, path_best_dir) == 0x13Bu, "path_best_dir");
_Static_assert(offsetof(WorkRam, pac_wanted_dir) == 0x13Cu, "pac_wanted_dir");
_Static_assert(offsetof(WorkRam, path_opposite_dir) == 0x13Du, "path_opposite_dir");
_Static_assert(offsetof(WorkRam, path_from) == 0x13Eu, "path_from");
_Static_assert(offsetof(WorkRam, path_target) == 0x140u, "path_target");
_Static_assert(offsetof(WorkRam, path_try) == 0x142u, "path_try");
_Static_assert(offsetof(WorkRam, path_min_dist_lo) == 0x144u, "path_min_dist_lo");
_Static_assert(offsetof(WorkRam, path_min_dist_hi) == 0x145u, "path_min_dist_hi");
_Static_assert(offsetof(WorkRam, pac_speed) == 0x146u, "pac_speed");
_Static_assert(offsetof(WorkRam, elroy2_speed) == 0x14Eu, "elroy2_speed");
_Static_assert(offsetof(WorkRam, elroy1_speed) == 0x152u, "elroy1_speed");
_Static_assert(offsetof(WorkRam, ghost_speed) == 0x156u, "ghost_speed");
_Static_assert(offsetof(WorkRam, ghost_orient_table) == 0x186u, "ghost_orient_table");
_Static_assert(offsetof(WorkRam, ghost_home_move_counter) == 0x194u, "ghost_home_move_counter");
_Static_assert(offsetof(WorkRam, ghost_leave_home_units_lo) == 0x195u, "ghost_leave_home_units_lo");
_Static_assert(offsetof(WorkRam, ghost_leave_home_units_hi) == 0x196u, "ghost_leave_home_units_hi");
_Static_assert(offsetof(WorkRam, ghost_leave_home_idle_lo) == 0x197u, "ghost_leave_home_idle_lo");
_Static_assert(offsetof(WorkRam, ghost_leave_home_idle_hi) == 0x198u, "ghost_leave_home_idle_hi");
_Static_assert(offsetof(WorkRam, tunnel_slow) == 0x199u, "tunnel_slow");
_Static_assert(offsetof(WorkRam, pac_move_delay) == 0x19Du, "pac_move_delay");
_Static_assert(offsetof(WorkRam, pills_since_pac_move) == 0x19Eu, "pills_since_pac_move");
_Static_assert(offsetof(WorkRam, pills_after_death) == 0x19Fu, "pills_after_death");
_Static_assert(offsetof(WorkRam, substate) == 0x1A0u, "substate");
_Static_assert(offsetof(WorkRam, ghosts_killed_pending) == 0x1A4u, "ghosts_killed_pending");
_Static_assert(offsetof(WorkRam, pac_death_anim) == 0x1A5u, "pac_death_anim");
_Static_assert(offsetof(WorkRam, power_pill_active) == 0x1A6u, "power_pill_active");
_Static_assert(offsetof(WorkRam, frightened) == 0x1A7u, "frightened");
_Static_assert(offsetof(WorkRam, kill_ghost_state) == 0x1ABu, "kill_ghost_state");
_Static_assert(offsetof(WorkRam, ghost_state) == 0x1ACu, "ghost_state");
_Static_assert(offsetof(WorkRam, diff_unused_4db0) == 0x1B0u, "diff_unused_4db0");
_Static_assert(offsetof(WorkRam, reverse) == 0x1B1u, "reverse");
_Static_assert(offsetof(WorkRam, cruise_elroy_1) == 0x1B6u, "cruise_elroy_1");
_Static_assert(offsetof(WorkRam, cruise_elroy_2) == 0x1B7u, "cruise_elroy_2");
_Static_assert(offsetof(WorkRam, pink_exit_limit) == 0x1B8u, "pink_exit_limit");
_Static_assert(offsetof(WorkRam, blue_exit_limit) == 0x1B9u, "blue_exit_limit");
_Static_assert(offsetof(WorkRam, orange_exit_limit) == 0x1BAu, "orange_exit_limit");
_Static_assert(offsetof(WorkRam, elroy1_pill_threshold) == 0x1BBu, "elroy1_pill_threshold");
_Static_assert(offsetof(WorkRam, elroy2_pill_threshold) == 0x1BCu, "elroy2_pill_threshold");
_Static_assert(offsetof(WorkRam, frightened_time_lo) == 0x1BDu, "frightened_time_lo");
_Static_assert(offsetof(WorkRam, frightened_time_hi) == 0x1BEu, "frightened_time_hi");
_Static_assert(offsetof(WorkRam, pac_entering_tunnel) == 0x1BFu, "pac_entering_tunnel");
_Static_assert(offsetof(WorkRam, ghost_anim_phase) == 0x1C0u, "ghost_anim_phase");
_Static_assert(offsetof(WorkRam, ghost_orient_index) == 0x1C1u, "ghost_orient_index");
_Static_assert(offsetof(WorkRam, ghost_orient_counter_lo) == 0x1C2u, "ghost_orient_counter_lo");
_Static_assert(offsetof(WorkRam, ghost_orient_counter_hi) == 0x1C3u, "ghost_orient_counter_hi");
_Static_assert(offsetof(WorkRam, frame_div8_counter) == 0x1C4u, "frame_div8_counter");
_Static_assert(offsetof(WorkRam, death_counter_lo) == 0x1C5u, "death_counter_lo");
_Static_assert(offsetof(WorkRam, death_counter_hi) == 0x1C6u, "death_counter_hi");
_Static_assert(offsetof(WorkRam, path_try_dir) == 0x1C7u, "path_try_dir");
_Static_assert(offsetof(WorkRam, frightened_flash_counter) == 0x1C8u, "frightened_flash_counter");
_Static_assert(offsetof(WorkRam, rng_rom_ptr_lo) == 0x1C9u, "rng_rom_ptr_lo");
_Static_assert(offsetof(WorkRam, rng_rom_ptr_hi) == 0x1CAu, "rng_rom_ptr_hi");
_Static_assert(offsetof(WorkRam, frightened_timer_lo) == 0x1CBu, "frightened_timer_lo");
_Static_assert(offsetof(WorkRam, frightened_timer_hi) == 0x1CCu, "frightened_timer_hi");
_Static_assert(offsetof(WorkRam, gap_4dcd) == 0x1CDu, "gap_4dcd");
_Static_assert(offsetof(WorkRam, coin_blink_counter) == 0x1CEu, "coin_blink_counter");
_Static_assert(offsetof(WorkRam, power_pill_flash_counter) == 0x1CFu, "power_pill_flash_counter");
_Static_assert(offsetof(WorkRam, ghosts_killed_count) == 0x1D0u, "ghosts_killed_count");
_Static_assert(offsetof(WorkRam, killed_ghost_anim) == 0x1D1u, "killed_ghost_anim");
_Static_assert(offsetof(WorkRam, fruit_pos) == 0x1D2u, "fruit_pos");
_Static_assert(offsetof(WorkRam, fruit_points) == 0x1D4u, "fruit_points");
_Static_assert(offsetof(WorkRam, gap_4dd5) == 0x1D5u, "gap_4dd5");
_Static_assert(offsetof(WorkRam, start_button_wait) == 0x1D6u, "start_button_wait");
_Static_assert(offsetof(WorkRam, gap_4dd7) == 0x1D7u, "gap_4dd7");
_Static_assert(offsetof(WorkRam, game_mode) == 0x200u, "game_mode");
_Static_assert(offsetof(WorkRam, game_mode_sub0) == 0x201u, "game_mode_sub0");
_Static_assert(offsetof(WorkRam, game_mode_sub1) == 0x202u, "game_mode_sub1");
_Static_assert(offsetof(WorkRam, game_mode_sub2) == 0x203u, "game_mode_sub2");
_Static_assert(offsetof(WorkRam, level_state) == 0x204u, "level_state");
_Static_assert(offsetof(WorkRam, gap_4e05) == 0x205u, "gap_4e05");
_Static_assert(offsetof(WorkRam, cutscene1_state) == 0x206u, "cutscene1_state");
_Static_assert(offsetof(WorkRam, cutscene2_state) == 0x207u, "cutscene2_state");
_Static_assert(offsetof(WorkRam, cutscene3_state) == 0x208u, "cutscene3_state");
_Static_assert(offsetof(WorkRam, player_number) == 0x209u, "player_number");
_Static_assert(offsetof(WorkRam, difficulty_ptr_lo) == 0x20Au, "difficulty_ptr_lo");
_Static_assert(offsetof(WorkRam, difficulty_ptr_hi) == 0x20Bu, "difficulty_ptr_hi");
_Static_assert(offsetof(WorkRam, fruit1_released) == 0x20Cu, "fruit1_released");
_Static_assert(offsetof(WorkRam, fruit2_released) == 0x20Du, "fruit2_released");
_Static_assert(offsetof(WorkRam, dots_eaten) == 0x20Eu, "dots_eaten");
_Static_assert(offsetof(WorkRam, pink_exit_counter) == 0x20Fu, "pink_exit_counter");
_Static_assert(offsetof(WorkRam, blue_exit_counter) == 0x210u, "blue_exit_counter");
_Static_assert(offsetof(WorkRam, orange_exit_counter) == 0x211u, "orange_exit_counter");
_Static_assert(offsetof(WorkRam, died_this_level) == 0x212u, "died_this_level");
_Static_assert(offsetof(WorkRam, level_number) == 0x213u, "level_number");
_Static_assert(offsetof(WorkRam, lives_real) == 0x214u, "lives_real");
_Static_assert(offsetof(WorkRam, lives_displayed) == 0x215u, "lives_displayed");
_Static_assert(offsetof(WorkRam, pill_bitmap) == 0x216u, "pill_bitmap");
_Static_assert(offsetof(WorkRam, power_pill_data) == 0x234u, "power_pill_data");
_Static_assert(offsetof(WorkRam, level_data_copy) == 0x238u, "level_data_copy");
_Static_assert(offsetof(WorkRam, in_service_hist) == 0x266u, "in_service_hist");
_Static_assert(offsetof(WorkRam, in_coin2_hist) == 0x267u, "in_coin2_hist");
_Static_assert(offsetof(WorkRam, in_coin1_hist) == 0x268u, "in_coin1_hist");
_Static_assert(offsetof(WorkRam, coin_counter) == 0x269u, "coin_counter");
_Static_assert(offsetof(WorkRam, coin_counter_timeout) == 0x26Au, "coin_counter_timeout");
_Static_assert(offsetof(WorkRam, dip_coins_per_credit) == 0x26Bu, "dip_coins_per_credit");
_Static_assert(offsetof(WorkRam, coins_inserted) == 0x26Cu, "coins_inserted");
_Static_assert(offsetof(WorkRam, dip_credits_per_coin) == 0x26Du, "dip_credits_per_coin");
_Static_assert(offsetof(WorkRam, credits) == 0x26Eu, "credits");
_Static_assert(offsetof(WorkRam, dip_lives) == 0x26Fu, "dip_lives");
_Static_assert(offsetof(WorkRam, num_players) == 0x270u, "num_players");
_Static_assert(offsetof(WorkRam, dip_bonus_life) == 0x271u, "dip_bonus_life");
_Static_assert(offsetof(WorkRam, dip_cocktail) == 0x272u, "dip_cocktail");
_Static_assert(offsetof(WorkRam, dip_difficulty_ptr_lo) == 0x273u, "dip_difficulty_ptr_lo");
_Static_assert(offsetof(WorkRam, dip_difficulty_ptr_hi) == 0x274u, "dip_difficulty_ptr_hi");
_Static_assert(offsetof(WorkRam, ghost_names_mode) == 0x275u, "ghost_names_mode");
_Static_assert(offsetof(WorkRam, gap_4e76) == 0x276u, "gap_4e76");
_Static_assert(offsetof(WorkRam, score_p1_lo) == 0x280u, "score_p1_lo");
_Static_assert(offsetof(WorkRam, score_p1_mid) == 0x281u, "score_p1_mid");
_Static_assert(offsetof(WorkRam, score_p1_hi) == 0x282u, "score_p1_hi");
_Static_assert(offsetof(WorkRam, bonus_life_p1) == 0x283u, "bonus_life_p1");
_Static_assert(offsetof(WorkRam, score_p2_lo) == 0x284u, "score_p2_lo");
_Static_assert(offsetof(WorkRam, score_p2_mid) == 0x285u, "score_p2_mid");
_Static_assert(offsetof(WorkRam, score_p2_hi) == 0x286u, "score_p2_hi");
_Static_assert(offsetof(WorkRam, bonus_life_p2) == 0x287u, "bonus_life_p2");
_Static_assert(offsetof(WorkRam, high_score_lo) == 0x288u, "high_score_lo");
_Static_assert(offsetof(WorkRam, high_score_mid) == 0x289u, "high_score_mid");
_Static_assert(offsetof(WorkRam, high_score_hi) == 0x28Au, "high_score_hi");
_Static_assert(offsetof(WorkRam, gap_4e8b) == 0x28Bu, "gap_4e8b");
_Static_assert(offsetof(WorkRam, CH1_FREQ0) == 0x28Cu, "CH1_FREQ0");
_Static_assert(offsetof(WorkRam, CH1_FREQ1) == 0x28Du, "CH1_FREQ1");
_Static_assert(offsetof(WorkRam, CH1_FREQ2) == 0x28Eu, "CH1_FREQ2");
_Static_assert(offsetof(WorkRam, CH1_FREQ3) == 0x28Fu, "CH1_FREQ3");
_Static_assert(offsetof(WorkRam, CH1_FREQ4) == 0x290u, "CH1_FREQ4");
_Static_assert(offsetof(WorkRam, CH1_VOL) == 0x291u, "CH1_VOL");
_Static_assert(offsetof(WorkRam, CH2_FREQ1) == 0x292u, "CH2_FREQ1");
_Static_assert(offsetof(WorkRam, CH2_FREQ2) == 0x293u, "CH2_FREQ2");
_Static_assert(offsetof(WorkRam, CH2_FREQ3) == 0x294u, "CH2_FREQ3");
_Static_assert(offsetof(WorkRam, CH2_FREQ4) == 0x295u, "CH2_FREQ4");
_Static_assert(offsetof(WorkRam, CH2_VOL) == 0x296u, "CH2_VOL");
_Static_assert(offsetof(WorkRam, CH3_FREQ1) == 0x297u, "CH3_FREQ1");
_Static_assert(offsetof(WorkRam, CH3_FREQ2) == 0x298u, "CH3_FREQ2");
_Static_assert(offsetof(WorkRam, CH3_FREQ3) == 0x299u, "CH3_FREQ3");
_Static_assert(offsetof(WorkRam, CH3_FREQ4) == 0x29Au, "CH3_FREQ4");
_Static_assert(offsetof(WorkRam, CH3_VOL) == 0x29Bu, "CH3_VOL");
_Static_assert(offsetof(WorkRam, effect) == 0x29Cu, "effect");
_Static_assert(offsetof(WorkRam, wave) == 0x2CCu, "wave");
_Static_assert(offsetof(WorkRam, gap_4efc) == 0x2FCu, "gap_4efc");
_Static_assert(offsetof(WorkRam, intermission_flag) == 0x300u, "intermission_flag");
_Static_assert(offsetof(WorkRam, marquee_step) == 0x301u, "marquee_step");
_Static_assert(offsetof(WorkRam, cutscene_script) == 0x302u, "cutscene_script");
_Static_assert(offsetof(WorkRam, gap_4f0e) == 0x30Eu, "gap_4f0e");
_Static_assert(offsetof(WorkRam, cutscene_frame) == 0x310u, "cutscene_frame");
_Static_assert(offsetof(WorkRam, gap_4f16) == 0x316u, "gap_4f16");
_Static_assert(offsetof(WorkRam, cutscene_count) == 0x318u, "cutscene_count");
_Static_assert(offsetof(WorkRam, gap_4f1e) == 0x31Eu, "gap_4f1e");
_Static_assert(offsetof(WorkRam, cutscene_done) == 0x320u, "cutscene_done");
_Static_assert(offsetof(WorkRam, gap_4f26) == 0x326u, "gap_4f26");
_Static_assert(offsetof(WorkRam, cutscene_frac) == 0x330u, "cutscene_frac");
_Static_assert(offsetof(WorkRam, gap_4f3c) == 0x33Cu, "gap_4f3c");
_Static_assert(offsetof(WorkRam, cutscene_anim) == 0x340u, "cutscene_anim");
_Static_assert(offsetof(WorkRam, gap_4f4c) == 0x34Cu, "gap_4f4c");
_Static_assert(offsetof(WorkRam, cutscene_sprite) == 0x350u, "cutscene_sprite");
_Static_assert(offsetof(WorkRam, cpu_stack) == 0x35Cu, "cpu_stack");
_Static_assert(offsetof(WorkRam, gap_4fc0) == 0x3C0u, "gap_4fc0");

/* Values the program stores. The addresses stay these bytes. */
#define MAIN_TASK_LIST 0x4CC0u
#define STACK_TOP      0x4FC0u

static inline WorkRam *work_ram(uint8_t *mem)
{
	return (WorkRam *)(void *)(mem + WORK_RAM_BASE);
}

/* Absolute arcade address of a work-RAM byte, as the task list stores it. */
static inline uint8_t *work_byte(WorkRam *ram, uint16_t addr)
{
	return (uint8_t *)ram + (unsigned)(addr - WORK_RAM_BASE);
}

const char *work_ram_name(uint16_t addr);

#endif
