* Generated by py/gen_idiom_ram.py from py/ram_symbols.py.
* Work RAM fields at their arcade addresses in the game bank.

WORK_RAM_BASE equ $4C00
WORK_RAM_END equ $4FEF
MAIN_TASK_LIST equ $4CC0

sprite equ $4C00 ; sprite code and color by slot (SPR_*). Code bits 7-6 are the flips
sprite_SIZE equ 2
sprite_COUNT equ 8
sprite_code equ $4C00
sprite_color equ $4C01
sprite_pos equ $4C10 ; sprite positions by slot, in hardware order
sprite_pos_SIZE equ 2
sprite_pos_COUNT equ 8
sprite_pos_x equ $4C10
sprite_pos_y equ $4C11
sprite_out equ $4C20 ; vblank's copy of sprite[], flips rotated into bits 1-0, for $4FF0
sprite_out_SIZE equ 2
sprite_out_COUNT equ 8
sprite_out_code equ $4C20
sprite_out_color equ $4C21
sprite_pos_out equ $4C30 ; vblank's copy of sprite_pos[], for $5060
sprite_pos_out_SIZE equ 2
sprite_pos_out_COUNT equ 8
sprite_pos_out_x equ $4C30
sprite_pos_out_y equ $4C31
fruit_path_index equ $4C40 ; COUNT: current place in fruit path
fruit_bounce_index equ $4C41 ; BCNT: current place within bounce
fruit_path_ptr equ $4C42 ; PATH: pointer to current fruit path (lo)
fruit_path_ptr_hi equ $4C43 ; PATH: pointer to current fruit path (hi)
gap_4c44 equ $4C44 ; undocumented
gap_4c44_LEN equ 60
task_list_tail_ptr equ $4C80 ; pointer to end of non-IRQ task list (lo)
task_list_tail_ptr_hi equ $4C81 ; pointer to end of non-IRQ task list (hi)
task_list_head_ptr equ $4C82 ; pointer to beginning of task list (lo)
task_list_head_ptr_hi equ $4C83 ; pointer to beginning of task list (hi)
SOUND_COUNTER equ $4C84 ; VBLANK sound counter (also SOUND_COUNTER)
timer_unused_4c85 equ $4C85 ; 8-bit counter unused
clock_hundredths equ $4C86 ; clock counter: hundredths
clock_seconds equ $4C87 ; clock counter: seconds
clock_minutes equ $4C88 ; clock counter: minutes
clock_hours equ $4C89 ; clock counter: hours
clock_limit_changes equ $4C8A ; counter-limit changes this frame
rng_unused_4c8b equ $4C8B ; random (unused)
rng_unused_4c8c equ $4C8C ; random (unused)
gap_4c8d equ $4C8D ; undocumented
gap_4c8d_LEN equ 3
timed_task_list equ $4C90 ; IRQ scheduled tasks (4C90-4CBF), 16 x 3 bytes
timed_task_list_LEN equ 48
main_task_list equ $4CC0 ; non-IRQ tasks (4CC0-4CCF), 16 x 2 bytes
main_task_list_LEN equ 64
pos equ $4D00 ; actor pixel positions (ACT_*)
pos_SIZE equ 2
pos_COUNT equ 5
pos_y equ $4D00
pos_x equ $4D01
mid_tile equ $4D0A ; actor tile, taken at the middle of the sprite
mid_tile_SIZE equ 2
mid_tile_COUNT equ 5
mid_tile_y equ $4D0A
mid_tile_x equ $4D0B
step equ $4D14 ; actor direction as a tile step
step_SIZE equ 2
step_COUNT equ 5
step_y equ $4D14
step_x equ $4D15
next_step equ $4D1E ; ghosts' chosen step; Ms. Pac's wanted step
next_step_SIZE equ 2
next_step_COUNT equ 5
next_step_y equ $4D1E
next_step_x equ $4D1F
prev_dir equ $4D28 ; ghosts' previous direction (ACT_*)
prev_dir_LEN equ 4
dir equ $4D2C ; actor direction (ACT_*), DIR_*
dir_LEN equ 5
tile equ $4D31 ; actor tile position
tile_SIZE equ 2
tile_COUNT equ 5
tile_y equ $4D31
tile_x equ $4D32
path_best_dir equ $4D3B ; pathfinding: best orientation found
pac_wanted_dir equ $4D3C ; wanted pacman orientation
path_opposite_dir equ $4D3D ; pathfinding: opposite orientation
path_from equ $4D3E ; pathfinding: the ghost's tile
path_from_SIZE equ 2
path_from_COUNT equ 1
path_from_y equ $4D3E
path_from_x equ $4D3F
path_target equ $4D40 ; pathfinding: the target tile
path_target_SIZE equ 2
path_target_COUNT equ 1
path_target_y equ $4D40
path_target_x equ $4D41
path_try equ $4D42 ; pathfinding: the neighbor tile being tried
path_try_SIZE equ 2
path_try_COUNT equ 1
path_try_y equ $4D42
path_try_x equ $4D43
path_min_dist_lo equ $4D44 ; pathfinding: minimum distance^2 (lo)
path_min_dist_hi equ $4D45 ; pathfinding: minimum distance^2 (hi)
pac_speed equ $4D46 ; Ms. Pac speed: normal, then energized
pac_speed_SIZE equ 4
pac_speed_COUNT equ 2
pac_speed_bits_0 equ $4D46
pac_speed_bits_1 equ $4D47
pac_speed_bits_2 equ $4D48
pac_speed_bits_3 equ $4D49
elroy2_speed equ $4D4E ; red's cruise elroy 2 speed
elroy2_speed_SIZE equ 4
elroy2_speed_COUNT equ 1
elroy2_speed_bits_0 equ $4D4E
elroy2_speed_bits_1 equ $4D4F
elroy2_speed_bits_2 equ $4D50
elroy2_speed_bits_3 equ $4D51
elroy1_speed equ $4D52 ; red's cruise elroy 1 speed
elroy1_speed_SIZE equ 4
elroy1_speed_COUNT equ 1
elroy1_speed_bits_0 equ $4D52
elroy1_speed_bits_1 equ $4D53
elroy1_speed_bits_2 equ $4D54
elroy1_speed_bits_3 equ $4D55
ghost_speed equ $4D56 ; ghost speeds, 3 per ghost (ACT_*): SPEED_NORMAL/BLUE/TUNNEL
ghost_speed_SIZE equ 4
ghost_speed_COUNT equ 12
ghost_speed_bits_0 equ $4D56
ghost_speed_bits_1 equ $4D57
ghost_speed_bits_2 equ $4D58
ghost_speed_bits_3 equ $4D59
ghost_orient_table equ $4D86 ; difficulty ghost orientation change table (4D86-4D93)
ghost_orient_table_LEN equ 14
ghost_home_move_counter equ $4D94 ; counter: ghost movement inside home
ghost_leave_home_units_lo equ $4D95 ; units before ghost leaves home (lo)
ghost_leave_home_units_hi equ $4D96 ; units before ghost leaves home (hi)
ghost_leave_home_idle_lo equ $4D97 ; inactivity counter for leave-home (lo)
ghost_leave_home_idle_hi equ $4D98 ; inactivity counter for leave-home (hi)
tunnel_slow equ $4D99 ; ghost is in a tunnel slowdown area
tunnel_slow_LEN equ 4
pac_move_delay equ $4D9D ; delay to update pacman movement
pills_since_pac_move equ $4D9E ; pills eaten before last pacman move
pills_after_death equ $4D9F ; pills eaten after death (ghost release)
substate equ $4DA0 ; ghost substate while alive
substate_LEN equ 4
ghosts_killed_pending equ $4DA4 ; # ghosts killed but collision not done yet
pac_death_anim equ $4DA5 ; pacman dead animation state
power_pill_active equ $4DA6 ; power pill effect active
frightened equ $4DA7 ; ghost is blue
frightened_LEN equ 4
kill_ghost_state equ $4DAB ; killing ghost state (0=none, 1-4=which)
ghost_state equ $4DAC ; ghost state: 0 alive, else eyes/returning home
ghost_state_LEN equ 4
diff_unused_4db0 equ $4DB0 ; difficulty related, appears unused
reverse equ $4DB1 ; actor must reverse (ACT_*)
reverse_LEN equ 5
cruise_elroy_1 equ $4DB6 ; 1st difficulty / cruise elroy 1 flag
cruise_elroy_2 equ $4DB7 ; 2nd difficulty / cruise elroy 2 flag
pink_exit_limit equ $4DB8 ; pink leave-home pill counter limit
blue_exit_limit equ $4DB9 ; blue leave-home pill counter limit
orange_exit_limit equ $4DBA ; orange leave-home pill counter limit
elroy1_pill_threshold equ $4DBB ; pills remaining for cruise elroy 1
elroy2_pill_threshold equ $4DBC ; pills remaining for cruise elroy 2
frightened_time_lo equ $4DBD ; frightened duration (lo)
frightened_time_hi equ $4DBE ; frightened duration (hi)
pac_entering_tunnel equ $4DBF ; 1 if pacman about to enter tunnel
ghost_anim_phase equ $4DC0 ; changes every 8 frames; ghost anim
ghost_orient_index equ $4DC1 ; orientation-change table index
ghost_orient_counter_lo equ $4DC2 ; ghost orientation change counter (lo)
ghost_orient_counter_hi equ $4DC3 ; ghost orientation change counter (hi)
frame_div8_counter equ $4DC4 ; 0..8; do work every 8 frames
death_counter_lo equ $4DC5 ; counter after pacman killed (lo)
death_counter_hi equ $4DC6 ; counter after pacman killed (hi)
path_try_dir equ $4DC7 ; current orientation being tried
frightened_flash_counter equ $4DC8 ; ghost color flash under big pill
rng_rom_ptr_lo equ $4DC9 ; RNG ROM pointer (lo), routine 2A23
rng_rom_ptr_hi equ $4DCA ; RNG ROM pointer (hi)
frightened_timer_lo equ $4DCB ; blue-ghost timer (lo); ceases at 0
frightened_timer_hi equ $4DCC ; blue-ghost timer (hi)
gap_4dcd equ $4DCD ; undocumented
coin_blink_counter equ $4DCE ; after insert coin; LED / 1UP blink
power_pill_flash_counter equ $4DCF ; power pill flash counter
ghosts_killed_count equ $4DD0 ; current killed ghosts 0..4
killed_ghost_anim equ $4DD1 ; killed ghost animation state
fruit_pos equ $4DD2 ; FRUITP: fruit position
fruit_pos_SIZE equ 2
fruit_pos_COUNT equ 1
fruit_pos_y equ $4DD2
fruit_pos_x equ $4DD3
fruit_points equ $4DD4 ; FVALUE: fruit points entry, or 0
gap_4dd5 equ $4DD5 ; undocumented
start_button_wait equ $4DD6 ; LED/start-button wait state
gap_4dd7 equ $4DD7 ; undocumented
gap_4dd7_LEN equ 41
game_mode equ $4E00 ; main routine number (init/demo/coin/play)
game_mode_sub0 equ $4E01 ; main routine 0 subroutine #
game_mode_sub1 equ $4E02 ; main routine 1 subroutine # (attract/demo)
game_mode_sub2 equ $4E03 ; main routine 2 subroutine #
level_state equ $4E04 ; level state subroutine # (2=pause ghosts)
gap_4e05 equ $4E05 ; undocumented
cutscene1_state equ $4E06 ; first cutscene state (pac-man)
cutscene2_state equ $4E07 ; second cutscene state
cutscene3_state equ $4E08 ; third cutscene state
player_number equ $4E09 ; current player: 0=P1, 1=P2
difficulty_ptr_lo equ $4E0A ; pointer to current difficulty settings (lo)
difficulty_ptr_hi equ $4E0B ; pointer to current difficulty settings (hi)
fruit1_released equ $4E0C ; FIRSTF: first fruit released/appeared
fruit2_released equ $4E0D ; SECONDF: second fruit flag
dots_eaten equ $4E0E ; DOTSEAT: pills eaten this level
pink_exit_counter equ $4E0F ; pill counter toward pink leaving home
blue_exit_counter equ $4E10 ; pill counter toward blue leaving home
orange_exit_counter equ $4E11 ; pill counter toward orange leaving home
died_this_level equ $4E12 ; 1 after dying; cleared when ghosts leave via 4D9F
level_number equ $4E13 ; current level
lives_real equ $4E14 ; real number of lives
lives_displayed equ $4E15 ; number of lives displayed
pill_bitmap equ $4E16 ; pill bitmaps (4E16-4E33)
pill_bitmap_LEN equ 30
power_pill_data equ $4E34 ; power pill data (4E34-4E37)
power_pill_data_LEN equ 4
level_data_copy equ $4E38 ; copy of level data (4E38-4E65)
level_data_copy_LEN equ 46
in_service_hist equ $4E66 ; last 4 SERVICE1 samples
in_coin2_hist equ $4E67 ; last 4 COIN2 samples
in_coin1_hist equ $4E68 ; last 4 COIN1 samples
coin_counter equ $4E69 ; coin→credits counter
coin_counter_timeout equ $4E6A ; coin counter timeout
dip_coins_per_credit equ $4E6B ; coins per credit (from DSW)
coins_inserted equ $4E6C ; number of coins inserted
dip_credits_per_coin equ $4E6D ; credits per coin
credits equ $4E6E ; credits; 0xFF = free play
dip_lives equ $4E6F ; lives per game (from DSW)
num_players equ $4E70 ; 0=1 player, 1=2 players
dip_bonus_life equ $4E71 ; bonus life threshold
dip_cocktail equ $4E72 ; cocktail mode
dip_difficulty_ptr_lo equ $4E73 ; difficulty settings pointer (lo)
dip_difficulty_ptr_hi equ $4E74 ; difficulty settings pointer (hi)
ghost_names_mode equ $4E75 ; ghost names mode 0/1
gap_4e76 equ $4E76 ; undocumented
gap_4e76_LEN equ 10
score_p1_lo equ $4E80 ; P1 score byte CC
score_p1_mid equ $4E81 ; P1 score byte BB
score_p1_hi equ $4E82 ; P1 score byte AA
bonus_life_p1 equ $4E83 ; P1 got bonus life?
score_p2_lo equ $4E84 ; P2 score byte CC
score_p2_mid equ $4E85 ; P2 score byte BB
score_p2_hi equ $4E86 ; P2 score byte AA
bonus_life_p2 equ $4E87 ; P2 got bonus life?
high_score_lo equ $4E88 ; high score byte CC
high_score_mid equ $4E89 ; high score byte BB
high_score_hi equ $4E8A ; high score byte AA
gap_4e8b equ $4E8B ; undocumented
CH1_FREQ0 equ $4E8C ; ch1 freq nibble 0
CH1_FREQ1 equ $4E8D ; ch1 freq nibble 1
CH1_FREQ2 equ $4E8E ; ch1 freq nibble 2
CH1_FREQ3 equ $4E8F ; ch1 freq nibble 3
CH1_FREQ4 equ $4E90 ; ch1 freq nibble 4
CH1_VOL equ $4E91 ; ch1 volume
CH2_FREQ1 equ $4E92 ; ch2 freq nibble 1
CH2_FREQ2 equ $4E93 ; ch2 freq nibble 2
CH2_FREQ3 equ $4E94 ; ch2 freq nibble 3
CH2_FREQ4 equ $4E95 ; ch2 freq nibble 4
CH2_VOL equ $4E96 ; ch2 volume
CH3_FREQ1 equ $4E97 ; ch3 freq nibble 1
CH3_FREQ2 equ $4E98 ; ch3 freq nibble 2
CH3_FREQ3 equ $4E99 ; ch3 freq nibble 3
CH3_FREQ4 equ $4E9A ; ch3 freq nibble 4
CH3_VOL equ $4E9B ; ch3 volume
effect equ $4E9C ; effect channels 1-3 (CH1_E_* ...)
effect_SIZE equ 16
effect_COUNT equ 3
effect_num equ $4E9C
effect_unused1 equ $4E9D
effect_cur_bit equ $4E9E
effect_p3 equ $4E9F
effect_p4 equ $4EA0
effect_p5 equ $4EA1
effect_p6 equ $4EA2
effect_p7 equ $4EA3
effect_p8 equ $4EA4
effect_p9 equ $4EA5
effect_pa equ $4EA6
effect_type equ $4EA7
effect_duration equ $4EA8
effect_dir equ $4EA9
effect_freq equ $4EAA
effect_volume equ $4EAB
wave equ $4ECC ; song channels 1-3 (CH1_W_* ...)
wave_SIZE equ 16
wave_COUNT equ 3
wave_num equ $4ECC
wave_unused1 equ $4ECD
wave_cur_bit equ $4ECE
wave_p3 equ $4ECF
wave_p4 equ $4ED0
wave_p5 equ $4ED1
wave_p6 equ $4ED2
wave_p7 equ $4ED3
wave_p8 equ $4ED4
wave_p9 equ $4ED5
wave_pa equ $4ED6
wave_type equ $4ED7
wave_duration equ $4ED8
wave_dir equ $4ED9
wave_freq equ $4EDA
wave_volume equ $4EDB
gap_4efc equ $4EFC ; undocumented
gap_4efc_LEN equ 4
intermission_flag equ $4F00 ; 1 during intermission / parts of attract
marquee_step equ $4F01 ; marquee bulb phase (0-15). Inside the stack page, above its depth
cutscene_script equ $4F02 ; cutscene actor script pointers, lo/hi per actor
cutscene_script_LEN equ 12
gap_4f0e equ $4F0E ; undocumented
gap_4f0e_LEN equ 2
cutscene_frame equ $4F10 ; cutscene actor animation step
cutscene_frame_LEN equ 6
gap_4f16 equ $4F16 ; undocumented
gap_4f16_LEN equ 2
cutscene_count equ $4F18 ; cutscene actor command countdown
cutscene_count_LEN equ 6
gap_4f1e equ $4F1E ; undocumented
gap_4f1e_LEN equ 2
cutscene_done equ $4F20 ; cutscene actor reached its END
cutscene_done_LEN equ 6
gap_4f26 equ $4F26 ; undocumented
gap_4f26_LEN equ 10
cutscene_frac equ $4F30 ; cutscene actor sub-pixel motion, 1/16 pixel
cutscene_frac_SIZE equ 2
cutscene_frac_COUNT equ 6
cutscene_frac_y equ $4F30
cutscene_frac_x equ $4F31
gap_4f3c equ $4F3C ; undocumented
gap_4f3c_LEN equ 4
cutscene_anim equ $4F40 ; cutscene actor animation table pointers, lo/hi per actor
cutscene_anim_LEN equ 12
gap_4f4c equ $4F4C ; undocumented
gap_4f4c_LEN equ 4
cutscene_sprite equ $4F50 ; cutscene sprite codes and colors, copied to sprite[1..6]
cutscene_sprite_SIZE equ 2
cutscene_sprite_COUNT equ 6
cutscene_sprite_code equ $4F50
cutscene_sprite_color equ $4F51
cpu_stack equ $4F5C ; CPU stack (4F5C-4FBF)
cpu_stack_LEN equ 100
gap_4fc0 equ $4FC0 ; undocumented
gap_4fc0_LEN equ 48
SpriteCode_code equ 0
SpriteCode_color equ 1
SpritePos_x equ 0
SpritePos_y equ 1
Coord_y equ 0
Coord_x equ 1
SpeedPattern_bits_0 equ 0
SpeedPattern_bits_1 equ 1
SpeedPattern_bits_2 equ 2
SpeedPattern_bits_3 equ 3
SoundChannel_num equ 0
SoundChannel_unused1 equ 1
SoundChannel_cur_bit equ 2
SoundChannel_p3 equ 3
SoundChannel_p4 equ 4
SoundChannel_p5 equ 5
SoundChannel_p6 equ 6
SoundChannel_p7 equ 7
SoundChannel_p8 equ 8
SoundChannel_p9 equ 9
SoundChannel_pa equ 10
SoundChannel_type equ 11
SoundChannel_duration equ 12
SoundChannel_dir equ 13
SoundChannel_freq equ 14
SoundChannel_volume equ 15
